### ISSUE TITLE
building java bindings on windows

### ISSUE THREAD

**Issue by williballenthin** [capstone-engine/capstone#1043]
The build recipes for the Java bindings are specific to *nix. They should also support Windows.

I may contribute these recipes when I am confident I have something working well. Others may feel to jump in, too.

For future reference, here is what I used to get the Java tests working on Windows 10:

- version:

    ```
    C:\Users\user\Documents\code\capstone\bindings\java (master)
    λ java -version
    java version "1.8.0_152"
    Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
    Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
    ```

 - compile `capstone.dll`:
   - open `msvc\capstone.sln` in visual studio 2017
   - upgrade everything
   - toolbar -> platform: x64
   - build project `capstone_dll`
   - output: `C:\Users\user\Documents\code\capstone\msvc\Debug\capstone.dll`

 - build bindings
   - binding generator is currently only for *nix, have to do this manually
   - review Makefile
   - generate constants:

      ```
      C:\Users\user\Documents\code\capstone\bindings (master)
      λ python const_generator.py java
      Generating bindings for java
      ```

   - fetch jna.jar
     - project: https://github.com/java-native-access/jna
     - url: http://search.maven.org/#artifactdetails%7Cnet.java.dev.jna%7Cjna%7C4.5.0%7C

   - compile bindings:

        ```
        C:\Users\user\Documents\code\capstone\bindings\java\capstone (master)
        λ javac -classpath C:\Users\user\Downloads\jna-4.5.0.jar Capstone.java Arm_const.java Arm64_const.java Mips_const.java X86_const.java Xcore_const.java Ppc_const.java Sparc_const.java Sysz_const.java Arm.java Arm64.java Mips.java X86.java Xcore.java Ppc.java Sparc.java Systemz.java
        Note: Some input files use unchecked or unsafe operations.
        Note: Recompile with -Xlint:unchecked for details.
        ```

    - build jar (note: you must be in the parent directory to get the JAR layout correct):

        ```
        C:\Users\user\Documents\code\capstone\bindings\java (master)
        λ jar cf capstone.jar capstone\*.class
        ```

 - run tests
   - copy `jna.jar` into current directory
   - copy `capstone.dll` into current directory
   - copy `capstone.jar` into current directory
   - run test:

      ```
      C:\Users\user\Documents\code\capstone\bindings\java (master)
      λ java -classpath jna.jar;capstone.jar;. Test
      ****************
      Platform: X86 16bit (Intel syntax)
      Code: 0x8d 0x4c 0x32 0x08 0x01 0xd8 0x81 0xc6 0x34 0x12 0x00 0x00
      Disasm:
      0x1000:         lea     cx, word ptr [si + 0x32]
      0x1003:         or      byte ptr [bx + di], al
      0x1005:         fadd    dword ptr [bx + di + 0x34c6]
      0x1009:         adc     al, byte ptr [bx + si]
      0x100b:
      [...]
      ```

**Comment by Rot127** [comment]
I close this for now, because the Java bindings have been abandoned for a while now. And the issue be found even if closed.
