### ISSUE TITLE
Unknow opcodes for MIPS32 BE

### ISSUE THREAD

**Issue by GH0st3rs** [capstone-engine/capstone#1054]
What am I doing wrong?

```python
>>> from capstone import *

>>> md = Cs(CS_ARCH_MIPS, CS_MODE_MIPS32|CS_MODE_BIG_ENDIAN)
>>> next(md.disasm(b'\x01\x20\x10\x2d', 0x100))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```
But if I use rasm2:
```bash
$ rasm2 -a mips -e -d '0120102d'
move v0, t1
```
Unknow opcodes:
0120102d -> move v0, t1
0080e82d -> move sp, a0
40ab5000 -> dmtc0 t3, $10
00a0402d -> move t0, a1
0080502d -> move t2, a0
01a0702d -> move t6, t5
40ac1000 -> dmtc0 t4, $2
...
and etc.

**Comment by andrewcalvano** [comment]
I ran into this as well. Additionally, it looks like llvm-mc in the latest llvm release fails to disassemble these instructions.
