### ISSUE TITLE
Python PyPI package doesn't work with pip install --user

### ISSUE THREAD

**Issue by pfalcon** [capstone-engine/capstone#1077]
A usecase: I'm using Capstone in my Python project, and I want to make it as easy as possible to install by end users. Virtualenvs are too advanced, system-wide installation via pip requires sudo and may conflict with distro package. The best solution would be to use `pip install --user`. However, that doesn't work successfully with the 3.0.4 package on PyPI:

~~~
$ pip3 install --user capstone
Collecting capstone
  Using cached capstone-3.0.4.tar.gz
[]
Successfully installed capstone-3.0.4

$ ./ScratchABit.py example-arm_32_arm.elf 
Traceback (most recent call last):
  File "./ScratchABit.py", line 980, in <module>
    CPU_PLUGIN = __import__(default_plugins.cpus[arch_id])
  File "/mnt/hdd/projects/ScratchABit/plugins/cpu/arm_32_arm_capstone.py", line 1, in <module>
    import capstone
  File "/home/pfalcon/.local/lib/python3.5/site-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
~~~

Looking at what was installed, `libcapstone.so` went into `~/.local/lib/python3.5/site-packages/usr/lib/python3/dist-packages/capstone`, while the Python code is at `~/.local/lib/python3.5/site-packages/capstone`.

I'm not sure what to blame here, maybe it's even a pip problem. But the end result is the same for end user - it doesn't work. An obvious workaround is to put .so in the same way as the Python source. And IMHO, it's worth to do it, to make seamless installation possible. (When installing into venv, .so ends up exactly by the source).

**Comment by pfalcon** [comment]
System: Ubuntu 16.04 x86_64.

**Comment by pfalcon** [comment]
Actually, it's worse than that - it doesn't work even when installed into virtualenv (tested with python3's builtin "venv" module). E.g. after install, .so ends up in `.venv/lib/python3.5/site-packages/usr/lib/python3/dist-packages/capstone`, while Python source is in .venv/lib/python3.5/site-packages/capstone

Steps to reproduce:

~~~
$ mkdir capstone
$ python3 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip3 install capstone
Collecting capstone
Installing collected packages: capstone
Successfully installed capstone-3.0.4
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(.venv) $ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import capstone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.venv/lib/python3.5/site-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
>>> 
(.venv) $ ls -l .venv/lib/python3.5/site-packages/capstone
total 220
-rw-rw-r-- 1 pfalcon pfalcon 22523 Jan 15 21:19 arm64_const.py
-rw-rw-r-- 1 pfalcon pfalcon  1923 Jan 15 21:19 arm64.py
-rw-rw-r-- 1 pfalcon pfalcon 14736 Jan 15 21:19 arm_const.py
-rw-rw-r-- 1 pfalcon pfalcon  1882 Jan 15 21:19 arm.py
-rw-rw-r-- 1 pfalcon pfalcon     0 Jan 15 21:19 hexagon_const.py
-rw-rw-r-- 1 pfalcon pfalcon   999 Jan 15 21:19 hexagon.py
-rw-rw-r-- 1 pfalcon pfalcon 27980 Jan 15 21:19 __init__.py
-rw-rw-r-- 1 pfalcon pfalcon 16947 Jan 15 21:19 mips_const.py
-rw-rw-r-- 1 pfalcon pfalcon   924 Jan 15 21:19 mips.py
-rw-rw-r-- 1 pfalcon pfalcon 23906 Jan 15 21:19 ppc_const.py
-rw-rw-r-- 1 pfalcon pfalcon  1293 Jan 15 21:19 ppc.py
drwxrwxr-x 2 pfalcon pfalcon  4096 Jan 15 21:19 __pycache__
-rw-rw-r-- 1 pfalcon pfalcon  9552 Jan 15 21:19 sparc_const.py
-rw-rw-r-- 1 pfalcon pfalcon  1048 Jan 15 21:19 sparc.py
-rw-rw-r-- 1 pfalcon pfalcon  1036 Jan 15 21:19 systemz.py
-rw-rw-r-- 1 pfalcon pfalcon 15258 Jan 15 21:19 sysz_const.py
-rw-rw-r-- 1 pfalcon pfalcon 35841 Jan 15 21:19 x86_const.py
-rw-rw-r-- 1 pfalcon pfalcon  1931 Jan 15 21:19 x86.py
-rw-rw-r-- 1 pfalcon pfalcon  3353 Jan 15 21:19 xcore_const.py
-rw-rw-r-- 1 pfalcon pfalcon  1004 Jan 15 21:19 xcore.py
(.venv) $ ls -l .venv/lib/python3.5/site-packages/usr/lib/python3/dist-packages/capstone/
total 2844
-rwxrwxr-x 1 pfalcon pfalcon 2912064 Jan 15 21:19 libcapstone.so
~~~

**Comment by pfalcon** [comment]
> Actually, it's worse than that - it doesn't work even when installed into virtualenv

I'm taking that back. The story here is:

1. Installed into venv, it worked.
2. I tried installing with pip install --user, that didn't work, but also produced hosed .whl file and cached it.
3. On all the future installs (including into a venv), the broken cached packed was used.

`pip3 --no-cache-dir install capstone` protects against broken cached packages like that.

**Comment by pfalcon** [comment]
Ok, so breakage comes from wheels. The way to disable whl creation appears to be --no-cache-dir.

With that flag, both --user and venv installs work well.

**Comment by rhelmot** [comment]
Hi - could you try using `pip install --pre --user capstone`? there are many many many changes and fixes to the python installation, but they are only available as pre-release. This has been the case for nearly a year.

**Comment by XVilka** [comment]
@kabeor @aquynh probably worth closing too
