### ISSUE TITLE
cann't correctly disassembly PPC instruction '\x41\x81\x00\x00'

### ISSUE THREAD

**Issue by gh0stZerO** [capstone-engine/capstone#1117]
`python
from capstone import *
from capstone.ppc import *

base_addr = 0x8000f000
code = b'\x41\x81\x00\x00'
md = Cs(CS_ARCH_PPC, CS_MODE_BIG_ENDIAN)
for j in md.disasm(code, base_addr):
    print j.op_str
`
## 

then you will find the
j.op_str =='' is True
code = b'\x41\x82\x00\x00'
code = b'\x40\x82\x00\x00'
code = b'\x41\x80\x00\x00'
code = b'\x40\x80\x00\x00'

**Comment by aquynh** [comment]
can you clarify: what is wrong, and what is expected output?

**Comment by gh0stZerO** [comment]
code = b'\x41\x81\x00\x00'
the IDA output is : 
.text:0x8000f000 loc_8000f000:
.text:0x8000f000                 bgt        loc_8000f000
but the capstone output is ''

![image](https://user-images.githubusercontent.com/38447431/39307311-116ae30a-4995-11e8-9311-f8ff6bf4f113.png)


😁 😁 😁

**Comment by aquynh** [comment]
fixed now in the "next" branch:

```
$ cstool ppc64be '41820000 40820000 41800000 40800000' 0x8000f000
8000f000  41 82 00 00  bt	cr0eq, 0x8000f000
8000f004  40 82 00 00  bf	cr0eq, 0x8000f004
8000f008  41 80 00 00  bt	cr0lt, 0x8000f008
8000f00c  40 80 00 00  bf	cr0lt, 0x8000f00c
```

**Comment by Rot127** [comment]
Closed with https://github.com/capstone-engine/capstone/pull/2013
