### ISSUE TITLE
Can't decode MRS.W  R3, MSP (ARM-Thumb mode)

### ISSUE THREAD

**Issue by don1001** [capstone-engine/capstone#1228]
Can't decode MRS.W  R3, MSP (ARM-Thumb mode)

IDA:
```
.text:00000130 EF F3 08 83                 MRS.W   R3, MSP`
```

Capstone (next branch)
```
me@me ~ $ cstool -d thumb EFF30883
ERROR: invalid assembly code
```

**Comment by don1001** [comment]
> @don1001 @aquynh
> What is needed to add it?

I don't know, but it's instruction in common in bootloader code so would be good to decode it.

**Comment by aquynh** [comment]
looks like CortexM mode? actually Capstone can decode this.

```
$ cstool cortexm "EF F3 08 83"
 0  ef f3 08 83  mrs	r3, msp
```
