### ISSUE TITLE
error in MIPS big endian assembly, instruction is '00c0502d'

### ISSUE THREAD

**Issue by yasong** [capstone-engine/capstone#1267]
```python
#filename: mipsbe.py
import sys
import os
import binascii
from capstone import *
from capstone.mips import *

def main():
	md = Cs(CS_ARCH_MIPS, CS_MODE_MIPS32 + CS_MODE_BIG_ENDIAN)
	address = 0x80008000
	address = int(sys.argv[2], 16)
	inst = sys.argv[1]
	for j in md.disasm(binascii.a2b_hex(inst), address):
		print "0x%x:  %s %s" %  (j.address, j.mnemonic, j.op_str)

if __name__ == '__main__':
	main()
```

```bash
$python mipsbe.py 00c0502d 373275a0
```
capstone returns none, but ida returns 'move $t2. $a2'
other assembler returns 
![image](https://user-images.githubusercontent.com/9759407/47068001-ae99ce00-d21d-11e8-8198-3af6e7d62cb8.png)
[https://www.eg.bucknell.edu/~csci320/mips_web/](https://www.eg.bucknell.edu/~csci320/mips_web/)

**Comment by radare** [comment]
Just use r2 or the r_asm api if you need this programatically. It was fixed in there several years ago
