### ISSUE TITLE
`groups` is unexpectedly empty for many x86 instructions

### ISSUE THREAD

**Issue by parasyte** [capstone-engine/capstone#128]
When I enable detail mode, I expected the `groups` field to have at least one entry. But many x86 instructions are returned with empty `groups`. Here's a minimal test case:

``` python
from capstone import *

CODE = "\x55\x48\x89\xe5"

md = Cs(CS_ARCH_X86, CS_MODE_64)
md.detail = True
for i in md.disasm(CODE, 0x1000):
    print "0x%x:\t%s\t%s\tgroups = %s" % (
        i.address, i.mnemonic, i.op_str, str(i.groups)
    )
```

Two instructions will be printed: the first instruction has `X86_GRP_MODE64` set; that looks right. But the second instruction has empty `groups`. Certainly this instruction should also be at least part of the same `X86_GRP_MODE64` group?

Actual output:

```
0x1000: push    rbp     groups = [17]
0x1001: mov     rbp, rsp        groups = []
```

This bug seems to affect many, many instructions, not just `mov`.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, plz feel free to open a new issue if there is progress.
thx :)
