### ISSUE TITLE
MIPS pseudo-instructions

### ISSUE THREAD

**Issue by jvoisin** [capstone-engine/capstone#146]
IDA Pro is disassembling MIPS into pseudo-instruction:

```
.text:00416CB4 26 00 01 3C+                li      $at, 0x269EC
```

while capstone is not:

```
0x00416cb4    2600013c     lui at, 0x26
0x00416cb8    c39e2134     ori at, at, 0x9ec3
```

It would be nice to be able to get both in capstone :)

**Comment by learn-more** [comment]
@jvoisin : The '+' is just an indication to you that there are more bytes to display, but your current setting limits ida to less.
(Options->General->Disassembly->Number of opcode bytes)

**Comment by kabeor** [comment]
Close this issue for now because of legacy, plz feel free to open a new issue if there is progress.
thx :)
