### ISSUE TITLE
ARM writeback on post-index 

### ISSUE THREAD

**Issue by deadeert** [capstone-engine/capstone#1507]
Hello, 

I just wonder why post-index for instruction such as LDRD Rd, [Rs], #imm is considered as writeback ?
 e0c020d4 	ldrd	r2, [r0], #4
>>> i=tuple(cs.disasm(b'\xd4\x20\xc0\xe0',0))[0]
>>> i.writeback
True

According to ARM  manual it should not be.

**Comment by c01dkit** [comment]
Hi @deadeert , In your case, Rs will be modified (writeback) after loading 4 bytes Rs+imm. You can refer to the manual here [ARM Cortex-M3](https://developer.arm.com/documentation/dui0552/a/the-cortex-m3-instruction-set/memory-access-instructions/ldr-and-str--immediate-offset?lang=en)

**Comment by Rot127** [comment]
@kabeor Can be closed I guess
