### ISSUE TITLE
MIPS Coprocessor 0 register naming

### ISSUE THREAD

**Issue by nurmukhametov** [capstone-engine/capstone#1508]
There is an issue with naming of coprocessor 0 registers:

```
./cstool/cstool -d mips64be 40021000
 0  40 02 10 00  mfc0   $v0, $v0, 0
        ID: 405 (mfc0)
        op_count: 3
                operands[0].type: REG = v0
                operands[1].type: REG = v0
                operands[2].type: IMM = 0x0
        Groups: stdenc mips32 
```

This instruction moves the contents of a COP0 register 2 (EntryLo0) to a general register 2 ($v0).

It should be 
```
mfc0 $v0, EntryLo0, 0
```
or at least
```
mfc0 $v0, $2, 0
```

**Comment by junchao-loongson** [comment]
I want to know how the inc file in the capstone\arch\Mips\ directory is generated so that I can fix this bug

**Comment by junchao-loongson** [comment]
> 
> 
> I want to know how the inc file in the capstone\arch\Mips\ directory is generated so that I can fix this bug

I now know how the *inc file is generated, I will try to fix this bug.
