### ISSUE TITLE
update_flags not working as expected for some ARM instructions

### ISSUE THREAD

**Issue by cnheitman** [capstone-engine/capstone#1568]
There seems to be an issue with `update_flags` on some ARM instruction (at least for `ADC` and `SBC`). More precisely, Capstone reports `update_flags` as `true` when it should be `false` (according to ARM reference manual).

The following code snippet shows the issue:

```python
from capstone import *
from capstone.arm import *

CODE = [
    b"\x03\x00\xa1\xe0", # adcal r0, r1, r3
    b"\x03\x00\xb1\xe0", # adcsal r0, r1, r3
    b"\x03\x00\xc1\xe0", # sbcal r0, r1, r3
    b"\x03\x00\xd1\xe0", # sbcsal r0, r1, r3
    b"\x03\x00\x81\xe0", # addal r0, r1, r3
    b"\x03\x00\x91\xe0", # addsal r0, r1, r3
    b"\x03\x00\x41\xe0", # subal r0, r1, r3
    b"\x03\x00\x51\xe0", # subsal r0, r1, r3
]

md = Cs(CS_ARCH_ARM, CS_MODE_ARM)
md.detail = True

for code in CODE:
    for i in md.disasm(code, 0x1000):
        print("{} {} ; update_flags: {}".format(i.mnemonic, i.op_str, i.update_flags))
```

Output:

```shell
adc r0, r1, r3 ; update_flags: True
adcs r0, r1, r3 ; update_flags: True
sbc r0, r1, r3 ; update_flags: True
sbcs r0, r1, r3 ; update_flags: True
add r0, r1, r3 ; update_flags: False
adds r0, r1, r3 ; update_flags: True
sub r0, r1, r3 ; update_flags: False
subs r0, r1, r3 ; update_flags: True
```

Here `update_flags` is `true` for `ADC` and `SBC` when it should be `false` (generally, it should only report `true` for those instructions with the `s` suffix). Notice that this does not happen with neither `ADD` nor `SUB`.

**Comment by aquynh** [comment]
You may use "cstool -d" to avoid writing code.

Is this on the "next" branch?

**Comment by aquynh** [comment]
I have been thinking about starting "Unicorn2", that sync with latest Qemu
version. I am aware that big companies have been using Unicorn, and the
number of really cool projects depending on it is growing.

This takes a lot of time & effort, but am not sure Gofundme is the right
way to get fund, or better to find some sponsors from other sources.

Any ideas?

**Comment by aquynh** [comment]
Ah wrong thread, pls ignore.

**Comment by cnheitman** [comment]
Thanks, I wasn't aware of the tool.
I tested it originally on version 4.0.1. 
I've just tried on "next" branch and it also reports `true` when it should  report `false`.
Retaled to this issue #247 (apparently reintroduced at some point).

**Comment by JonathanSalwan** [comment]
@aquynh up :)

**Comment by Rot127** [comment]
Gets closed with https://github.com/capstone-engine/capstone/pull/1949

**Comment by pipe01** [comment]
This still seems to be an issue on 5.0.1

**Comment by Rot127** [comment]
Are you able to use the `next` branch in your project? This fix is not so easily ported back. Because, from `v5` on, we introduced a new updater (auto-sync) and changed the architecture module structure quite a bit.
If you use `next` you would get more precise details, alias detection and is based on LLVM 16 (soon 18).
