### ISSUE TITLE
Missing operand access specifiers and identification of Z vector registers for SVE instructions within the 'next' branch.

### ISSUE THREAD

**Issue by jj16791** [capstone-engine/capstone#1670]
A large majority of SVE instructions are missing access specifiers for all their operands, whilst some SVE instructions' Z vector registers are being labelled as ARM64_REG_INVALID. The latter cases are primarily seen in Load and Store instructions (e.g. st1w, ld1rw, ld1w, etc).

**Comment by Rot127** [comment]
I added this to the closing list of #2026 since it adds way better support for SVE. Feel free to check this again and provide a failure case if it isn't working after #2026 was merged.
