### ISSUE TITLE
x86: "in eax,0x0c"  x86.encoding.imm_size must be 1

### ISSUE THREAD

**Issue by inaryart** [capstone-engine/capstone#1733]
It's size shouldn't be 4

**Comment by keenk** [comment]
Are you using master or the "next" branch? The next branch is the most current.

Assuming the original bytes were e5 0c, the next branch shows the size of the immediate operand as 1

**Comment by notes365** [comment]
i curenrtly use Version 4.0.2,i'm waiting for the next stable version

**Comment by keenk** [comment]
You may be waiting a long time. Next branch is way ahead of master and has been for a long time
