### ISSUE TITLE
Upgrade to modern CMake

### ISSUE THREAD

**Issue by mrexodia** [capstone-engine/capstone#1826]
Hello,

CMake 2.8.11 is now almost 10 years old. The latest CMake version (3.22) is extremely widely available (for example through `pip` and all major package managers) and I think it would be good to upgrade capstone to a more modern CMake version.

For example 3.15 added the [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html) target property which would help get rid of all the (discouraged) changes to CMAKE_CXX_FLAGS etc.

There is also the issue of mixing a static and shared library of the same project into the `CMakeLists.txt`. This makes packaging capstone in a canonical way difficult and a user is extremely unlikely to use both in their project (either they are all linux dynamic linking or they want to statically link everything in my experience).

Currently there is also no proper packaging support for capstone (`find_package(capstone)`).

I already addressed these issues (https://github.com/LLVMParty/capstone/commit/718a5d58ca7a9fc50f7d5c2c4b57533a15847aa9) and I'm willing to put in the work, but I would like to discuss it first.

Here is an example what the usage looks like with modern cmake:

https://github.com/LLVMParty/Triton/blob/ef7169e0bc2bcdc9397acea161cbc02b7eea08e6/CMakeLists.txt#L109-L125

Duncan

**Comment by aquynh** [comment]
Yes, pls go ahead.
