### ISSUE TITLE
Inconsistent Python Bindings for X86 Encoding Fields

### ISSUE THREAD

**Issue by davepfeiffer** [capstone-engine/capstone#1829]
The fields of cs_x86_encoding are added to the cx_x86 top level instead of being referenced through cs_x86.cs_x86_encoding.<encoding_field>

Is this the intended way to reference encoding fields? The location was quite deceptive when using other languages' (mainly [rust's](https://docs.rs/capstone-sys/0.11.0/capstone_sys/struct.cs_x86.html#structfield.encoding)) as reference. 

Below are the lines affecting the fields. I would be happy to submit a pull request if desired.

https://github.com/capstone-engine/capstone/blob/ea6b1a264689311ab11efb60354461e7990a2581/bindings/python/capstone/__init__.py#L645

https://github.com/capstone-engine/capstone/blob/ea6b1a264689311ab11efb60354461e7990a2581/bindings/python/capstone/x86.py#L83

**Comment by aquynh** [comment]
Probably we can support both.

If you send PR, pls update test_x86.py, too.
