### ISSUE TITLE
AArch64: dc, ic instructions missing operand

### ISSUE THREAD

**Issue by adamjseitz** [capstone-engine/capstone#1856]
On aarch64, `ic` and `dc` instructions are missing an entry in the instruction detail's `operands` array for the `ic_op` and `dc_op` operands; the operand array contains only the register.

I tried disassembling these with `cstool` built from the commit on the `next` branch (31af3c3e3bf75ca5074715fe966094606c816ba6).

```
$ cstool -d arm64 '22 7b 0b d5'
 0  22 7b 0b d5  dc     cvau, x2
        ID: 947 (dc)
        op_count: 1
                operands[0].type: REG = x2

$ cstool -d arm64 '20 75 0b d5'
 0  20 75 0b d5  ic     ivau, x0
        ID: 946 (ic)
        op_count: 1
                operands[0].type: REG = x0
```

**Comment by kabeor** [comment]
Solved, close.
