### ISSUE TITLE
X86-64 disassembly 'mov rcx,[xxxxxxxxx]'

### ISSUE THREAD

**Issue by ashyerv** [capstone-engine/capstone#1858]
![1](https://user-images.githubusercontent.com/101718937/159153050-81909cd2-7c85-4d73-974b-af63c739f0cb.png)

is my issus?

**Comment by xxr0ss** [comment]
`rip` (in `mov rcx, qword ptr [rip + 0x3a48d4f]`) == the address of the next instruction (`0x1418C1291`).
`mov rcx, [0x145309FE0]` and `mov rcx, qword ptr [rip + 0x3a48d4f]` are the same.

**Comment by ashyerv** [comment]
> 

thanks reply.
but this address is static address. i can't running..   
i know  mov rcx, [0x145309FE0] == mov rcx, qword ptr [rip + 0x3a48d4f]
but i only want  >-- 0x145309FE0 <---
can auto calc it ?

**Comment by ashyerv** [comment]
OK.use X86_REL_ADDR(xxx) !
