### ISSUE TITLE
'regs_access()' is still not supported in MIPS

### ISSUE THREAD

**Issue by yasong** [capstone-engine/capstone#1869]
when using ‘res_access()’ in MIPS, capstone raises an error:
```
capstone.CsError: Invalid/unsupported architecture(CS_ERR_ARCH)
```
capstone version:
```
capstone (5.0.0)
```
When will capstone support regs_access?
Thank you.

**Comment by kabeor** [comment]
We still have no plan, becouse capstone still based on LLVM9 for now. And we want to sync with latest LLVM, welcome to contribute if you are familiar with LLVM.
