### ISSUE TITLE
Download page points to the old git repo

### ISSUE THREAD

**Issue by huth** [capstone-engine/capstone#1888]
http://www.capstone-engine.org/download.html still points to the old git repo https://github.com/aquynh/capstone - I think this should be updated to point to https://github.com/capstone-engine/capstone nowadays instead?

**Comment by huth** [comment]
I just noticed that the website has a separate repository, so I created a pull request there now instead:

https://github.com/capstone-engine/capstone-engine.github.io/pull/8

**Comment by aquynh** [comment]
thank you!
