### ISSUE TITLE
Missing sync tools instructions for PowerPC arch on next

### ISSUE THREAD

**Issue by terorie** [capstone-engine/capstone#1899]
The PowerPC target on the next branch is missing instructions on how to run `llvm-tblgen`.

Running `gen-tablegen-arch.sh` only works with LLVM 7.0.1 and with a small patch to one of the TableGen files (replacing `PPCCustomInserterPseudo` with `Pseudo` in `PPCInstrHTM.td`)

**Comment by kabeor** [comment]
Solved in #1898
