### ISSUE TITLE
SME Index instruction alias printing is not always valid

### ISSUE THREAD

**Issue by FinnWilkinson** [capstone-engine/capstone#1924]
If a SME instruction such as `ld1w	{za0h.s[w12, 2]}, p0/z, [x0]` is disassembled then it is printed via AArch64GenAsmWriter.inc:printAliasInstr. In the new AArch64 support a function called `set_sme_index` is used to print SME Tile indexes (`za0h.s[w12, 2]`) in the correct form : 
```
operands[0].type: REG = zas0
			operands[0].index.base: REG = w12
			operands[0].index.disp: 0x2
```
But this function is not present in the printing logic at the end of printAliasInstr, hence it is recognised and stored as a memory operand instead : 
```
0  02 00 9f e0  ld1w	{za0h.s[w12, 2]}, p0/z, [x0]
	ID: 457 (ld1w)
	op_count: 4
		operands[0].type: REG = zas0
		operands[1].type: MEM
			operands[1].mem.base: REG = w12
		operands[2].type: REG = p0
		operands[3].type: MEM
			operands[3].mem.base: REG = x0
	Registers read: w12 x0
```

**Comment by kabeor** [comment]
Fixed. Close now.
