### ISSUE TITLE
mips32r2 bugs

### ISSUE THREAD

**Issue by wodz** [capstone-engine/capstone#209]
1) mtc0 instruction is wrongly decoded (some examples below)
                            capstone                                objdump
4080e000        mtc0    $zero, $gp, 0             mtc0    zero,c0_taglo
4080e800        mtc0    $zero, $sp, 0             mtc0    zero,c0_taghi
40886000        mtc0    $t0, $t4, 0                  mtc0    t0,c0_status

2) synci instruction is not recognized by capstone
                               capstone                                      objdump
051f0000        .byte   0x00, 0x00, 0x1f, 0x05          synci   0(t0)

3) jump instructions wrongly decode target address(j, jal). This instructions are not absolute (the new address is computed by taking the upper 4 bits of the PC, concatenated to the 26 bit immediate value shifted left by two, and the lower two bits are 00, so the address created remains word-aligned.)
                                                  capstone                               objdump
0x9404040c:     09010216        j       0x4040858                     j       94040858

As as side note - I couldn't find any documentation about capstone internals so I could fix thouse bugs myself without huge effort.

**Comment by wodz** [comment]
any news when synci support will be merged?

**Comment by aquynh** [comment]
On Fri, Jan 23, 2015 at 5:47 PM, Marcin Bukat <notifications@github.com>
wrote:

> any news when synci support will be merged?
>

sometime in Feb, when i have more free time.

also, there are lots of changes in Mips core in upstream (LLVM) at the
moment, so i want to wait for a bit more.

thanks.

**Comment by aquynh** [comment]
@wodz, the `next` branch now supports *synci* instructions.

the `next` branch now also handle a lot more Mips instructions than before. let me know if you find any issue, or any instructions still missing.

thanks
