### ISSUE TITLE
PPC 0x000EAEB0 callthru special instruction missing

### ISSUE THREAD

**Issue by wargio** [capstone-engine/capstone#258]
I was using cenigma and i noticed that was missing the `callthru` (`0x000EAEB0`) instruction in the PPC core:
It's an instruction used to interact with the IBM PPC simulator. I saw dozen of time this instruction inside kernel sources..

Some references:
[hello_cores/callthru_config.h](https://repo.anl-external.org/viewvc/bgq-driver/V1R1M1/firmware/tests/hello_cores/callthru_config.h?revision=1&content-type=text/plain&pathrev=1)
[hello_cores/sim_support_code.h](https://repo.anl-external.org/viewvc/bgq-driver/V1R1M1/firmware/tests/hello_cores/sim_support_code.h?revision=1&content-type=text%2Fplain&pathrev=1)
[asm-powerpc/systemsim.h Linux Kernel](https://kernel.googlesource.com/pub/scm/linux/kernel/git/ericvh/systemsim/+/systemsim-2.6.19/include/asm-powerpc/systemsim.h)

Should be added this to capstone?

**Comment by aquynh** [comment]
On Sat, Jan 31, 2015 at 10:13 PM, Giovanni <notifications@github.com> wrote:

> I was using cenigma and i noticed that was missing the callthru (
> 0x000EAEB0) instruction in the PPC core:
> It's an instruction used to interact with the IBM PPC simulator. I saw
> dozen of time this instruction inside kernel sources..
>
> Some references:
> hello_cores/callthru_config.h
> <https://repo.anl-external.org/viewvc/bgq-driver/V1R1M1/firmware/tests/hello_cores/callthru_config.h?revision=1&content-type=text/plain&pathrev=1>
> hello_cores/sim_support_code.h
> <https://repo.anl-external.org/viewvc/bgq-driver/V1R1M1/firmware/tests/hello_cores/sim_support_code.h?revision=1&content-type=text%2Fplain&pathrev=1>
> asm-powerpc/systemsim.h Linux Kernel
> <https://kernel.googlesource.com/pub/scm/linux/kernel/git/ericvh/systemsim/+/systemsim-2.6.19/include/asm-powerpc/systemsim.h>
>

i will take a closer look and if possible, will add it into the major next
PPC update.

thanks.
