### ISSUE TITLE
Use README in markdown

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#283]
And also add this coverity badge: https://scan.coverity.com/projects/1673/badge.svg?flat=1 to see if the next branch is building and how many issues are there

**Comment by radare** [comment]
The rest of .TXT files should be converted to markdown too.

**Comment by aquynh** [comment]
besides having the badge, what else is good with having README in markdown?

**Comment by radare** [comment]
Different font size for titles, code blocks, bold, italic, standard parsing for embeding it in the website, clickable links, etc
