### ISSUE TITLE
MIPS pseudoinstruction 'la'

### ISSUE THREAD

**Issue by shibumi** [capstone-engine/capstone#286]
Hey everybody,
There is a pseudoinstruction in MIPS called 'la'. I am missing that in capstone. I think this would increase readability if you would implement that pseudoinstruction in capstone.

References:
https://en.wikibooks.org/wiki/MIPS_Assembly/Pseudoinstructions

**Comment by aquynh** [comment]
Please also provide the input (hexcode), endian mode, hardware mode so i
can test it. Thanks.

**Comment by nihilus** [comment]
Oh... Though one. I donnu if it is possible in a deterministic way to disassemble to 'la' (See MIPS Run has info on this).

**Comment by nihilus** [comment]
One could look at how the $at register is used (this is the was IDA Pro does it) AFAIU.
