### ISSUE TITLE
Support conditional privileged instructions

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#288]
PowerPC have privileged instructions, but only some of their constructions are like this. for example see MFSPR:

http://www-01.ibm.com/support/knowledgecenter/ssw_aix_71/com.ibm.aix.alangref/idalangref_mfspr_spr_instrs.htm

depending on the arguments it is privileged or not. How to handle this in Capstone?

**Comment by aquynh** [comment]
this depends on the context, so the group is best handled dynamically somewhere in `PPCInstPrinter.c` (meaning adding `PPC_GRP_PRIVILEGE` to `@groups` array at run-time)
