### ISSUE TITLE
undefined vs unpredictible instructions

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#291]
is there a way to determine if an instruction is undefined or just unpredictible?

This is possible with GNU binutils. The difference between them is that an unpredictible instruction is a valid instruction with invalid arguments. and an undefined one is just one that doesnt have any valid decoding.

**Comment by radare** [comment]
Note that both (undefined and unpredictable) instructions are invalid.

**Comment by aquynh** [comment]
not at the moment. this requires some changes in the way we report error by decoder & printer layers.
