### ISSUE TITLE
Build files

### ISSUE THREAD

**Issue by learn-more** [capstone-engine/capstone#314]
Wouldnt it make sense to delete all platform specific build files,
and only leave the cmake files in?

That way only the cmake files should be maintained,
now the cmake, the msvc, the xcode and makefiles should all be kept up to date.

**Comment by aquynh** [comment]
yes, some also proposed that, but i think it is better to have MSVC & XCode project there, so people without CMake can still compile code. there is not much work to maintain them anyway.

thanks.

**Comment by learn-more** [comment]
It might not be too much work,
but you need access to 3 or 4 platforms to test all changes, which means contributors most likely won't check or even update them all.

if having to install cmake is an issue, you could consider premake.
it's something like cmake, but lua-based, and can be distributed as single executable.

**Comment by aquynh** [comment]
will keep this in mind, thanks!
