### ISSUE TITLE
LR not in ARM regs_write for BLX

### ISSUE THREAD

**Issue by zachriggle** [capstone-engine/capstone#321]
The BL and BLX instructions both modify the LR register in addition to PC.  This is not captured in the "implicit registers", at least as far as the example (slightly modified) would have be believe.

```
0x38:   blx     r3
        Implicit registers read:  pc 
        Implicit registers written:  pc 
        This instruction belongs to groups: 1 147 138
```

```
from capstone import *
from capstone.arm import *

md = Cs(CS_ARCH_ARM, CS_MODE_ARM)
md.detail = True

for i in md.disasm('3\xff/\xe1', 0x38):
    print "0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str)

    if len(i.regs_read) > 0:
        print("\tImplicit registers read: "),
        for r in i.regs_read:
            print("%s " %i.reg_name(r)),
        print

    if len(i.regs_write) > 0:
        print("\tImplicit registers written: "),
        for r in i.regs_read:
            print("%s " %i.reg_name(r)),
        print

    if len(i.groups) > 0:
        print("\tThis instruction belongs to groups:"),
        for g in i.groups:
            print("%u" %g),
        print
```

**Comment by aquynh** [comment]
just fixed in the "next" branch, can you confirm? thanks.

**Comment by zachriggle** [comment]
What's the easiest way to build just the Python bindings for Next?

**Comment by zachriggle** [comment]
Also, the fix you made in 34c5ae39e127c757b41ea4822d41bd4d304bef1d should probably apply to ARM64 as well

**Comment by aquynh** [comment]
would you mind submitting a PR to fix that issue for Arm64?

**Comment by zachriggle** [comment]
Sure I can check it out.

**Comment by aquynh** [comment]
great, looks forward to your PR. 

please make sure to do that on the "next" branch. a fix for "master" is also appreciated, if the same commit cannot be merged into "master". thanks.
