### ISSUE TITLE
branch and indirect_branch

### ISSUE THREAD

**Issue by learn-more** [capstone-engine/capstone#325]
It would be usefull if there was some info in the detail structure about a branch being relative.
Seeing as this info is already known, adding it would be trivial.

What would be the best approach for this?

**Comment by aquynh** [comment]
perhaps we can simply add a new field like `bool indirect_branch;` into `cs_XXX` structure? (XXX = arch name)

**Comment by learn-more** [comment]
That would work fine.

PR to master or next?

**Comment by aquynh** [comment]
please do that on the "next" branch, as 3.x version is now in maintenance mode & get no major changes (i.e those change the interface).

so this field is only relevant when its group = GRP_JUMP, right?

thanks.

**Comment by aquynh** [comment]
another approach is to create a new group, such as CS_GRP_INDIRECT_BRANCH. this sounds cleaner, right?

**Comment by learn-more** [comment]
Yes, it's only relevant for GRP_JUMP (in this case)
I was hestitant to make it a group, because it would make checking for the group harder.
(Unless in the case of it being an indirect branch, both branch and indirect branch would be set, in that case it would not break anything, and still be simple to check)

**Comment by aquynh** [comment]
yes, indirect jump instructions will get 2 groups CS_GRP_JUMP & CS_GRP_BRANCH_INDIRECT. sounds fine to me

**Comment by aquynh** [comment]
sorry, i mean CS_GRP_BRANCH_RELATIVE (not INDIRECT)

**Comment by learn-more** [comment]
The whole group_name_maps is a bit messy imo.

they are lookup tables used as direct indexers,
there are guards before directly indexing the array that are not all correct,
and none of the XXX_group_name handles the CS_GRP_PRIVILEGE.

Best would be to either stop using them as array, but instead use them as lookup tables (eliminating the need for the guard and manual offsetting),
or convert them into switch cases.

Also, the name CS_GRP_JUMP_INDIRECT would make more sense.

**Comment by aquynh** [comment]
you are right on the lookup table. please feel free to send a PR, i will merge.

regarding the missing CS_GRP_PRIVILEGE, that needs to be fixed, too.

do you mean `CS_GRP_JUMP_INDIRECT` for relative branch? why?

**Comment by learn-more** [comment]
Because branch is already called CS_GRP_JUMP,
and this is just a subset of those.

**Comment by aquynh** [comment]
i mean why dont name it `CS_GRP_JUMP_RELATIVE` ?

**Comment by aquynh** [comment]
all the `XXX_group_name()` functions have been simplified by using lookup table as your suggestion: https://github.com/aquynh/capstone/commit/1182d2575952de60877a35eeb2f2ff8ec57b445e

i dont backport this to the "master" branch as we will not add any new groups to this stable branch.

in the same commit, i also added the missing group PRIVILEGE, as pointed out by you.

now feel free to fix your `suite/test_group_name.py` and send a PR, thanks!

**Comment by aquynh** [comment]
do you still plan to add that group for relative branch instructions?

**Comment by learn-more** [comment]
i do.

**Comment by aquynh** [comment]
do you have any progress on this new group?

**Comment by learn-more** [comment]
It seems that insns[i].indirect_branch is either not set correctly, or it means something different than the jump being relative?

**Comment by aquynh** [comment]
On Sun, Aug 2, 2015 at 9:39 PM, learn_more <notifications@github.com> wrote:

> It seems that insns[i].indirect_branch is either not set correctly, or it
> means something different than the jump being relative?
>

indirect branch does not mean relative branch.
for example, `JMP EAX` is indirect branch.

**Comment by learn-more** [comment]
So to write this properly, there will be different code for each arch?

For example, for x86 there is this check:

    uint64_t Bits = (Bits2 << 32) | Bits1;
    uint64_t Bits1 = OpInfo[opcode];
    switch ((Bits >> 14) & 63) {
    case 9:
    // rel
    break;
    }

Or would there be a possibility to somehow retrieve this info another way?
Basically, I was hoping to do some instruction analysis, but it seems that capstone hides the relative part of an instruction, only giving access to the 'fixed up' address as X86_OP_IMM.

**Comment by hlide** [comment]
*indirect branch* has nothing to with relative branch: it means the target instruction address is fetched from a register or from a memory slot and as an absolute address most of time (at least it is always segment relative for x86[-64], so absolute address in flat mode).

*direct branch* suggest that the target instruction address is part of the immediate value of the branch instruction, it doesn't necessarily means it is relative to *PC/IP*. For instance, **MIPS** *Bxx* instructions are indeed relative to *PC* but not **MIPS** *Jxx* instructions which are relative to a segment (so you could say the immediate value is almost an absolute address).

**Comment by learn-more** [comment]
Yeah, i understand the difference now :)

I was interested in relative branch, but since i already wrote the code for indirect branch, shall i put that in a pull request?

**Comment by hlide** [comment]
relative address can be retrieved by math: for instance for X86 we have `opd[x].imm - insn.address - insn.size`. But I guess you're speaking about knowing if this jump has a target relative/absolute address because the same instruction ID (JMP) may have different opcodes and there is no such direct information except for analysing the opcode, right ?

**Comment by hlide** [comment]
And avoid saying *indirect branch*: because all x86 *indirect branch* instructions are certainly segment-relative (and so absolute address) and all x86 *direct branch* instructions are certainly ip-relative (and so relative address), it is not the case for the other architectures: **MIPS** *Bxx* (PC relative address) and **MIPS** *Jxx* (segment-relative) are all *direct branch* instructions!

**Comment by learn-more** [comment]
I know how to calculate it, but i would like some indication in the insn that it is infact needed.

**Comment by ParkHanbum** [comment]
is this issue closed?

**Comment by aquynh** [comment]
no, do you want to contribute with a pull request?
