### ISSUE TITLE
JZ != JE

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#342]
Follow up on https://github.com/radare/radare2/issues/2462

**Comment by aquynh** [comment]
So you mean some people want to have JZ as default mnemonic, rather than JE? I dont get it: you can do that now with a single call to cs_option(), so what is the problem?

Of course we can make a change in Capstone for JZ to be the default mnemonic, but then what if others ask to change it back to JE just because they like it better? This would never stop because it is just personal favourite, right?

**Comment by radare** [comment]
Jz is only for short 16bit jumps, for 32 and 64 its Je. Acording to intel documentation. So its not a personal choice

**Comment by aquynh** [comment]
Now this is interesting! What is your proposal now? Add some callback to
cs_opt_mnem? Then go ahead and send me a PR, thanks.

**Comment by radare** [comment]
my proposal is to remove cs_opt_mnem because the example in the website is wrong and i cant imagine other examples that can make it correct or useful at all. capstone should disassemble 16bit short jumps, so both JZ and JE are both valid, but depends on the context. this is why old school people likes JZ instead of JE, but the reason of the difference is not an aesthethic trend, but a technical thing that it’s documented by Intel.

**Comment by aquynh** [comment]
On Wed, Apr 29, 2015 at 10:31 PM, radare <notifications@github.com> wrote:

> my proposal is to remove cs_opt_mnem because the example in the website is
> wrong and i cant imagine other examples that can make it correct or useful
> at all. capstone should disassemble 16bit short jumps, so both JZ and JE
> are both valid, but depends on the context. this is why old school people
> likes JZ instead of JE, but the reason of the difference is not an
> aesthethic trend, but a technical thing that it’s documented by Intel.
>

interesting. lets see if others are joining this discussion before we think
about removing this option.

**Comment by jpenalbae** [comment]
As have been already said on radare/radare2#2462 JE/JZ  and JNE/JNZ have different opcodes besides they do the same.

```
| Opcode  | Instruction| Op/En| 64-Bit Mode| Compat/Leg Mode| Description    
| 74 cb   | JE rel8    | D    | Valid      | Valid          | Jump short if equal (ZF=1).    
| 0F 84 cw| JE rel16   | D    | N.S.       | Valid          | Jump near if equal (ZF=1). Not supported    
| 0F 84 cd| JE rel32   | D    | Valid      | Valid          | Jump near if equal (ZF=1).                  
| 74 cb   | JZ rel8    | D    | Valid      | Valid          | Jump short if zero (ZF ← 1).    
| 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported    
| 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1).                  
| 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported    
| 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1). JZ FARLABEL;
| 75 cb   | JNE rel8   | D    | Valid      | Valid          | Jump short if not equal (ZF=0).        
| 0F 85 cw| JNE rel16  | D    | N.S.       | Valid          | Jump near if not equal (ZF=0). Not supported
| 0F 85 cd| JNE rel32  | D    | Valid      | Valid          | Jump near if not equal (ZF=0).                  
| 75 cb   | JNZ rel8   | D    | Valid      | Valid          | Jump short if not zero (ZF=0).                  
| 0F 85 cw| JNZ rel16  | D    | N.S.       | Valid          | Jump near if not zero (ZF=0). Not supported 
| 0F 85 cd| JNZ rel32  | D    | Valid      | Valid          | Jump near if not zero (ZF=0).   
```

So I would stick to the documentation and display the proper mnemonic for each opcode.

**Comment by aquynh** [comment]
On Wed, Apr 29, 2015 at 11:29 PM, Jaime Peñalba <notifications@github.com>
wrote:

> As have been already said on radare/radare2#2462
> <https://github.com/radare/radare2/issues/2462> JE/JZ and JNE/JNZ have
> different opcodes besides they do the same.
>
> | Opcode  | Instruction| Op/En| 64-Bit Mode| Compat/Leg Mode| Description
> | 74 cb   | JE rel8    | D    | Valid      | Valid          | Jump short if equal (ZF=1).
> | 0F 84 cw| JE rel16   | D    | N.S.       | Valid          | Jump near if equal (ZF=1). Not supported
> | 0F 84 cd| JE rel32   | D    | Valid      | Valid          | Jump near if equal (ZF=1).
> | 74 cb   | JZ rel8    | D    | Valid      | Valid          | Jump short if zero (ZF ← 1).
> | 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported
> | 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1).
> | 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported
> | 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1). JZ FARLABEL;
> | 75 cb   | JNE rel8   | D    | Valid      | Valid          | Jump short if not equal (ZF=0).
> | 0F 85 cw| JNE rel16  | D    | N.S.       | Valid          | Jump near if not equal (ZF=0). Not supported
> | 0F 85 cd| JNE rel32  | D    | Valid      | Valid          | Jump near if not equal (ZF=0).
> | 75 cb   | JNZ rel8   | D    | Valid      | Valid          | Jump short if not zero (ZF=0).
> | 0F 85 cw| JNZ rel16  | D    | N.S.       | Valid          | Jump near if not zero (ZF=0). Not supported
> | 0F 85 cd| JNZ rel32  | D    | Valid      | Valid          | Jump near if not zero (ZF=0).
>
> So I would stick to the documentation and display the proper mnemonic for
> each opcode.
>

a quick question: regarding this issue, does Capstone do anything wrong at
the moment?


thanks.

**Comment by radare** [comment]
yes, it disassembles all JZ/JNZ instructions as JE/JNE

**Comment by aquynh** [comment]
On Wed, Apr 29, 2015 at 11:36 PM, radare <notifications@github.com> wrote:

> yes, it disassembles all JZ/JNZ instructions as JE/JNE
>

can you provide the sample hexcode of all the buggy instructions, so i can
test & fix them?

**Comment by jpenalbae** [comment]
Sorry, looks like I was on a mistake.

Both mnemonics use the same opcode, so `cs_opt_mnem` makes sense.

rel8
```
| 74 cb   | JE rel8    | D    | Valid      | Valid          | Jump short if equal (ZF=1).                 
| 74 cb   | JZ rel8    | D    | Valid      | Valid          | Jump short if zero (ZF ← 1).                
| 75 cb   | JNE rel8   | D    | Valid      | Valid          | Jump short if not equal (ZF=0).             
| 75 cb   | JNZ rel8   | D    | Valid      | Valid          | Jump short if not zero (ZF=0).          
```

rel16
```
| 0F 84 cw| JE rel16   | D    | N.S.       | Valid          | Jump near if equal (ZF=1). Not supported    
| 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported        
| 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported        
| 0F 85 cw| JNE rel16  | D    | N.S.       | Valid          | Jump near if not equal (ZF=0). Not supported
| 0F 85 cw| JNZ rel16  | D    | N.S.       | Valid          | Jump near if not zero (ZF=0). Not supported 
```

rel32
```
| 0F 84 cd| JE rel32   | D    | Valid      | Valid          | Jump near if equal (ZF=1).                  
| 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1).                      
| 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1).                      
| 0F 85 cd| JNE rel32  | D    | Valid      | Valid          | Jump near if not equal (ZF=0).              
| 0F 85 cd| JNZ rel32  | D    | Valid      | Valid          | Jump near if not zero (ZF=0).      
```

**Comment by mrexodia** [comment]
As far as I know the opcodes of JE and JZ are the same, so this means there is no difference between JE and JZ **when you disassemble the instruction**. There are also various other examples of conditional branches that have different mnemonics:

```
enum BRANCH_TYPE
{
    //JO vs JNO
    JO = 1,
    JNO = -1,
    //JC=JB=JNAE vs JNC=JNB=JAE
    JC = 2,
    JB = 2,
    JNAE = 2,
    JNC = -2,
    JNB = -2,
    JAE = -2,
    //JE=JZ vs JNE=JNZ
    JE = 3,
    JZ = 3,
    JNE = -3,
    JNZ = -3,
    //JA=JNBE vs JNA=JBE
    JA = 4,
    JNBE = 4,
    JNA = -4,
    JBE = -4,
    //JP=JPE vs JNP=JPO
    JP = 6,
    JPE = 6,
    JNP = -6,
    JPO = -6,
    //JL=JNGE vs JNL=JGE
    JL = 7,
    JNGE = 7,
    JNL = -7,
    JGE = -7,
    //JG=JNLE vs JNG=JLE
    JG = 8,
    JNLE = 8,
    JNG = -8,
    JLE = -8,
};
```

There might be some random difference, but the conditions are the same so a disassembler should consider them equal.

**Comment by aquynh** [comment]
to be sure, someone should assemble all the suspected instructions (using "nasm", for example) and confirm the output opcode that they have expected values.

but i would be shocked if JZ is not JE in some contexts. Intel would not be that silly to design their CPU that way, right?

**Comment by radare** [comment]
It depends on what you trust:

- intel documentation
- instruction internals
- what random assemblers do
- what random disassemblers do

I would trust the first one, despite the instruction internals are the same between jz and je. Its just a formalism for the reader. You know.. Opcode != Mnemonic.

**Comment by aquynh** [comment]
you are right, it is better to cross check everything.

**Comment by mrexodia** [comment]
I don't agree. It is impossible to derive what was intended when you
disassemble. The instructions have the same opcode.

**Comment by radare** [comment]
Acording to the documentation, the use of jz or je doesnt depends on user choice. But I get your point, but i dont think you want your disassembler to switch from jz to je depending on user choice or some magic analysis. Im looking for a consistent syntax across all capstone users. Thats why im refering to the intel documentation

**Comment by hlide** [comment]
To make thing clearly, you have two ways to see how a conditional jump occurs: the bitwise way (eflags bits) or the logical way (comparison result).

Bitwise way:

- jz/jnz: ZF = 1/0
- jo/jno: OF = 1/0 --> no conflict with logical way
- jp/jnp: PF = 1/0 --> no conflict with logical way
- js/jns: SF = 1/0 --> no conflict with logical way
- jc/jnc: CF = 1/0

for instance, I would expect  jz/jnz after a TEST/AND/OR/XOR and jc/jnc after a MUL/IMUL

Logical way:

- je/jne: ZF = 1/0
- jb/jnb: CF = 1/0

I would expect the logical Jcc after a CMP.

As for DEC/INC/ADD/ADC/SUB/SBB, it is very subjective as I would tend to prefer bitwise way over logical way when possible.

**Comment by hlide** [comment]
To sum up what I posted : instructions like Jcc, SETcc, CMOVcc chose bitwise way over logical way when conflicting unless the last previous instruction to set eflags is CMP.

**Comment by hlide** [comment]
As for Intel documentation stating that JZ is used for near jumps and JE for short jumps, I think it doesn't make any sense since there is no way to apply the same logic to the not conflicting conditional jumps so that is the worst "solution" they gave.

**Comment by hlide** [comment]
For logical Jcc, you could choose the "positive" condition over "negative" condition:

```
A/NBE --> A
AE/NB --> AE
B/NAE --> B
BE/NA --> BE
G/NLE --> G
GE/NL --> GE
L/NGE --> L
LE/NG --> LE
```

**Comment by aquynh** [comment]
this whole discussion is interesting!

while i think it makes sense to mix JE & JZ in the disassembly depending on
the context, is there any engine/tool doing this now? i doubt it.

besides, think about using the disassembly you get from Capstone to feed in
the assembler (to produce machine code) at the next step of your analysis
tools. i am not sure that all assemblers would be able to handle JE & JZ
at the same time. most likely only one of them, but not two (?)

**Comment by mrexodia** [comment]
All the assemblers I used supported both. But yea, it makes sense to use Jz
as default, since Intel also uses it in their tools (not je)

**Comment by hlide** [comment]
I guess most disassemblers choose only one (and as far as I remember bitwise way).
To handle Jcc, You simply need to record which instruction id was the last to set eflags (supposedly that you already provide that kind of information) in the X86 context. When encountering Jcc/SETcc/CMOVcc, just check if last instruction was a I_CMP to select logical way over the defaulted bitwise way. I guess user can do it by using the details info to do so.

**Comment by aquynh** [comment]
handling branch instructions this way turns Capstone to an analysis framework, which i dont want to. lets keep it simple & leave this job to higher level tools built on top of it.

**Comment by aquynh** [comment]
changing mnemonic "JE" to "JZ" by default may render compatibility issue. like a tool that only handles JE but not JZ, then this change will break it.

for this reason, it is not a good idea to make this move. now we have OPT_MNEMONIC option, nothing prevents you from setting the mnemonics to anything you want.

**Comment by hlide** [comment]
As long as there is a way for user to determine if an instruction is setting eflags, it can be done on user side, that's what I mean in the last sentence of my previous post.

**Comment by aquynh** [comment]
yes, now X86 engine can even tell you in details which bits in EFLAGS are modified. see http://capstone-engine.org/op_access.html, and pay attention to the screenshot at the bottom.

**Comment by hlide** [comment]
So a solution for the user may be the following: in the case of choosing bitwise version by default and logical version especially after a I_CMP, we can call cs_option with OPT_MNEMONIC to set Jcc, SETcc and CMOVcc dynamically inside an iteration through cs_disasm_iter or in a second pass iterating through the result of cs_disasm. If an instruction is modifying ZF and it is not I_CMP, the user must use cs_option to choose JZ, SETZ and CMOVZ. If it is I_CMP, the user must use cs_option to choose JE, SETE and CMOVE. Of course, the user can track those changes to avoid to call cs_option more than necessary. The same thing can happen for CF. Does it sound valid as a solution?

**Comment by mrexodia** [comment]
@hlide I believe everything was solved already. You can customize the mnemonic :+1:

**Comment by hlide** [comment]
@mrexodia please reread my last post and you will understand that I'm **not** suggesting to change anything in the code **since** the **user** (of capstone library) can use the **current** mnemonic customization dynamically to handle JZ vs. JE according to a context.

**Comment by XVilka** [comment]
So what was decided on this one? @radare @aquynh

**Comment by radare** [comment]
i think we can live with the way it works now already, it was just a complain from my young me when i was doing reversing in DOS, where JE/JNE was used instead of JZ/JZE

**Comment by radare** [comment]
we can close it, or add another option to have this magiic inside capstone, but r2 can do this already from RParse
