### ISSUE TITLE
Wrong disassembly of 16-bit relative call

### ISSUE THREAD

**Issue by Nodepad** [capstone-engine/capstone#352]
Capstone disassembles relative 16-bit calls incorrectly.
https://github.com/radare/radare2/issues/2482

**Comment by Nodepad** [comment]
1. I guess issue is in loading immediate operand, it's loaded like unsigned instead of signed. I think function `MCOperand_getImm ` returns unsigned value: 0xfffd instead of -3 for example above.
https://github.com/aquynh/capstone/blob/next/arch/X86/X86IntelInstPrinter.c#L627
```
int64_t imm = MCOperand_getImm(Op) + MI->flat_insn->size + MI->address;
```
2 .  About issue https://github.com/aquynh/capstone/issues/111
Why do you think that relative offsets should overlap in 16-bit mode? For example you can address same code with `f000:ffaa` or `fff0:00aa`. In second case there won't be overlapping. I think this issue isn't an issue and it shouldn't be fixed

**Comment by aquynh** [comment]
@Nodepad, can you check the new branch *x86pcrel* at https://github.com/aquynh/capstone/tree/x86pcrel to see if your problem is fixed?

@radare, can you also check if the branch *x86pcrel* fixes that old issue https://github.com/aquynh/capstone/issues/111 ?

**Comment by Nodepad** [comment]
Fixed my issue. Thank you.

**Comment by radare** [comment]
Will update capstone head commit in r2 repo soon. So we can run the testsuite and ensure no othwr breaks are in there.

Thanks!

**Comment by aquynh** [comment]
ok, let me know. if this fixes that issue https://github.com/aquynh/capstone/issues/111, i will merge it into "next" branch. thanks.

**Comment by radare** [comment]
Looks good to me, you can merge back into next. Thanks

**Comment by aquynh** [comment]
merged that into "next", thanks.

**Comment by radare** [comment]
Reopen this issue as long as it breaks several tests in our testsuite failing other x86-16 disassembled instructions. See https://travis-ci.org/radare/radare2/jobs/61135594

**Comment by aquynh** [comment]
cannot read that crap. can you post here all the input (in hexcode), current output & expected output?

**Comment by aquynh** [comment]
can you guys try again the new branch `pcrel16` to see if this fixes all the issues?

the related commit is https://github.com/aquynh/capstone/commit/a7b2cc29787175fa55a9aea51585fa09fbd771c2

(make sure to do `./make.sh` for fresh-recompile)

**Comment by radare** [comment]
Waiting for travis to confirm https://github.com/radare/radare2/pull/2498

**Comment by aquynh** [comment]
@Nodepad, can you join this discussion at https://github.com/aquynh/capstone/issues/111 ?

**Comment by radare** [comment]
Can you reopen this issue as long as its not fixed? the travis reports failure too

**Comment by aquynh** [comment]
yes, it is open again now.

this is exactly the same issue with https://github.com/aquynh/capstone/issues/111. you got the right result due to pure luck, because your code segment is 0.

**Comment by aquynh** [comment]
i mean @Nodepad got the right result, not you.

**Comment by radare** [comment]
😭

**Comment by aquynh** [comment]
of course i can fix the code to make your tests pass again, but your tests on 16bit relative jumps are actually right due to pure luck, and the problem is still there.

**Comment by radare** [comment]
any update on this? i would like to be able to use capstone releases without having to revert stuff

**Comment by aquynh** [comment]
you still havent answered the questions on https://github.com/aquynh/capstone/issues/111: how do you want to solve the problem?

so go to https://github.com/aquynh/capstone/issues/111 and input your ideas.

**Comment by radare** [comment]
i did

**Comment by XVilka** [comment]
What we decided with this one?
