### ISSUE TITLE
movsw is decoded as movsd in next branch - need to get it fixed urgently

### ISSUE THREAD

**Issue by bipulr** [capstone-engine/capstone#356]
"rep movsw" byte code is 0x66 0xf3 0xa5 which is decoded as "rep movsd" in next branch, output below. capstone-3.0.2 package decodes it correctly.

Platform: X86 64 (Intel syntax)
Code:0x66 0xf3 0xa5 
Disasm:
0x1000: rep movsd   dword ptr [rdi], dword ptr [rsi]

```
Prefix:0xf3 0x00 0x66 0x00 
Opcode:0xa5 0x00 0x00 0x00 
rex: 0x0
addr_size: 8
modrm: 0x0
disp: 0x0
sib: 0x0
op_count: 2
    operands[0].type: MEM
        operands[0].mem.base: REG = rdi
    operands[0].size: 4
    operands[0].access: WRITE
    operands[1].type: MEM
        operands[1].mem.base: REG = rsi
    operands[1].size: 4
    operands[1].access: READ
Registers read: rdi rsi rflags rcx
Registers modified: rdi rsi rcx
EFLAGS: TEST_DF
```

0x1003:

**Comment by bipulr** [comment]
same issue for "rep scasw" which is decoded as "rep scasd"

**Comment by aquynh** [comment]
this is a known problem that i am still looking for the right solution.

fyi, while Capstone does not handle `0x66 0xf3 0xa5` properly yet, `0xf3
0x66 0xa5` is OK.

**Comment by mrexodia** [comment]
Has there been any progress with this?

**Comment by aquynh** [comment]
will solve this when i have more time this coming holidays
