### ISSUE TITLE
jz vs je

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#36]
capstone disassembles 74/75 opcode as 'je/jne' while other disassemblers use 'jz/jnz'. In fact, both mnemonics are assembled as the same instruction, so that's just an aesthetical issue.

I personally prefer the 'jz/jnz' form, should we change this? What's your preference?

**Comment by learn-more** [comment]
How would this be implemented?
An option per instruction, or one option to toggle all instructions to alternate names?
And how to handle the case of one instruction with 3 alternate names?

**Comment by aquynh** [comment]
this can be done via **cs_option** API.

the idea is to define a new option (like *CS_OPT_INSN_NAME*), then let user pass the *instruction ID* & *instruction name* to it. then at run time, the printer will use this name for the corresponding instruction.

the implementation should not be too complicated.

**Comment by mrexodia** [comment]
Keep in mind that there should be like 10 options then, jz vs je is not the
only thing.

**Comment by aquynh** [comment]
surely yes, but then we run *cs_option()* 10 times, one for each of these instructions.

**Comment by mrexodia** [comment]
True, or maybe use a bit field?

**Comment by aquynh** [comment]
Why? This is at the setup stage, so i dont see any issue calling this API even hundreds times. That does not affect performance or anything, so lets keep it simple.

**Comment by mrexodia** [comment]
Okay :)

**Comment by learn-more** [comment]
yeah, my idea was to pass a struct that has the id & name the user wants for it then.
capstone will alloc it's own private copy of the struct, not sure where to store it yet, but ill find a nice place.

**Comment by aquynh** [comment]
you can look at how the option `CS_OPT_SKIPDATA_SETUP` was implemented.

for keeping data, that should be inside the struct  `cs_struct` (see file `cs_priv.h`).

thanks.

**Comment by learn-more** [comment]
I was thinking of storing it somewhere in the internal lookup tables,
but that would mean it would have to be done for all arches separately.

In case that it's stored in the cs_struct, it would mean that when a few are selected, they would have to be iterated trough for each instruction.

**Comment by aquynh** [comment]
lets consider this case: you create 2 engines (of X86), and each engine has different setups.
so `cs_struct` is the only place to keep them independent.

**Comment by aquynh** [comment]
to replace the original mnemonic with the one you want, a good place is to do that in `fill_insn()` function in `cs.c`. this code works for all archs, so you do not need to do that separately.

**Comment by aquynh** [comment]
so i implemented a new option **CS_OPT_MNEMONIC** to customize instruction mnemonic at run-time. this should support all 8 architectures Capstone has at the moment.

this code is now available in the `mnem` branch at https://github.com/aquynh/capstone/tree/mnem.

you can find how to use this option in the new test code **test_customized_mnem.c** at https://github.com/aquynh/capstone/blob/mnem/tests/test_customized_mnem.c.

below is the output of `test_customized_mnem`, which is intuitive & self explanatory.

```
Disassemble X86 code with default instruction mnemonic
75 01 		jne	0x1003

Now customize engine to change mnemonic from 'JNE' to 'JNZ'
75 01 		jnz	0x1003

Reset engine to use the default mnemonic
75 01 		jne	0x1003
```

of course you should be able to run `cs_option(CS_OPT_MNEMONIC)` as many times as you want - so there is no limit on how many instructions you can customize.

let me know if you guys have any comment, thanks.

**Comment by mrexodia** [comment]
awesome solution! I think you can mark this issue as resolved :+1:

**Comment by aquynh** [comment]
thanks. lets see if there are more comments before this is merged into the "next".

@mrexodia btw, can you answer my question on the issue https://github.com/aquynh/capstone/issues/335? how did you create ".a" file for MingW?

**Comment by radare** [comment]
Awesome! Will test it asap. I was also missing the jz namings..

**Comment by aquynh** [comment]
i merged this "mnem" branch into the "next" branch.

Python binding support for new option *CS_OPT_MNEMONIC* is now ready: see sample code https://github.com/aquynh/capstone/blob/next/bindings/python/test_customized_mnem.py.

the "mnem" branch will be deleted.

**Comment by aquynh** [comment]
some docs for this new option: http://capstone-engine.org/mnemonic.html

**Comment by aquynh** [comment]
can you guys please join this related discussion: https://github.com/aquynh/capstone/issues/342 ?

thanks.
