### ISSUE TITLE
ARM Disassembler broken for ldrdge

### ISSUE THREAD

**Issue by zachriggle** [capstone-engine/capstone#363]
Looks like the ARM disassembler is broken for some instructions, on the `next` branch.  It won't disassemble `DFF868A0` in either endian-mode.

```
>>> from capstone import *
>>> md = Cs(CS_ARCH_ARM, CS_MODE_ARM)
>>> md.detail = True
>>> for i in md.disasm(b'\x00\x00\x00\x00\xdf\xf8\x68\xa0', 0): print(i.mnemonic, i.op_str)
(u'andeq', u'r0, r0, r0')
>>> for i in md.disasm(b'\x00\x00\x00\x00\xa0\x68\xf8\xdf', 0): print(i.mnemonic, i.op_str)
(u'andeq', u'r0, r0, r0')
(u'svcle', u'#0xf868a0')

>>> md = Cs(CS_ARCH_ARM, CS_MODE_ARM + CS_MODE_BIG_ENDIAN)
>>> md.detail = True
>>> for i in md.disasm(b'\x00\x00\x00\x00\xdf\xf8\x68\xa0', 0): print(i.mnemonic, i.op_str)
(u'andeq', u'r0, r0, r0')
(u'svcle', u'#0xf868a0')
>>> for i in md.disasm(b'\x00\x00\x00\x00\xa0\x68\xf8\xdf', 0): print(i.mnemonic, i.op_str)
(u'andeq', u'r0, r0, r0')
```

However, it should disassemble just fine.

```
$ disasm -c arm -c little 00000000dff868a0
   0:   00000000        andeq   r0, r0, r0
   4:   a068f8df        ldrdge  pc, [r8], #-143 ; 0xffffff71    ; <UNPREDICTABLE>
$ disasm -c arm -c big 00000000dff868a0
   0:   00000000        andeq   r0, r0, r0
   4:   dff868a0        svcle   0x00f868a0
```

**Comment by zachriggle** [comment]
Note that I updated the original comment because of a copy-paste error.

**Comment by zachriggle** [comment]
FWIW, in 3.0.3 I get the same thing.

**Comment by zachriggle** [comment]
Looks like GDB disagrees a bit.  

(gdb) x/i $pc
=> 0xf67c7a00:	ldr.w	r10, [pc, #104]	; 0xf67c7a6c
(gdb) x/wx $pc
0xf67c7a00:	0xa068f8df

**Comment by aquynh** [comment]
which disassembler are you using to verify this?

**Comment by zachriggle** [comment]
objdump.  the command-line wrapper is pwntools, but all it does is wrap binutils.

**Comment by zachriggle** [comment]
Also, FWIW this is a side-effect of GDB sucking about not actually giving me `$pc`.  This is supposed to be two Thumb instructions, but GDB does its own thing so I was decoding them as ARM instead.  I've since fixed the issue, but the discrepancy in decoding still exists.

**Comment by aquynh** [comment]
need to look closer in the ARM manual, but it seems GDB is wrong here (again) on this code, because it should be invalid code to me (so Capstone/LLVM is right).

can you try to see how other disassemblers (IDA, etc) say about this code??
