### ISSUE TITLE
No CS_ constant to check registers against common values

### ISSUE THREAD

**Issue by zachriggle** [capstone-engine/capstone#367]
In some analyses, it is useful to be able to determine whether a given operand is register with a predictable value.  For example, all architectures have a register which corresponds to the program counter, but there is no unified constant to check for this.  Also, there is no unified constant for the zero register (MIPS and PPC).

Second, there are registers which exist on all architectures, but are not predictable, but would still be useful to have a unified way to test against them.  The only candidate here is the stack pointer register.

These are not difficult to work around, but require looking up the current architecture which is ~= annoying.

Could we unify the register constants such that `CS_REG_PC`, `CS_REG_SP` and `CS_REG_ZERO` are possible?

**Comment by zachriggle** [comment]
One complication that this causes is how to disambiguate X86_REG_EIP and X86_REG_RIP.  Both could be considered `CS_REG_PC` under different circumstances.

**Comment by zachriggle** [comment]
Perhaps a better way to solve it is to use a bitmask for the ones which require disambiguation?

This could be extended to the general case for registers of multiple widths, in order to known that e.g. `X86_REG_AX` and `X86_REG_EAX` are both the same register.  This can currently be done on a per-architecture basis, but not in a general manner.

This in itself causes complications for architectures with more than 32 (or 64) registers, as you run out of bits to AND with.

**Comment by aquynh** [comment]
sounds interesting. can you propose in details your bitmask solution?

**Comment by aquynh** [comment]
we used to do this for groups & operand types (see https://github.com/aquynh/capstone/issues/195), so we can surely do the same thing for registers etc, as long as the solution is clean enough and works on all archs.

**Comment by zachriggle** [comment]
How about the following mapping?

Register Class: 8 bits
Since there is no overlap (i.e., a register can only be one of stack pointer, program counter, zero register).  This mapping is shared across all architectures.

Native Register: 8 bits
This allows breaking out the "native-size" register for each register value.  The intent is not to identify registers individually, but to say that they all belong to the same hardware register.  For example, rax, eax, ax, ah, al would all have the same value in this field.   This mapping is per-architecture.

Register ID: 16 bits (allows 65k registers).  This allows breaking out the individual registers and register sub-divisions as we currently have.  It looks like x86 uses the most, at ~600 distinct registers.  This can be the current register value, no change is necessary.

The "register class" and "native register" fields allow 256 distinct values which should be more than sufficient.  However, as there are more values we want to represent than bits, the mask will have to be checked for equality (`foo & bar == bar` vs `foo & bar != 0`).

**Comment by aquynh** [comment]
so you want to add a new API (a function) that given a register ID at the input, it returns the class+native value at output?

**Comment by zachriggle** [comment]
Sure, I figure something like `CS_REG_CLASS(ins)` ==> `CS_REG_CLASS_STACK`

**Comment by aquynh** [comment]
On May 19, 2015 5:07 AM, "Zach Riggle" <notifications@github.com> wrote:
>
> Sure, I figure something like CS_REG_CLASS(ins) ==> CS_REG_CLASS_STACK

Lets clarify that we need a new function, but not a macro, because changing
the register id will affect a lot of things on how the registers are
handled internally. So all we need to do is to creat mapping tables that
map current register ids to its class etc, and a new func API will simply
return the mapping value.

Feel free to send in a pull request. Thanks.

**Comment by zachriggle** [comment]
SGTM

**Comment by zachriggle** [comment]
This is not as easy without changing the register ID, since the function would need to know which architecture the instruction comes from.  A bitmask is a bit easier to handle, and doesn't require introspection of where the instruction came from.

**Comment by aquynh** [comment]
the function API can get the handle (csh) as one parameter, and everything will be fine.

actually it is possible to do what you are asking: we can just map the current register ID to the new ID in the mapping tables, so that the new ID encodes all the info, and return the new ID back as register ID. this requires a bit more work and touch more places though. but this seems more clean, yes.
