### ISSUE TITLE
Incorrect ARM Condition Codes for CBNZ

### ISSUE THREAD

**Issue by zachriggle** [capstone-engine/capstone#368]
```
>>> (i.bytes, i.mnemonic, i.op_str, i.cc)
(bytearray(b'c\xb9'), 'cbnz', 'r3, #0xf67ca920', 15)
>>> ARM_CC_AL
15
```

**Comment by aquynh** [comment]
currently we consider `CBZ` & `CBNZ` (thumb mode) are two instructions, but not instructions with code conditions.

**Comment by zachriggle** [comment]
I can see that side, since the *comparison* happens unconditionally, but the jump has a condition -- as do many of the conditional moves.  Do any of the other conditional non-jump instructions have the CC set?

**Comment by aquynh** [comment]
yes, you can grep for "Code condition:" at the output of `tests/test_arm` for that.

currently we do not have `Z` or `NZ` condition, but only `EQ` & `NE`. not sure if we should apply this for these instructions `CBZ`/`CBNZ`, but this issue raises a good question.

**Comment by zachriggle** [comment]
I've always understood `Z/EQ` and `NZ/NE` to be the same, but that may just be my Intel-centric view of the world :P
