### ISSUE TITLE
call / jump x86 for 32-bits and 64-bits mode.

### ISSUE THREAD

**Issue by Worobow** [capstone-engine/capstone#371]
For x86 in 32-bit mode, disassembler processing instructions such call/jmp <disp> without resulting options that the register  IP (RIP) is used as base, but a 64-bit mode, this indicated. It seems that be applied uniformly across to all platforms but not.

**Comment by aquynh** [comment]
On Wed, May 20, 2015 at 9:54 PM, Worobow <notifications@github.com> wrote:

> For x86 in 32-bit mode, disassembler processing instructions such call/jmp
> without resulting options that the register IP (RIP) is used as base, but a
> 64-bit mode, this indicated. It seems that be applied uniformly across to
> all platforms but not.
>

sorry that i dont understand what you are talking about. can you give some
examples: input (hexcode), output, and the expected output?


thanks.

**Comment by Worobow** [comment]
.text:00401207 E8 6B 06 00 00         call    _RTC_Initialize
.text:0040120C E8 7D 03 00 00        < some next instrs>
...
.text:00401877                                  _RTC_Initialize

call instr at .text:00401207 use RIP as base 0040120C + 66B =>1877 :)

**Comment by aquynh** [comment]
On Wed, May 20, 2015 at 10:24 PM, Worobow <notifications@github.com> wrote:

> .text:00401207 E8 6B 06 00 00 call _RTC_Initialize
> .text:0040120C E8 7D 03 00 00 < some next instrs>
> ...
> .text:00401877 _RTC_Initialize
>
> call instr at .text:00401207 use RIP as base 0040120C + 66B =>1877 :)
>

so what is wrong?

**Comment by hlide** [comment]
I think he means JUMP and CALL in 32-bit mode should be handled the same way as 64-bit by telling if EIP is read/written as it is done for RIP in 64-bit.

**Comment by radare** [comment]
I have read it twice and i still dont understand this issue either

**Comment by radare** [comment]
At esil level? Esil already specifies that and the current form is correct. So i still dont see the problem

**Comment by hlide** [comment]
he's talking about consistency and coherency in the way to handle PC. Instruction dealing with PC (that is, changing PC or explicitely reading PC should "indicate" the case in detail mode. Apparently, 32-bit mode version of x86 is not "indicating" that EIP is read and written when **CALL**ing.

**Comment by aquynh** [comment]
on the "next" branch, with **x86** we have this:

    0x401207:	call	0x401877
	Registers read: esp eip
	Registers modified: esp

with **x86_64**, on the same input, we have:

    0x401207:	call	0x401877
	Registers read: rsp rip
	Registers modified: rsp

so what is inconsistent here?

**Comment by hlide** [comment]
well maybe he isn't using *next* or whatever, I was just trying to "interpret" what he means.

**Comment by Worobow** [comment]
I'm sorry for the delay guys, I mean, it would be nice that, "IMM" operand had the same set of attributes as "MEM". But now I understand how you process "instructions". You analyze what it reads and writes. I will use this approach, too. Thank you. Beer. ))

**Comment by Worobow** [comment]
0x400014A8:     call    0x40001710 ( 0xe8, 0x63,0x02,0x00,0x00 ) reg read count=1, reg read=[rsp], reg write count=0
0x40001716:     mov     rbp, rsp ( 0x48, 0x8b,0xec ) reg read count=0, reg write count=0 

IMHO this's seem a little bit strange. 
WAIDW?
the "call" do modify rip and rsp.

**Comment by aquynh** [comment]
regs_read[] & regs_write[] actually indicate registers **implicitly** read & written.

if you want to access all the registers **implicitly** & **explicitly** read/writen, see this: http://capstone-engine.org/op_access.html (be sure to use the "next" branch for this new feature)

**Comment by aquynh** [comment]
CALL modifies RSP because it pushes the return address into the stack. also, it is relative CALL in this case, thus it reads RIP. see https://github.com/aquynh/capstone/issues/358.

**Comment by Worobow** [comment]
I'll ask here. Does exist a built-in way to get a pointer to operands inside the instruction? Or is it necessary calculate manually? (skip prefix, opcode, modrm etc.)?

**Comment by aquynh** [comment]
please open a new issue for unrelated questions, because it will also confuse you eventually.

i dont really understand what you are asking. anyway, it is a good idea to go through all the sample code in see tests/test*.c: all the API is well presented in these samples.
