### ISSUE TITLE
Wrong arm64 instruction disassembly

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#372]
According to http://www.element14.com/community/servlet/JiveServlet/previewBody/41836-102-1-229511/ARM.Reference_Manual.pdf the LDP instruction is composed like STP, but for loading instead of storing a pair of registers. The construction is: `LDP R1, R2, [REG+DISP]`, currently capstone disassembles it like this:

```
fd7bbfa9       stp x29, x30, [sp, -0x10]!  //// STP
fd030091       mov x29, sp
400000b4       cbz x0, 0x401034  
00003fd6       blr x0
fd7bc1a8       ldp x29, x30, [sp], 0x10    //// LDP
c0035fd6       ret

```

**Comment by aquynh** [comment]
what is the output of others (GNU, IDA)?
