### ISSUE TITLE
Please check instr decode.

### ISSUE THREAD

**Issue by Worobow** [capstone-engine/capstone#390]
.text:0000000140001219 66 39 05 E0 ED FF FF     cmp     cs:140000000h, ax
.text:0000000140001220 74 04 

instruction displacenemt size is 4 but in ...
capstone-next\arch\X86\X86DisassemblerDecoder.c
line:807 
                            insn->displacementSize   = (hasOpSize ? 2 : 4);
displacementSize setup 2.

**Comment by aquynh** [comment]
does this affect anything else in the structure `cs_insn` at the output? if not, we can ignore this issue?

**Comment by Worobow** [comment]
Yeah. All clear. Sorry. I was naive to think that you fix this.

**Comment by aquynh** [comment]
i will look into this later, but apparently this does not cause any issue to the output, so it is not a priority.

thanks.
