### ISSUE TITLE
Disassembly of imul

### ISSUE THREAD

**Issue by yegord** [capstone-engine/capstone#392]
Hi,

the instruction `18009e8fe:   67 65 4c 69 73 74 3a    imul   r14,QWORD PTR gs:[ebx+0x74],0x2058253a` is disassembled by capstone (master) as `imul r14, dword ptr gs:[ebx + 0x74], 0x2058253a`. The size of the second operand reported by capstone is four bytes, although it should be eight: x86 does not have `imul` with 64-bit target register and 32-bit memory argument.

Could you fix this?

**Comment by yegord** [comment]
By the way, the size of the last (immediate) operand is reported to be 8, although it should be 4.
Actually, 8 would be also fine, but then you have to sign-extend it.

**Comment by aquynh** [comment]
the input code `67 65 4c 69 73 74 3a` does not seem to correct, because i cannot disassemble it. neither other disassemblers, so can you double check this?

**Comment by yegord** [comment]
My bad. The code is '67 65 4c 69 73 74 3a 25 58 20'. I did not notice that objdump -d used two lines for this instruction.

**Comment by aquynh** [comment]
with "master" branch, i dont get the output imul `r14, dword ptr gs:[ebx + 0x74], 0x2058253a` like in your report, but  `imul	r14, qword ptr gs:[ebx + 0x74], 0x2058253a`, and the size of the second operand is 8 bytes, like below. can you double check this?

0x1000:	imul	r14, qword ptr gs:[ebx + 0x74], 0x2058253a
	op_count: 3
		operands[0].type: REG = r14
		operands[0].size: 8
		operands[1].type: MEM
			operands[1].mem.segment: REG = gs
			operands[1].mem.base: REG = ebx
			operands[1].mem.disp: 0x74
		operands[1].size: 8
		operands[2].type: IMM = 0x2058253a
		operands[2].size: 8

on the size of immediate operand, this is a known issue (see https://github.com/aquynh/capstone/issues/296), and we will not have a fix very soon.

**Comment by yegord** [comment]
Thank you for your answer. I have upgraded to capstone facb90c46675574c7d32b33b7f7d66bf9bb545ec, indeed, the memory operand has the size of eight bytes now.

However, Capstone now disassembles `1800027c0:   40 e9 0b 00 50 e9       rex jmpq 0x1695027d1` as `jmp 0x1695027d1` with the immediate operand size being 4 bytes. This is very strange, taking into account that the number 0x1695027d1 has 9 hex digits, and, therefore, does not fit into 4 bytes.

As far as I understand, similar problems are known and are not going to be fixed, say, in the next couple of weeks?

**Comment by aquynh** [comment]
yes the immediate size is currently based on few things, such as hardware mode (32bit/64bit), and not accurate, but this takes time to fix.

i cannot promise to fix this problem thoroughly  in a couple of weeks, but i might do this case by case if you report them.

a question: the size of immediate does not really matter in most cases, so why does it affect your app?

**Comment by yegord** [comment]
It affects my app, because it tries to generate correct IR for an instruction. And when some immediate operands have unexpected sizes, incorrect IR gets generated, and/or assertions fire. In case of IMUL, the wrong operand size prevents sign-extension, therefore, the constant in IR gets a wrong value (in case the immediate was negative). In case of JMP, I simply cannot generate a 32-bit constant in IR having value 0x1695027d1 (an assertion fails).

Can you please then consider this message as a bug report for two instructions: IMUL (immediate still has size 8 instead of four — or you sign-extend it yourself?) and JMP?

**Comment by yegord** [comment]
Another related question: `401222:       83 e4 f0                and    $0xfffffff0,%esp`, according to capstone facb90c46675574c7d32b33b7f7d66bf9bb545ec, has two operands of size 4, which is true. However, the value of operand[1].imm is 0xfffffffffffffff0. Is it assumed that the immediate value is sign-extended to sizeof(operand[1].imm), and the user must truncate is manually to four bytes?

Probably, I am missing the general understanding of the meaning of .size and .imm operand fields. What do the values in them denote?

**Comment by aquynh** [comment]
on this AND instruction, it is a bug, and fixed with the latest commit https://github.com/aquynh/capstone/commit/36d05945f972fd70d43584b468e52beb8a27da8b in the "master" branch. (the "next" branch does not have this issue)

on the size of immediate operands, it tells you the size in bytes. example: `mov ah, 18` has 1 byte size for `18`, and `mov ax, 35` has 2 byte size for `35`, etc.

i will look at the IMUL & JMP instructions later.

thanks.

**Comment by yegord** [comment]
Thank you! But I still have two questions. :-)
1. Do I understand correctly, that if the size of an immediate is N bytes, then all bytes in the .imm field, except for the N least significant bytes, must be zero, and if they are not, this is a bug?
2. Do I understand correctly, that the size of an immediate is the size of the immediate, as it is in the encoding of an instruction? In other words, if you have `CMP r/m32, imm8`, then the size of the immediate is going to be one byte, not four?

**Comment by hlide** [comment]
1. I would expect the result in .imm field be signed or unsigned according to the instruction rule (is the immediate operand signed or unsigned for this instruction?), though a cast operation doing 8/16/32-bit sign-extension or zero-extension operation according to the size of the immediate operand. If not, it means you must do it yourself.
2. You should understand correctly, otherwise that size of immediate would not make a sense.

**Comment by aquynh** [comment]
@yegord, on your number (1), i think you still have to consider the sign of the immediate. 

you are correct on the number (2): this is what i mean for the size of immediate operands (which is still incorrect in some cases now)

**Comment by yegord** [comment]
@aquynh, so, your answer to (1) means to me that you sign-extend the immediate to 64 bits yourself. Do you always do this? Do you do this only for particular instructions? What is the rule?

libudis86 for immediates returns the size that they actually occupy in the instruction and returns the value as is: no sign-extension or other clever logic involved. I was quite happy with this behavior. :)

(I am annoying you with all these question partly because I want to make sure that there is a common understanding of what is the right output, before we (mostly, you) start fixing it.)

**Comment by aquynh** [comment]
if you are willing to help, here is the complete fix for this immediate size issue:

- find all the opcode related to immediate in `arch/X86/X86GenInstrInfo.inc`. you can find them by "grepping" for "i8", "i16", "i32", "i64".
- create a mapping table from these opcodes that map them to the immediate size. example: `X86_AAD8i8` maps to 1 (byte), `X86_OR16i16` maps to 2 (bytes), etc.
- use this mapping table to setup the immediate size `printOperand()`, in this code block https://github.com/aquynh/capstone/blob/next/arch/X86/X86IntelInstPrinter.c#L701
- do this for AT&T as well (https://github.com/aquynh/capstone/blob/next/arch/X86/X86ATTInstPrinter.c)

this is easy enough, but let me know if you need any helps.

thanks.

**Comment by aquynh** [comment]
this issue has been completely fixed with the latest commit https://github.com/aquynh/capstone/commit/de8dd26780efc2fd32fe4329ddc8f11769b4d238 in the "next" branch - for all instructions with immediate operands, but not only this case. see the new output below:

    imul	r14, qword ptr gs:[ebx + 0x74], 0x2058253a
	op_count: 3
		operands[0].type: REG = r14
		operands[0].size: 8
		operands[0].access: WRITE

		operands[1].type: MEM
			operands[1].mem.segment: REG = gs
			operands[1].mem.base: REG = ebx
			operands[1].mem.disp: 0x74
		operands[1].size: 8
		operands[1].access: READ

		operands[2].type: IMM = 0x2058253a
		operands[2].size: 4

	Registers read: gs ebx
	Registers modified: rflags r14

let me know if you still find something wrong, thanks.

**Comment by hlide** [comment]
I see. I was under impression we could have the size of *operands[1].mem.disp* as it was encoded in the opcode, but I guess it is not the purpose for this decomposer.

**Comment by aquynh** [comment]
interesting question. what should be the value of it? simply use the size of base register for it, or just 16/32/64 (bits) in case memory operand is without base/index registers?

but frankly adding `disp.size` is ugly here, and i am not sure how useful it is.

**Comment by yegord** [comment]
I assume that the size of everything in the address expression (including displacement) is `detail_->addr_size`. I do not check if the higher bits of `operand.mem.disp` are set, I just truncate the value to `detail_->addr_size`, so, if you sign-extend the value to something larger than `detail_->addr_size`, it is fine. I also believe that `disp.size` is superficial.

Thanks a lot for the fixes, @aquynh. I will eventually upgrade snowman to the latest capstone and see what else is broken.

**Comment by hlide** [comment]
For reflection purpose mostly. Suppose you want to patch. The user can make a function to patch a displacement value of any opcode without the need to know about the opcode by fetching all the necessary informations in details to do so.

**Comment by yegord** [comment]
Maybe the right way to patch something is to disassemble it, patch, and assemble again. :)

**Comment by hlide** [comment]
To illustrate in pseudo algorithm:
```
x86_patch_disp8(insn, value):
    mem_oper = find(insn.details.operands, lambda x: x.type == MEM and x.disp.size == 8)
    imm_oper = find(insn.details.operands, lambda x: x.type == IMM)
    if mem_oper then
        disp_pos = insn.size
        if imm_oper then
            disp_pos -= imm_oper.size
        disp_pos -= mem_oper.disp.size   
        insn.bytes[disp_pos] = value
        return true
    else
        return false
```

**Comment by hlide** [comment]
the other issue i see is how do you know *MEM* operand has no *disp*? setting *operands[1].mem.disp* to 0 won't tell us if a *disp* field is present in the opcode.

**Comment by aquynh** [comment]
you are right, the current setup cannot tell. we can only figure that out thanks to other fields in `cs_x86`, such as `modrm`. 

perhaps we can have a macro in `x86.h` to tell us this info?

**Comment by hlide** [comment]
well using *modrm* is more and less like relying on opcode to tell us that information. By full reflection, I mean each component is fully detailed in itself and doesn't depend on other part of the instruction to determine its nature. Since capstone is mostly used as a disassembler I understand most people don't see any interest about having a complete reflective decomposer. And yes I guess using some macros would be better than directly dealing with other fields like *modrm* ("dealing" uglier than having *disp.size* in my opinion).

**Comment by aquynh** [comment]
this discussion reminds me of this pull request: https://github.com/aquynh/capstone/pull/331
