### ISSUE TITLE
Missing API / defines for MIPS float ISA.

### ISSUE THREAD

**Issue by nihilus** [capstone-engine/capstone#414]
The instructions get disassembled correctly however I cannot find defines for add.a and add.s etc in MIPS.h etc.

**Comment by aquynh** [comment]
can you provide the hexcode + hardware mode so i can test this? 

thanks.

**Comment by nihilus** [comment]
Here we go;
Arithmetic Instructions
The arithmetic instructions operate on formatted data values. The result of most floating-point arithmetic operations meets the IEEE standard specification for accuracy; a result which is identical to an infinite-precision result rounded to the specified format, using the current rounding mode. The rounded result differs from the exact result by less than one unit in the least-significant place (ulp).
Table B-8
Mnemonic
ADD.fmt SUB.fmt MUL.fmt DIV.fmt ABS.fmt NEG.fmt SQRT.fmt
C.cond.fmt
FPU IEEE Arithmetic Operations
Description
Floating-Point Add Floating-Point Subtract Floating-Point Multiply Floating-Point Divide Floating-Point Absolute Value Floating-Point Negate Floating-Point Square Root
Floating-Point Compare
Defined in
MIPS I I I I I I II
I
￼Two operations, Reciprocal Approximation (RECIP) and Reciprocal Square Root Approximation (RSQRT), may be less accurate than the IEEE specification. The result of RECIP differs from the exact reciprocal by no more than one ulp. The result of RSQRT differs by no more than two ulp. Within these error limits, the result of these instructions is implementation specific.

fr0k:

**Comment by hlide** [comment]
there is MIPS_INSN_ADD_A
but I cannot find MIPS_INSN_ADD_S though
I wonder whether it is misnamed as MIPS_INSN_FADD

**Comment by hlide** [comment]
*add.s* means *single float addition*, i.e, 32-bit float
I think there is also *add.d* for 64-bit float addition, so I'm a little puzzled by the names of some mips instructions id with prefix MIPS_INSN_ in include/arch/mips.h.

**Comment by nihilus** [comment]
hmmm :-/

**Comment by aquynh** [comment]
can you provide the hexcode so i can test this issue?

**Comment by hlide** [comment]
@aquynh nihilus doesn't use capstone as a simple MIPS disassembler but as a MIPS decomposer for a MIPS decompiler (https://github.com/nihilus/snowman), so he does not use hexcode or anything like you asked as a source. What he need is which instruction id is mapped to which mnemonic (that is, what you find on official document) to implement the equivalent IR. Curiously the ids with prefix MIPS_INS_ are not found for the mnemonics for FPU (xxx.s/xxx.d) and instead we can find things like MIPS_INSN_Fxxx which does not comply with the usual mnemonics, hence the puzzlement because there is no such FADD, FSUB, etc. in MIPS as far as I know.

**Comment by hlide** [comment]
oh god! i tried for *abs.d* because it is mostly a float point operation. And what I found out is beyond my imagination:

* Mips_FABS_D32, MIPS_INS_ABS -> MIPS_GRP_STDENC, MIPS_GRP_NOTFP64BIT

* Mips_FABS_D64, MIPS_INS_ABS -> MIPS_GRP_STDENC, MIPS_GRP_FP64BIT

* Mips_FABS_MM, MIPS_INS_ABS -> MIPS_GRP_MICROMIPS

* Mips_FABS_S, MIPS_INS_ABS -> MIPS_GRP_STDENC

* Mips_FABS_S_MM, MIPS_INS_ABS -> MIPS_GRP_MICROMIPS

**Comment by hlide** [comment]
MIPS_INS_ABS is not encoding a single mnemonic, the same for MIPS_INS_ADD, especially we can find: Mips_FADD_S, MIPS_INS_ADD -> MIPS_GRP_STDENC **and** Mips_ADD, MIPS_INS_ADD -> MIPS_GRP_STDENC. So the only way to check if it is a *add.s* or *add* is to examine their operands (float register vs. integer register) ???

**Comment by hlide** [comment]
@nihilus if your ```_[operand(0) ^= (operand(1)) + (operand(2))];``` can proceed float operands implicitely, you could consider *add.s* and *add.d* as already done [here] (https://github.com/nihilus/snowman/blob/3e664f5d60ccdc79f3a1b370771ed67ddc49aab7/src/nc/arch/mips/MipsInstructionAnalyzer.cpp#L110).

**Comment by nihilus** [comment]
@hlide ah... That is so wrong inso many ways ;-)

**Comment by nihilus** [comment]
I am also missing 'mad' and 'madu' from the MIPS32 ISA.

**Comment by hlide** [comment]
@nihilus look inside "GIT\capstone\arch\Mips\MipsMapping.c". I do it with a search with "MADU" but nothing. Are you sure it is not "MADDU"?

**Comment by nihilus** [comment]
@hlide Yes, according to Sweeetman's See MIPS Run that's to different instructions

**Comment by hlide** [comment]
well i guess the MIPS support for LLVM is still poor

**Comment by nihilus** [comment]
@hlide Indeed, even bnezl seems to be handled incorrect: [Warning] Invalid instruction `bnezl $v0, 0x40bc50' at 0x40bc0c: The instruction does not have an argument with index 2

**Comment by aquynh** [comment]
i will upgrade Mips to the latest LLVM sometime this month. meanwhile, can you guys put together all the issues in 1 place, so i can look at that? for some missing instructions, we can either do that ourself, or report to LLVM.

thanks.

**Comment by hlide** [comment]
*bnezl* is not a canonical instruction: `bnezl rs, target` is an alias standing for the real instruction `bnel rs, $0, target`. Instead of relying with a very minimal and orthogonal set of instructions enough to cover anything, I fear you must deal with all that aliasing scrap.

**Comment by nihilus** [comment]
For bnezl  this actually works:
      	 	case MIPS_INS_BNEL: /* Fall-through */    
         	case MIPS_INS_BNE: {
         		if(detail_->op_count == 3)
        		_[
        			jump(~(operand(0) == operand(1)), operand(2), directSuccessor())
        		];
        		else /* BNEZL */
        		_[
        			jump(~(operand(0) == constant(0)), operand(1), directSuccessor())
        		];
    	    	break;
       	 	}

**Comment by nihilus** [comment]
MIPS_INS_MUL is not 'MUL.D' which it actually works as an alias for today!

**Comment by aquynh** [comment]
please provide the input hexcode so i can test this, thanks.

**Comment by hlide** [comment]
MIPS_INS_FMUL ?

**Comment by nihilus** [comment]
@hlide yeah, FMUL should be correct. However it does map to MUL.

**Comment by nihilus** [comment]
And again: I dont have the hexcode at hand but it is described in See MIPS Run. I can try looking it up when I am home.
