### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [capstone-engine/capstone#42]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [MCOperand_CreateReg](https://github.com/aquynh/capstone/blob/39da42692de1431814fb0202907d5b48a74f3b14/MCInst.c#L153)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [Mips_printInst](https://github.com/aquynh/capstone/blob/24ca24c5dbad62c4cd4809e6020ade877afc28fd/arch/Mips/MipsInstPrinter.c#L154)

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
