### ISSUE TITLE
Suggestion: Docs in github wiki

### ISSUE THREAD

**Issue by 2a03** [capstone-engine/capstone#423]
Recent SourceForge downtime highlighted a significant problem — almost complete abscence of documentation in the repo. 
###### Suggestions:
1. To move changelogs from wiki to descriptions in Releases tab  — those are really getting in the way as they are now and not that helpful while scattered by multiple tiny pages.
2. Move/Copy documentation from site to wiki.
3. (Optionally) Link wiki repository as a submodule to main repo — so everyone who checked it out would have the docs as well.

**Comment by aquynh** [comment]
great suggestions, thanks!

- i just put the ChangeLog of v3.0.4 into the Release tab.
- will copy docs from the homepage to wiki soon.
- why creating submodule, if we can put all the docs into docs/ directory?
   
  then what concerns me is that the docs are in .md format, which makes them a bit hard for users to read in plain text form?

**Comment by aquynh** [comment]
we now have all the docs in the wiki at https://github.com/aquynh/capstone/wiki.

thanks.

**Comment by aquynh** [comment]
besides the main site (http://capstone-engine.org), now we have a backup website at http://capstone-engine.github.io

thanks.

**Comment by 2a03** [comment]
Thank you very much @aquynh.

> why creating submodule, if we can put all the docs into docs/ directory?

To make the same docs available in wiki interface on GitHub and in repo — which helps to avoid duplication and necessity to check that documentation everywhere is consistent with release and is up to date. Instead of copying by hand, submodule can be just synchronized. 

But care should be taken — by default, **everybody** can commit to wiki. So either this should be changed beforehand in GitHub settings, or wiki should be carefully checked before sync'ing. This workflow may not seem that convinient, that's why it comes with _«(Optionally)»_

> the docs are in .md format, which makes them a bit hard for users to read in plain text form?

Well, [Markdown](https://guides.github.com/features/mastering-markdown/) essentially *is* the plain text. It was designed to be readable _«as is»_ from the very beginning, so that markup elements don't obscure and clutter actual text, (comparing to [MediaWiki markup](https://en.wikipedia.org/wiki/Help:Wiki_markup), for example). 
And it's hard to imagine anyone capable of using disasm lib not trying to open contents of «Docs» folder with cat, less,  favourite text editor or F3 in two–panel file manager. :smirk:

**Comment by aquynh** [comment]
yes, this makes a lot of sense. only one thing concerning me is that compared to the generated html, .md files lose some information.

i will see how to do this, thanks!

**Comment by bnagy** [comment]
Given the recent SourceForge actions (hijacking legit projects to insert malware) I would suggest dropping them completely.

**Comment by aquynh** [comment]
yes, we already switched to host website on Github 2 days ago.

**Comment by bnagy** [comment]
👍

**Comment by Snaipe** [comment]
I would probably recommend using [sphinx](http://sphinx-doc.org/) to generate the documentation; you would be able to seamlessly integrate an up-to-date documentation at capstone-engine.org.

For me, the big plus would be the following features:
* Man page, PDF, and HTML generation
* ReStructuredText input, which offers a lot more control than markdown while still being very readable/expressive in plain text
* Themeing of the output HTML to match your website
* The documentation is directly available in the repository

Also, if you need somewhere to host the docs, you can do so for free on https://readthedocs.org.

Now of course, this is only my opinion, so you should probably check it for yourself.
