### ISSUE TITLE
How to get the value of ds:esi ?

### ISSUE THREAD

**Issue by vedon** [capstone-engine/capstone#437]
the source code and the corresponding  assembly code 

![1 pic](https://cloud.githubusercontent.com/assets/1811570/9020381/129304ec-383b-11e5-8463-28dd5c6ee236.jpg)
![3 pic](https://cloud.githubusercontent.com/assets/1811570/9020382/12ca797c-383b-11e5-9aba-316210f475b7.jpg)

**Comment by aquynh** [comment]
are you confusing static & dynamic analysis?

Capstone is for static analysis, so it cannot get you the value of these registers.
So the question is irrelevant here, sorry.

The answer is to use your debug interface to get the register values <=== dynamic analysis part

**Comment by vedon** [comment]
@aquynh thx for reply , i See

**Comment by vedon** [comment]
In arm assembly code ,is it static analysis??

**Comment by aquynh** [comment]
static analysis means you do not run the code. example: disassembling. 
you dont get register value when doing static analysis.

dynamic analysis means you run the code. example: debugging.
you CAN get register value when doing static analysis.

so do not confuse

**Comment by aquynh** [comment]
updated: "you CAN get register value when doing DYNAMIC analysis."

**Comment by vedon** [comment]
Ok ,great explanations . From my snapshot ,there is a way to calculate the esi register value ?just do the math on hand.

**Comment by aquynh** [comment]
i dont know. you should consult the docs of your dynamic analysis tool (debugger?) on how to retrieve register value at run-time.

**Comment by hlide** [comment]
not only that, there is no reason for EDI to be the same value whenever you launch the application as it may be the address of a dynamic allocated object.

**Comment by hlide** [comment]
You should find the assembly code of *PageCache::singleton*, your answer will be the value set to *eax* as a returned pointer of this function.

**Comment by vedon** [comment]
@hlide  yes ,you are right.  I set a breakpoint in xcode and found that  i can get the value of %esi from the popl %esi  instruction .the value of %esi  is the instruction Address .aka ,98b759a.
