### ISSUE TITLE
[Enhancement] Add version info

### ISSUE THREAD

**Issue by halsten** [capstone-engine/capstone#447]
Is it possible to add a version resource info for the capstone DLL? It's confusing sometimes to know which dll I am using and would be helpful if I can just get that info from the version number as a resource.

--halsten

**Comment by aquynh** [comment]
From where did you get this DLL? Or if you compiled that, how did you
compile?

Thanks.


On Aug 11, 2015 3:30 PM, "Mohamed Saher" <notifications@github.com> wrote:
>
> Is it possible to add a version resource info for the capstone DLL? It's
confusing sometimes to know which dll I am using and would be helpful if I
can just get that info from the version number as a resource.

**Comment by halsten** [comment]
I use the compiled version obtained through the website.

**Comment by aquynh** [comment]
that was compiled with CMake & MSVC on Windows.

if you can send in a Github Pulll-Request to fix this issue, that would be
great!
some instructions to do this is available at
http://www.codeofclimber.ru/2015/generate-windows-dll-version-info-resource-with-cmake/

thanks.

**Comment by halsten** [comment]
Absolutely.
