### ISSUE TITLE
SIGSEGV in X86GenAsmWriter1

### ISSUE THREAD

**Issue by toastedcornflakes** [capstone-engine/capstone#463]
I encountered a crash in x64 disassembler (compiled with diet mode, latest master)

```
from capstone import *
from binascii import unhexlify
md = Cs(CS_ARCH_X86, CS_MODE_64)
d = md.disasm(unhexlify("402626485166646466666c695166430100f8666253554103f7de05"), 0x1000)
for i in d:
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

Stopped reason: SIGSEGV
0x00000000004d549a in getRegisterName (RegNo=0x0) at arch/X86/X86GenAsmWriter1.inc:15023
15023     return AsmStrs+RegAsmOffset[RegNo-1];
```

**Comment by aquynh** [comment]
which Capstone version are you using? i am quite sure that the latest version 3.0.4 does not allow you to access to `i.mnemonic`, which is irrelevant in DIET mode.

thanks.

**Comment by toastedcornflakes** [comment]
Sorry, my snippet was wrong. The crash is reproducible just by calling `capstone.disasm` and consuming the iterator. Using the DIET mode or not is irrelevant. The crash still occurs with full capstone:

    from capstone import *
    from binascii import unhexlify
    md = Cs(CS_ARCH_X86, CS_MODE_64)
    d = md.disasm(unhexlify("402626485166646466666c695166430100f8666253554103f7de05"), 0x1000)
    list(d)

(I also reinstalled the bindings, not sure if that was necessary)

**Comment by aquynh** [comment]
confirmed. will see how to fix this, thanks.
