### ISSUE TITLE
ARM: UDF vs TRAP

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#466]
Looks like capstone is assuming that `udf 0xfdef` is a trap, which in reality all the `udf` instructions are traps, which in reality, all the udf instructions are in fact traps. Some debuggers use that specific udf as a custom breakpoint. But in reality any other can be used, and in fact, some debuggers use multiple UDF instructions as traps in order to differentiate them. IMHO it would be good that capstone doesn't makes that assumption.

**Comment by stevemk14ebr** [comment]
this needs to be proof read i can't understand what you're saying at all.

**Comment by hlide** [comment]
I think @radare means *udf* can be used for several usages by using different encodings and not only that `udf 0xfdef`.

**Comment by aquynh** [comment]
yes i dont understand what he is trying to say. it is better with input & expected output, as usual. thanks.

**Comment by radare** [comment]
```
udf 16     ; trap (arm32-linux)  <- produces SIGTRAP
udf 1      ; trap (thumb-linux)
trap       ; alias for udf fede or fedeffe7(by capstone)
udf 0xfdee ; kgdb trap (spawns kernel or jtag debugger) kgdb or angel (capstone trap)
udf 0xfdef ; gdb trap (arm32-linux)
udf 0x20   ; bpf hole (arm32-linux) - used by the bpf jit
udf 3      ; bpf hole (thumb-linux) ""
bkpt 0     ; breakpoint instruction (0xe1200070) (slow?)
udf X      ; any other unhandled value produces SIGILL and core dump (on linux)
```
The reason why the choice of fdee is because it is a trap instruction for ARM and Thumb at the same time. But this is not the only UDF instruction that is compatible between arm and thumb, for example:
```
fedeffe7 arm     trap
fede     thumb   trap
or
fddeffe7 arm     udf 0xfded
fdde     thumb   udf 0xfd
...
```
Those instructions can be also used a *traps*. So it depends on the context, and i would prefer to always see `udf` instead of having to look between `udf` or `trap`.

**Comment by radare** [comment]
ping?

**Comment by aquynh** [comment]
looks interesting. will see how to fix this when i have more time, thanks.
