### ISSUE TITLE
Support Intel MPX instructions

### ISSUE THREAD

**Issue by eteran** [capstone-engine/capstone#468]
Currently, capstone displays things like:

```
66 0f 1b 04 24    ; bndmv [rsp], bnd0
66 0f 1b 4c 24 10 ; bndmov [rsp+0x10], bnd1
```

as nops with a ModRM. They are in fact, valid instructions using the MPX instruction set.
Demonstrated here: https://www.onlinedisassembler.com/odaweb/LI7eVBQ3/0

**Comment by aquynh** [comment]
a quick check and every disassemblers (even Xed2) except GNU (which ODA is using) report these as NOP instructions. given the bad track of record of GNU, are you sure ODA is right here?

thanks.

**Comment by eteran** [comment]
I good question, I'll check the Intel docs and see if I can confirm.

**Comment by eteran** [comment]
Looking at thedocs found here (http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf) I see this:

    66 0F 1A /r RM NE/V MPX Move lower and upper bound from bnd2/m64 to bound register
    BNDMOV bnd1, bnd2/m64 bnd1.
    66 0F 1A /r RM V/NE MPX Move lower and upper bound from bnd2/m128 to bound register
    BNDMOV bnd1, bnd2/m128 bnd1.
    66 0F 1B /r MR NE/V MPX Move lower and upper bound from bnd2 to bnd1/m64.
    BNDMOV bnd1/m64, bnd2
    66 0F 1B /r MR V/NE MPX Move lower and upper bound from bnd2 to bound register
    BNDMOV bnd1/m128, bnd2 bnd1/m128.

So looks like ODA might be right

**Comment by 10110111** [comment]
These instructions' legacy behavior is NOP, but when MPX is supported/enabled, they are non-nop instructions.

**Comment by 10110111** [comment]
Indeed, citing _Intel Architecture Instruction Set Extensions Programming Reference_ section 9.3.6:

> When Intel MPX is not enabled or not present, all Intel MPX instructions behave as NOP.

Although in older Intel's manuals opcode tables list most of them as reserved, AMD's manuals do list them as NOP, so indeed the legacy behavior in all earlier CPUs is NOP for MPX instructions in both Intel and AMD..

**Comment by hlide** [comment]
And I am also pretty sure GNU x86-32/64 bit architecture is not that bad as mentionned here. Intel and AMD also have their GNU gcc so undoubtedly they do good job with GNU binutils. As for Xed2, I wonder if it is a recent version.

**Comment by hlide** [comment]
I think MPX is now supported by XED : https://github.com/intelxed/xed and https://github.com/intelxed/xed/blob/master/datafiles/mpx/mpx-isa.txt.

**Comment by aquynh** [comment]
yes, planning the next major update, soon.

**Comment by davidbrazdil** [comment]
Sorry to ping but is there an ETA on when MPX support might be in "next"?

**Comment by XVilka** [comment]
Seems you can find them in real world binaries more and more. Will be useful to have it eventually.

**Comment by dukebarman** [comment]
What about bnd* instructions support? (bndmov, bndmk, etc.)
