### ISSUE TITLE
PowerPC: missing support for the 750CL's Paired Singles instruction.

### ISSUE THREAD

**Issue by phire** [capstone-engine/capstone#476]
Paired Singles is an vector instruction set extension for PowerPC, developed as a lightweight alternative to AltiVec, only dealing with two single precision floats at a time. The extension was originally developed for Nintendo with  the Gekko cpu found in the GameCube, and the Broadway and Espresso cpus in Nintendo's Wii and Wii-U support it too.

IBM also released the 750CL for non-Nintendo embedded customers with support for Paired Singles.

[Documentation can be found here](https://fail0verflow.com/media/files/ppc_750cl.pdf).

There is also an initial attempt at a paired singles support for llvm [here](https://github.com/Tilka/llvm-ppc750cl).

**Comment by aquynh** [comment]
any plans for LLVM to include this fix yet? 

let me know when this happens, so i will upgrade PPC core to have this supported. thanks.

**Comment by terorie** [comment]
Hi @aquynh, there is a second attempt to get paired-singles added to LLVM from last year it seems: https://reviews.llvm.org/D85137

Does Capstone depend on LLVM's disassembler? I would like to write a patch adding paired-singles support to Capstone.

Sorry for the necropost 🙂 This issue is still relevant to a small number of people working on Nintendo Wii reverse engineering.

**Comment by terorie** [comment]
Hi @kabeor, why this was closed?

**Comment by kabeor** [comment]
@terorie 
Sorry, we are cleaning legacy issues. Cause there were 400+ issues, so I have to close some of the earliest issues and see who will reply and manual reopen. Welcome back, I will continue to work on your issue here :)

**Comment by kabeor** [comment]
@terorie I reviewed this issue, it's interesting. Can you do a PR to `next` branch for this?

**Comment by terorie** [comment]
@kabeor Sure, I'll revisit this. Last time I looked at it, I was stuck because I couldn't figure out how to re-run LLVM TableGen code generation to add the missing instructions without breaking other things.
The LLVM upstream attempt to modify the td files has diverged a lot from the Capstone codebase too.

**Comment by kabeor** [comment]
@terorie you can check this [folder](https://github.com/capstone-engine/capstone/blob/next/suite/synctools/tablegen) to see if it can help to do some thing.
Actually, these scripts in the folder still use some llvm 7.0 tools which is very old. I was wondering how to get it updated to lastest llvm 13 tools. 

Please feel free to share if you have any thought about this.

**Comment by terorie** [comment]
Hey @kabeor, I've written TableGen definitions for all 750CL extension opcodes now. Unfortunately, LLVM 7.0.1 doesn't work anymore and is failing on unrelated code that I haven't touched. I think it might be due to an LLVM version mismatch. Can you confirm the correct LLVM version please?
Thanks 🙏🏻 

```
./gen-tablegen-arch.sh ~/opt/llvm-project/llvm/build/bin/ PPC 
...
Generating PPCGenSubtargetInfo.inc
Included from PPC/PPC.td:298:
Included from PPC/PPCSchedule.td:138:
Included from PPC/PPCScheduleP9.td:13:
Included from PPC/PPCInstrInfo.td:3173:
PPC/PPCInstrHTM.td:25:18: error: Couldn't find class 'PPCCustomInserterPseudo'
def TBEGIN_RET : PPCCustomInserterPseudo<(outs gprc:$out), (ins u1imm:$R), "#TBEGIN_RET", []>;
```

**Comment by terorie** [comment]
I think this commit https://github.com/capstone-engine/capstone/commit/839c5e2c1939e22400f51971687cacd8280d5062 creates a dependency on https://github.com/llvm/llvm-project/commit/c7b43b94ced62e9ce4c7cbb6a1cbafa350e646fa which is only in LLVM 8.0

**Comment by terorie** [comment]
I see, I think hot fix https://github.com/capstone-engine/capstone/pull/1510 uses a patched LLVM but it's not documented what the right version is.

**Comment by terorie** [comment]
My TableGen compiles now and I'm sending in a patch some time today. 🥳

**Comment by kabeor** [comment]
WoW, amazing. Looking forward to your PR:)

**Comment by terorie** [comment]
@kabeor #1898 is now ready for review and tested
