### ISSUE TITLE
ocaml bindings with _oasis

### ISSUE THREAD

**Issue by m4b** [capstone-engine/capstone#482]
I'm not sure how best to implement this, whether it's reasonable, etc., but I'm wondering how feasible it would be to add an `_oasis` buildfile to the OCaml bindings to ideally:
1. enable easy git submodule embeddings in Oasis based OCaml projects
2. use the capstone ocaml bindings with an already existent oasis build for seamless project integration

My use case is that I'd like to add capstone as a submodule to http://github.com/m4b/rdr so that I get constant upstream changes from capstone, and also a free disassembler.

Then, I'd simply add a `PrebuildCommand` to make the initial libcapstone library, and then have the ocaml bindings be an oasis library, which is then a build-dependency in the actual OCaml oasis project which now can use libcapstone.

Unfortunately I'm unable to get it working with oasis/ocamlbuild, and the makefile inside the bindings creates a bunch of object files inside the ocaml bindings directory, which then counts as polluting the directory, etc.  There are ways around some of these problems, but I'm unable to get it successfully integrated with `rdr`.

Anyway, I think an `_oasis` file would be a really great addition (if we can get it working properly), and at the very least, provides nice metadata.

**Comment by aquynh** [comment]
please go ahead doing this and send in a pull request. 
i will find some Ocaml experts to help review it.

thanks for stepping up to make Ocaml binding better!
