### ISSUE TITLE
Suggestion:performance optimization

### ISSUE THREAD

**Issue by bughoho** [capstone-engine/capstone#483]
I have two small suggestions:
## 1:About InternalInstruction,

``` c++
memset(&insn, 0, offsetof(InternalInstruction, reader));  <---X86Disassembler.c
```

I used the msvc ide to do the performance test.
![1](https://cloud.githubusercontent.com/assets/10548054/10126255/c859e310-65c0-11e5-9e55-1d1a5bfd4bfd.png)

I moved the prefixPresent[0x100] and prefixLocations[0x100] to the back of "byteReader_t reader".
like this:

``` c
typedef struct InternalInstruction {
 ....
  /* Reader interface (C) */
  byteReader_t reader;

  //bughoho modified at 2015.09.27 这两个是从前面移动到下面来的,避免memset消耗太多性能
  /* 1 if the prefix byte corresponding to the entry is present; 0 if not */
  uint8_t prefixPresent[0x100];
  /* contains the location (for use with the reader) of the prefix byte */
  uint64_t prefixLocations[0x100];
  //bughoho end
```

and i just initialize some the necessary values to avoid consuming performance:
like this:

``` c
    memset(&insn, 0, offsetof(InternalInstruction, reader));
    insn.prefixPresent[0x26] = 0;
    insn.prefixPresent[0x2e] = 0;
    insn.prefixPresent[0x36] = 0;
    insn.prefixPresent[0x3e] = 0;
    insn.prefixPresent[0x64] = 0;
    insn.prefixPresent[0x65] = 0;
    insn.prefixPresent[0x66] = 0;
    insn.prefixPresent[0xf0] = 0;
    insn.prefixPresent[0xf2] = 0;
    insn.prefixPresent[0xf3] = 0;
    //end
```

finally result:
![2](https://cloud.githubusercontent.com/assets/10548054/10126263/08dbd772-65c1-11e5-995e-77c2c17a8c1d.png)
## 2:About this I just offer a suggestion:

``` c++
typedef struct cs_insn{
uint8_t bytes[16];
}
```

sometmes,we may be could use uint8_t\* byte instead uint8_t bytes[16]? "uint8_t\* bytes" could direct reference to a pointer to an incoming parameter
thus,we can eliminating unnecessary memcpy.

**Comment by onesbug** [comment]
ah..I almost forgotten.There is also a suggestion.
CAPSTONE_EXPORT
bool cs_disasm_iter(csh handle,
	const uint8_t **code, size_t *size,
	uint64_t *address, cs_insn *insn,
	bool needformat); <-----this
and this:
		if (needformat)
			handle->printer(&mci, &ss, handle->printer_info);

In some cases,i just need the instruction information and don't need text information,but the "printer" function is very expensive.

**Comment by aquynh** [comment]
on the idea (1): this looks interesting. can you send a pull-request together with your benchmark code?

on the idea (2), this requires separate allocation for bytes[].

on the new "needformat" argument, this breaks the current API, so we should avoid it.
you can find similar implemented in our compile-time option named "DIET": http://www.capstone-engine.org/diet.html

thanks.
