### ISSUE TITLE
Some MIPS FPU instructions doesn't map to the functions

### ISSUE THREAD

**Issue by nihilus** [capstone-engine/capstone#486]
Found not to work for decompilation is:

```
MIPS_INS_CEQ
MIPS_INS_CEQI
```

any clue on how to make them map to the disassembly?

**Comment by nihilus** [comment]
I am stupid: I should obviously use: MIPS_INS_FCEQ

**Comment by nihilus** [comment]
Actually lots of MIPS FPU instructions is missing in the capstone API :-(

**Comment by nihilus** [comment]
Here are the compare instructions with encodings: https://llvm.org/svn/llvm-project/llvm/tags/RELEASE_33/rc3/test/MC/Mips/mips-fpu-instructions.s

**Comment by nihilus** [comment]
I cannot really figure out how to use MIPS_INS_C and MIPS_INS_CVT because of the different "sub instructions"

**Comment by aquynh** [comment]
can you list all the missing FPU instructions?

**Comment by nihilus** [comment]
I have made a local patch... I will send it when Ive fixed up CVT as well.

**Comment by nihilus** [comment]
It is just a matter of mapping them to individual defines / enums

**Comment by nihilus** [comment]
@aquynh look how I did here: cb6c6fba3a12240e86c834ab72f61c999b94d162
This makes MIPS_INS_C usable for a decompiler.
