### ISSUE TITLE
Expose supported architectures in defines

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#508]
Capstone should generate an include file at compile time in order to inform which architectures are included in the build that is going to be used by 3rd party projects.

**Comment by aquynh** [comment]
at run-time, we have the API `cs_support()` that can tell you which archs are supported. example: cs_support(CS_ARCH_X86) will return True if X86 is compiled, and False otherwise.

**Comment by radare** [comment]
i need this at compile time, because otherwise the code cant be compiled

**Comment by aquynh** [comment]
I would suggest to compile them together to solve your problem. I think it is wrong and confused to generate header file to include which archs are compiled.

**Comment by revskills** [comment]
this should be at compile time IMO.. If you suggest to do that in compile time doesn't make sense for third party projects using capstone. What is the benefit of run-time vs. compile it?.

**Comment by aquynh** [comment]
how about at compile time you have some simple code to verify which arch is compiled?

typically, it is like this:

    #include <capstone/capstone.h>
    int main(int argc, char **argv) { if (cs_support(argv[1]))) return 1; return 0; }

then you can call `./check_arch CS_ARCH_X86` and get the result.

**Comment by aquynh** [comment]
again, i want to keep the header files the same regardless which archs are compiled. dont you think it is confused if `capstone.h` varies on different machines?

**Comment by radare** [comment]
This will not work if you are crosscompiling.

I dont understand why a single define like CAPSTONE_HAS_$arch may hurt you in any way. It just makes things cleaner and easier

**Comment by radare** [comment]
hello?

**Comment by aquynh** [comment]
i already explained that i want to keep capstone.h the same regardless of how the framework is compiled.

**Comment by radare** [comment]
I didnt said at any moment that i wanted to modify capstone.h.. So i guess i should do a pullreq and demonstrate with an asciinema the reason why the current approach is wrong.

**Comment by radare** [comment]
I have submitted a PR with my change proposal, please review and let me know what you see.

**Comment by arrowd** [comment]
How about adding `FindCapstone.cmake` that, aside of usual PkgConfig machinery, would preform `try_compile` on code like

```
#include <capstone/capstone.h>
int main(int argc, char **argv) { if (cs_support(argv[1]))) return 1; return 0; }
```

and then set appropriate variables (`CAPSTONE_HAS_ARCHX`)?
