### ISSUE TITLE
[Featrue Request]Expose displacementOffset and immediateOffset

### ISSUE THREAD

**Issue by bughoho** [capstone-engine/capstone#509]
For Example:
mov dword ptr ds:[0x401000],0x402000
Among them,0x401000 and 0x402000 are in relocation table,I need to identify them.
I found displacementOffset and immediateOffset in InternalInstruction,but struct cs_insn has not.
Can I add displacementOffset and immediateOffset in struct cs_insn and commit a PR?
thanks.

**Comment by aquynh** [comment]
we have similar requests so far: https://github.com/aquynh/capstone/pull/331, https://github.com/aquynh/capstone/issues/443, https://github.com/aquynh/capstone/issues/392 & https://github.com/aquynh/capstone/pull/444.

i am thinking about adding an "encoding" struct  to `cs_x86`, which exposes all the encoding info inside this structure.

**Comment by onesbug** [comment]
yeah,should be cs_x86.
Except displacementOffset and immediateOffset,Anything else you need?
could you provide a new cs_x86 struct to me?I would like to do the actual work,

**Comment by aquynh** [comment]
no, i dont really need anything. these are requests from community.

we will just do what people want, and nothing else. so please go ahead with the info people requested in the links i post above. 

thanks for stepping up for this work!

**Comment by onesbug** [comment]
Sorry,I don't have any offense.:)
I met two problem:
1:
https://github.com/aquynh/capstone/blob/next/include/capstone/x86.h#L291
Regarding Displacement value,if have a instruction such as:
```
mov dword ptr ds:[0],0
```
How to judge it?I think it is a bug. maybe also need to add a add dedicated variables:consumedDisplacement

2:
https://github.com/aquynh/capstone/blob/next/arch/X86/X86DisassemblerDecoder.h#L692
Why this is happening?Are there any samples?

**Comment by aquynh** [comment]
i dont understand the question (1). what is wrong?

same for (2): what is wrong?

**Comment by onesbug** [comment]
for (1):
for example:
```
1:mov eax,ecx
2:mov dword ptr [0],ecx
```
For cs_insn->cs_detail->cs_x86->disp,Their values are 0,if so,How do I know if this instruction is(or not) using disp?
for (2):
According to what I know,the x86 instruction only have one displacement and one immediate at the most,so i don't know that under what circumstances will contain two immediate in an instruction?

**Comment by aquynh** [comment]
(1) yes, your info is only relevant for example if one of the operands is a memory operand (`X86_OP_MEM`).

(2) X86 does not have instructions with 2 memory operands. same applies for 2 immediates i think (otherwise we need to stick this encoding info to operand instead (struct `cs_x86_op`).

**Comment by onesbug** [comment]
1>d:\capstone\arch\m68k\m68kdisassembler.c(321): error C2059: 语法错误:“{”
1>d:\capstone\arch\m68k\m68kdisassembler.c(321): error C2065: “value”: 未声明的标识符
1>d:\capstone\arch\m68k\m68kdisassembler.c(321): error C2059: 语法错误:“)”
1>d:\capstone\arch\m68k\m68kdisassembler.c(323): error C2143: 语法错误 : 缺少“{”(在“->”的前面)
1>d:\capstone\arch\m68k\m68kdisassembler.c(323): error C2059: 语法错误:“->”
1>d:\capstone\arch\m68k\m68kdisassembler.c(325): error C2059: 语法错误:“if”
1>d:\capstone\arch\m68k\m68kdisassembler.c(376): error C2143: 语法错误 : 缺少“{”(在“->”的前面)
1>d:\capstone\arch\m68k\m68kdisassembler.c(376): error C2059: 语法错误:“->”
1>d:\capstone\arch\m68k\m68kdisassembler.c(377): error C2143: 语法错误 : 缺少“{”(在“->”的前面)
1>d:\capstone\arch\m68k\m68kdisassembler.c(377): error C2059: 语法错误:“->”
1>d:\capstone\arch\m68k\m68kdisassembler.c(379): error C2059: 语法错误:“if”
1>d:\capstone\arch\m68k\m68kdisassembler.c(386): error C2059: 语法错误:“else”
1>d:\capstone\arch\m68k\m68kdisassembler.c(398): error C2059: 语法错误:“if”
1>d:\capstone\arch\m68k\m68kdisassembler.c(401): error C2059: 语法错误:“}”
1>d:\capstone\arch\m68k\m68kdisassembler.c(530): warning C4013: “get_ea_mode_op”未定义；假设外部返回 int
1>d:\capstone\arch\m68k\m68kdisassembler.c(789): error C2059: 语法错误:“{”
1>d:\capstone\arch\m68k\m68kdisassembler.c(789): error C2065: “value”: 未声明的标识符
1>d:\capstone\arch\m68k\m68kdisassembler.c(789): error C2059: 语法错误:“)”
1>d:\capstone\arch\m68k\m68kdisassembler.c(790): error C2065: “info”: 未声明的标识符
1>d:\capstone\arch\m68k\m68kdisassembler.c(790): warning C4047: “函数”:“m68k_info *”与“int”的间接级别不同
1>d:\capstone\arch\m68k\m68kdisassembler.c(790): warning C4024: “build_init_op”: 形参和实参 1 的类型不同
1>d:\capstone\arch\m68k\m68kdisassembler.c(790): error C2065: “opcode”: 未声明的标识符
1>d:\capstone\arch\m68k\m68kdisassembler.c(790): error C2065: “size”: 未声明的标识符

I'm ready to send a PR,m68kdisassembler.c was broken?I use msvc 2013.

**Comment by aquynh** [comment]
you can either open a new issue for M68K, or report it here: https://github.com/aquynh/capstone/issues/494

**Comment by hlide** [comment]
x86 instructions with recent instructions like AVX can have more than one immediate.

**Comment by bughoho** [comment]
amazing!Is there an example of this?

**Comment by hlide** [comment]
I read it somewhere but I fell to find out where. I probably misread it so I examined all the documents I had and I arrived to a conclusion there was no such second immediate after the first one, which means only one immediate always ends the instruction when available. If another immediate were needed, it might be embedded inside a long prefix.

**Comment by hlide** [comment]
To be precised, I read about an extra 4/8-bit immediate.

**Comment by bughoho** [comment]
@hlide,if so,the design is too complicated.I can't understand Why not use other variables to express immediate[1]
