### ISSUE TITLE
Support for mcrfs instruction in PowerPc

### ISSUE THREAD

**Issue by endeav0r** [capstone-engine/capstone#519]
It would appear these instructions are supported in llvm, but not yet in capstone:

http://llvm.org/viewvc/llvm-project?view=revision&revision=226070

Perhaps rebuild the instruction definitions in capstone from llvm?

**Comment by aquynh** [comment]
ok, will see when i have time to update for PPC.

thanks for the heads up.

**Comment by aquynh** [comment]
this is now supported in the "next" branch.

```
$ cstool -d ppc64be "0xfe 0x14 0x00 0x80"
 0  fe 14 00 80  mcrfs	cr4, cr5
	ID: 679 (mcrfs)
	op_count: 2
		operands[0].type: REG = cr4
		operands[1].type: REG = cr5
```
