### ISSUE TITLE
x86 relative call/jcc immediate operand

### ISSUE THREAD

**Issue by obs1dium** [capstone-engine/capstone#525]
When disassembling instructions such as `EB 04`, Capstone will return a single operand of type `X86_OP_IMM` with size 8 (in 64-bit mode) that already contains the effective target address, i.e. `insn.address + insn.size + sign_extend(imm)`.
Personally, I think the operand should contain the actual immediate value and size (4 and 1 in this example). It is easy to calculate the target address from that, maybe through a simple helper function.

**Comment by aquynh** [comment]
previously, this is what we did. but then since most people just want target address, but not relative address, we made the change.

**Comment by obs1dium** [comment]
I agree that most of the time you'll want absolute addresses, especially when printing out the disassembly. It's still a bit inconsistent, seeing as other RIP-relative addresses are not changed. For example, `48 8D 05 0A 00 00 00` correctly disassembles to `lea rax,[rip + 0xa]` regardless of the instructions VA and its memory operand's displacement is not messed with.

My ideal solution would be this:
* Provide an option to toggle between relative and absolute addresses for textual output 
* Provide a function to perform the conversion from relative to absolute addresses
* Leave the (immediate) operands untouched, i.e. relative values with correct sizes

Any comments are welcome, of course.
