### ISSUE TITLE
PPC static branch prediction hint information unavailable

### ISSUE THREAD

**Issue by kevemueller** [capstone-engine/capstone#543]
PPC allow static branch prediction hint to be encoded into the instruction opcode. This information seems to be currently unavailable with capstone.
e.g. 0x41bdfdfc should decode to bgt- cr7, 0xfffffdfc while it is currently decoded to bgt cr7,0xfffffdfc
which actually corresponds to 0x419dfdfc.

Static branch prediction hint should be exposed by capstone and the static hint encoded into the mnemonic.

**Comment by aquynh** [comment]
with the "next" branch, here is the output now.

```
$ cstool -d ppc64be "41bdfdfc 419dfdfc"
 0  41 bd fd fc  bc	0xd, cr7gt, 0xfdfc
	ID: 17 (bc)
	op_count: 3
		operands[0].type: IMM = 0xd
		operands[1].type: REG = cr7gt
		operands[2].type: IMM = 0xfdfc

 4  41 9d fd fc  bt	cr7gt, 0xfe00
	ID: 178 (bt)
	op_count: 2
		operands[0].type: REG = cr7gt
		operands[1].type: IMM = 0xfe00
```

any comments?

**Comment by ceeac** [comment]
Is there a reason to display the branch prediction hint as an operand? The `cs_ppc` struct has a member that can store the hint so IMO it makes sense to use the member instead of the operand.

**Comment by aquynh** [comment]
just because LLVM considers them registers. i can fix that, perhaps by updating cs_ppc fields?
