### ISSUE TITLE
Check union type-punning usage

### ISSUE THREAD

**Issue by j123123** [capstone-engine/capstone#551]
Type-punning using union is endian-dependent. And floating number binary representation can be big endian on CPU with little endian integer types, and vice-versa
https://en.wikipedia.org/wiki/Endianness#Floating-point

> Although the ubiquitous x86 processors of today use little-endian storage for all types of data (integer, floating point, BCD), there have been a few historical machines where floating point numbers were represented in big-endian form while integers were represented in little-endian form.[16] There are old ARM processors that have half little-endian, half big-endian floating point representation for double-precision numbers: both 32-bit words are stored in little-endian like integer registers, but the most significant one first. Because there have been many floating point formats with no "network" standard representation for them, there is no formal standard for transferring floating point values between diverse systems. It may therefore appear strange that the widespread IEEE 754 floating point standard does not specify endianness.

So this code may be wrong on some architectures: https://github.com/aquynh/capstone/blob/master/arch/AArch64/AArch64AddressingModes.h#L186-L205
I think, need to use some platform-specific header for this thing (like ieee754.h)
see also https://stackoverflow.com/questions/5242589/would-float-point-format-be-affected-by-big-endian-and-little-endian

**Comment by aquynh** [comment]
can you send a pull request for this issue?

**Comment by j123123** [comment]
How many architectures supported by capstone(I mean not arch which it can disassemble, I mean "on how many arch it should be able to run" )? I need info about float representation on all supported arch, and then I can send a pull request

**Comment by aquynh** [comment]
i dont really get this question, but we do not want to limit the number of architectures we will support.

**Comment by j123123** [comment]
OK, I see that [AArch64_AM_getFPImmFloat](https://github.com/aquynh/capstone/blob/14e3b788fb94a2864e0b57b292c9063756c83dde/arch/AArch64/AArch64AddressingModes.h#L183) function is only used in [printFPImmOperand](https://github.com/aquynh/capstone/blob/5e94dbabb53d3ff35bc5dc4993a147622e163d6c/arch/AArch64/AArch64InstPrinter.c#L1034) function, and this function uses [SStream_concat](https://github.com/aquynh/capstone/blob/5e94dbabb53d3ff35bc5dc4993a147622e163d6c/SStream.c#L39) function. SStream_concat uses [cs_vsnprintf](https://github.com/aquynh/capstone/blob/14e3b788fb94a2864e0b57b292c9063756c83dde/cs.c#L102) - vsnprintf. So I need to make my own printf? glibc have this https://www.gnu.org/software/libc/manual/html_node/Customizing-Printf.html but it is GNU extension. ISO standard C has nothing similar. I can make a lookup table for every possible 8-bit input in [AArch64_AM_getFPImmFloat](https://github.com/aquynh/capstone/blob/14e3b788fb94a2864e0b57b292c9063756c83dde/arch/AArch64/AArch64AddressingModes.h#L183) (like in https://github.com/aquynh/capstone/pull/552 ) and then just use `"%s"` but looks like you don't like lookup tables. What are your suggestions?
