### ISSUE TITLE
ARM unpredictable behavior indicator?

### ISSUE THREAD

**Issue by yifanlu** [capstone-engine/capstone#555]
It would be nice to have capstone indicate that a valid instruction could cause unpredictable behavior (as specified in the arch manual).

**Comment by aquynh** [comment]
do you have any examples?

**Comment by rpw** [comment]
See appendinx J1 of the ARM ARM:

**Comment by rpw** [comment]
Doing this in a comprehensive and complete fashion is quite an undertaking, but it would certainly be nice to have. See appendix J1 (Architectural Constraints on UNPREDICTABLE behaviors, 90 pages of description) of the ARM ARM [1] for details:

* J1.1.3: Using R15
* J1.1.4: Branching into an IT block
* J1.1.5: Branching to unaligned PC
* J1.1.6: Loads/stores to unaligned locations (ARMv7)
* [...]

@yifanlu how about a patch? ;)

[1] ARM Architecture Reference Manual ARMv8, DDI0487A.g
     http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0487a.h/index.html
