### ISSUE TITLE
z/Architecture (SystemZ) missing instructions

### ISSUE THREAD

**Issue by mainframed** [capstone-engine/capstone#563]
Based on a discussion for a radare issue (https://github.com/radare/radare2/issues/3417) a request for systemz support (aka mainframe, z/OS) was made. In researching this issue I noticed that not all instructions are supported by Capstone. All research was done using the IBM z/Architecture Reference Summary (SA22-7871-08) available [here](http://www-01.ibm.com/support/docview.wss?uid=isg29c69415c1e82603c852576700058075a).

For example, if I look at instruction "M" (page 16) with opcode 0x5c (M Multiply (64 <- 32)) and compare it to a known valid instruction (A):

Known valid instruction A (Add (32)):

```
Format: instruction_name,[instruction format],total_length,{'constant':length,[{'constant':len}|{field_name:len}...}
A,[RX-a],32,{{'5A':8},{R1:4},{X2:4},{B2:4},{D2:12}}
```

```
./test_systemz    
****************
Platform: SystemZ
Code:0x5a 0x0f 0x1f 0xff 
Disasm:
0x1000: a   %r0, 0xfff(%r15, %r1)
    op_count: 2
        operands[0].type: REG = 0
        operands[1].type: MEM
            operands[1].mem.base: REG = 1
            operands[1].mem.index: REG = 15
            operands[1].mem.disp: 0xfff
```

Known Missing Instruction M:

```
M,[RX-a],32,{{'5C':8},{R1:4},{X2:4},{B2:4},{D2:12}}
```

```
./test_systemz    
****************
Platform: SystemZ
Code:0x5c 0xa0 0x80 0x2c 
ERROR: Failed to disasm given code!
```

I believe this may be because LLVM hasn't implemented all the instructions.

It looks like this instruction isn't listed in the output of llvm-tblgen. Digging further I confirmed this instruction isn't implemented within SystemZInstrInfo.td (or any file in the llvm/lib/Target/SystemZ folder).

Based on further testing I noticed that there are 525 missing instructions from LLVM:
[Missing Instructions](https://github.com/aquynh/capstone/files/51470/not_found.txt)

**Comment by aquynh** [comment]
can you please report the missing instructions to LLVM? if they fix that upstream, Capstone can sync that and make them available.

**Comment by mainframed** [comment]
I've asked a similar question to the llvm-dev mailing list: http://lists.llvm.org/pipermail/llvm-dev/2015-December/093005.html

**Comment by bigendiansmalls** [comment]
@aquynh If I build the missing instructions into this file  https://github.com/llvm-mirror/llvm/blob/ea81d62d3775ccd81c3957c26ae9ff20f9601cbc/lib/Target/SystemZ/SystemZInstrInfo.td  -  is that all you'll need to rebuild Capstone?   If so, I can do this then we can test it from a separate branch if you like.

**Comment by aquynh** [comment]
it is best if the missing instructions are supported in LLVM, so we do not have to maintain them. can you submit to LLVM to see what they have to say?

thanks.

**Comment by XVilka** [comment]
Hi there! Any updates on this?

**Comment by aquynh** [comment]
Is this supported by LLVM yet?

**Comment by bigendiansmalls** [comment]
No - and I"m not sure it ever will be - maybe we should just close this - the goal was to have it for radare2  (which we're going a diff way with now) - but I'll leave it up to @mainframed

**Comment by mainframed** [comment]
Not that I'm aware, I reached out to the LLVM mailing list and received no reply.  I know @bigendiansmalls is working on this elsewhere, see: https://github.com/radare/radare2/commit/6d1242c18dd36d794037e4e9eaac0d44d5570d2e

**Comment by bigendiansmalls** [comment]
@aquynh It looks as if llvm has many more instructions than prior, would it be possible to incorporate the newest master build of llvm into a branch of capstone for me to test? Or, could you point me in the direction of how to do so, and I'd be happy to branch it and test.  Thank you.

**Comment by Maijin** [comment]
:?

**Comment by aquynh** [comment]
will update SystemZ & other archs when i get some free time.

**Comment by bigendiansmalls** [comment]
Thank you!!

**Comment by XVilka** [comment]
Are there any updates on this one?

**Comment by bigendiansmalls** [comment]
I haven't heard anything ... @aquynh ?
