### ISSUE TITLE
Error handling in disasm() method.

### ISSUE THREAD

**Issue by scudette** [capstone-engine/capstone#564]
When disassembling a random stream of bytes, captone quits the iterator when it hits an invalid op code. While this seems reasonable, it makes code that uses the disassembler more complex because it needs to account for this, advance the bytestream a bit and then try again.

Other disassemblers (e.g. distorm) produce a fake "db" instruction which just indicates that byte is not valid and continues disassembling. This makes calling code much simpler because if you really care about errors you could just look for "db" instruction.

Here is an example sequence that I want to display (checking for DLL injection into vad):

```
------ vad_0x7f6f0000 ------: 0x7f6f0000
  0x7f6f0000        0x0 c8000000             enter 0, 0                                      
  0x7f6f0004        0x4 ff01                 inc dword ptr [ecx]                             
  0x7f6f0006        0x6 0000                 add byte ptr [eax], al                          
  0x7f6f0008        0x8 ff                   db 0xff           <---- Invalid              
  0x7f6f0009        0x9 ee                   out dx, al                                      
  0x7f6f000a        0xa ff                   db 0xff                                         
  0x7f6f000b        0xb ee                   out dx, al                                      
  0x7f6f000c        0xc 087000               or byte ptr [eax], dh 
```

Right now I have to implement some complex code which checks if the disasm() iterator quits early and then reposition the stream, and emit a pseudo "db" instruction myself.

**Comment by aquynh** [comment]
this is called "SKIPDATA" mode, and has been available in Capstone forever: http://www.capstone-engine.org/skipdata.html

is this what you want?

**Comment by scudette** [comment]
Ah excellent - I must have missed that. It seems to do just what I want.

There seems to be a slight bug though - the fake instruction does not seem to have the operands field, so  when subsequent code tries to access it we get an infinite recursion:

```
File "/home/scudette/rekall/rekall-core/rekall/plugins/tools/disassembler.py", line 124, in operands
    for op in self.insn.operands:
  File "/home/scudette/Dev/lib/python2.7/site-packages/capstone/__init__.py", line 548, in __getattr__
    self.__gen_detail()
  File "/home/scudette/Dev/lib/python2.7/site-packages/capstone/__init__.py", line 525, in __gen_detail
    self.avx_cc, self.avx_sae, self.avx_rm, self.operands) = x86.get_arch_info(self._detail.arch.x86)
  File "/home/scudette/Dev/lib/python2.7/site-packages/capstone/__init__.py", line 548, in __getattr__
    self.__gen_detail()
  File "/home/scudette/Dev/lib/python2.7/site-packages/capstone/__init__.py", line 525, in __gen_detail
    self.avx_cc, self.avx_sae, self.avx_rm, self.operands) = x86.get_arch_info(self._detail.arch.x86)
  File "/home/scudette/Dev/lib/python2.7/site-packages/capstone/__init__.py", line 548, in __getattr__
    self.__gen_detail()
....
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

As a workaround I have to add this code:
```
if not hasattr(self.insn, "operands"): 
   return []
```

It would be ideal if the fake instruction behaved identically to other real instructions.

**Comment by aquynh** [comment]
can you post your code so i can reproduce the issue?

**Comment by scudette** [comment]
Sure. This is very simplified code. My code actually tries to match operands against rules:

```
import capstone

cs = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
cs.detail = True
cs.skipdata_setup = ("db", None, None)
cs.skipdata = True

data = 'c8000000ff010000ff'.decode("hex")

for insn in cs.disasm(data, 0):
    for op in insn.operands:
        print insn.mnemonic, op.type
```

Also the skipdata_setup above seems to have no effect (op.mnemonic is always ".byte"), although the documentation say it can be changed to "db" but this is a very minor issue.

**Comment by aquynh** [comment]
the issue with redefining the skipdata's mnemonic to "db" is now fixed in the "next" branch, please confirm.

regrading the issue with NULL operands, can you send the pull request based on your workaround above for reviewing?

thanks.
