### ISSUE TITLE
CBZ & CBNZ decoded as unconditional jumps

### ISSUE THREAD

**Issue by abenkhadra** [capstone-engine/capstone#578]
The condition flag of Thumb instructions `CBZ` & `CBNZ` instructions is always `ARM_CC_AL`. Basically, it should be `ARM_CC_EQ` and `ARM_CC_NE` respectively.

I noticed that both instructions lack setting `MCID_Predicable` in file `ARMGenInstrInfo.inc` as can be found [here](https://github.com/aquynh/capstone/blob/master/arch/ARM/ARMGenInstrInfo.inc#L5908-L5909). Adding that didn't fix the issue.

Function `AddThumbPredicate` assume that their predicate should be properly set. Therefore, it doesn't modify it. What is the best way for fixing this issue?

**Comment by aquynh** [comment]
what is the input (hexcode format) exposing this issue?

**Comment by abenkhadra** [comment]
For CBNZ consider for example `0x1bb9` and for CBZ there is `0x2bb1`. 
I'm using the latest master branch.

**Comment by aquynh** [comment]
for the record, can you please list all similar instructions having this issue?

**Comment by abenkhadra** [comment]
So far, these are the only ones. Condition code for all other branch instructions seems to be set properly in my tests. Additionally, `IT` condition codes seems correct.

**Comment by ripples-alive** [comment]
I just meet with the same issue. I'd like to know that whether you will fix it recently? @aquynh

**Comment by abenkhadra** [comment]
I raised this issue only because building a CFG requires linking basic blocks that end with conditional jumps with their direct successors. That  test can simply be done by checking the condition code of the jump instruction to be not equal to `ARM_CC_AL`.  CBZ/CBNZ are the only exception to this rule since they always have `ARM_CC_AL` set.

However, it's worth mentioning that CBZ/CBNZ themselves can not be conditional. That is, there execution doesn't depend on a condition code being set. Under this interpretation, Capstone's behavior is correct.

If we adopt the latter interpretation, then we should close this issue and the related issue #368.

**Comment by ripples-alive** [comment]
This issue does depend on the interpretation for the cc field. Though the CBZ/CBNZ themselves are not conditional, the jump is conditional. Maybe I misunderstood the meaning of cc field in capstone before. As I could not find precise document for each field in capstone, I just guessed the meaning. Hoping there will be a detailed document for capstone.
