### ISSUE TITLE
hexagon support

### ISSUE THREAD

**Issue by crowell** [capstone-engine/capstone#579]
https://twitter.com/capstone_engine/status/529641013350903808

any update on this?

**Comment by aquynh** [comment]
I have a version with Hexagon support, but did not merge it as Hexagon is so different from other archs so that it does not fit into the current setup.

Email me if you want to know more.

**Comment by rpw** [comment]
While overall the LLVM MC framework has become reasonably mature for Hexagon, the upstream HexagonDisassembler still has a number of issues decoding certain instructions, for instance instruction packets containing certain new-value instruction cannot be decoded.

I have started sending emailing the original author of that (Colin LeMahieu of QUIC), but have not received any answer yet.

**Comment by crowell** [comment]
@aquynh now that keystone can assemble for hexagon, it only makes sense that capstone should be able to disassemble it ;) 

pinging on this bug.

**Comment by aquynh** [comment]
it is a feature, not a bug :-)

**Comment by shiftre** [comment]
any update about this one ? the hexag00n project doesn't load properly in IDA and I was hoping Capstone would support it, even partially.

**Comment by apwest** [comment]
What is the current status of this?

**Comment by aquynh** [comment]
Nothing new. A big issue is that Hexagon asm syntax does not really fit
into current setup, in line with other languages.

**Comment by radare** [comment]
Its supported in r2 using the gnu disassembler, no anayzer yet. But may work as a starting point.

**Comment by apwest** [comment]
@radare can you elaborate? By 'r2' do you mean 3.0.5-rc2?

**Comment by radare** [comment]
r2 is radare2. Capstone doesnt support hexagon yet. But if u need a disassembler use radare2
