### ISSUE TITLE
lack of proper release tarball

### ISSUE THREAD

**Issue by rofl0r** [capstone-engine/capstone#582]
all of the critics in https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck (and the solution mentioned there) apply.

**Comment by aquynh** [comment]
you can download the source from http://www.capstone-engine.org/download.html, and i think some of the problems mentioned there are not true with current tarballs.

thanks.

**Comment by rofl0r** [comment]
yeah i downloaded it from there, and the dl link is
https://github.com/aquynh/capstone/archive/3.0.4.tar.gz
i.e. a github tag download.
the only point of the critics that does not apply is the "autoconf-dilemma" since this project uses cmake.

**Comment by rofl0r** [comment]
@kabeor closed without comment? the issue isn't resolved from what i can tell by looking at release tags and download page. btw, this PR here  https://github.com/htop-dev/htop/pull/878  has a universally usable github action that automatically creates a proper release tarball (including git submodules) when a release is tagged (you only gotta remove the `autoreconf -i` line).

**Comment by kabeor** [comment]
@rofl0r 
Sorry, we are cleaning legacy issues. Cause there were 400+ issues, so I have to close some of the earliest issues and see who will reply and manual reopen. Welcome back, I will continue to work on your issue here :)

**Comment by kabeor** [comment]
@rofl0r Can you PR for this issue?
