### ISSUE TITLE
No --soname of mingw

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#591]
https://github.com/radare/radare2/blob/e56be2fbd556f0a9459226636dcbe223830caa5d/shlr/capstone-patches/silent-cc-errors.patch

**Comment by aquynh** [comment]
PR for the next branch, please?

**Comment by radare** [comment]
will do when i have some time, is anyone having problems crosscompiling capstone for mingw?

i just filled the issue for reference. will review later in detail

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
