### ISSUE TITLE
wrong disassembly of cmp with sign-extension (intel x86 32bit)

### ISSUE THREAD

**Issue by orenmn** [capstone-engine/capstone#614]
for intel x86 32bit, capstone disassembles '\x83\xfa\xff' as:
`cmp edx, 0xff`
while it should be:
`cmp edx, 0xffffffff`

**Comment by aquynh** [comment]
can you try with the "next" branch, which will be released in near future as v4.0?

**Comment by orenmn** [comment]
i am sorry... i have no setup at all on this computer and no time to make one.
to verify this bug i have just patched the test.exe to print the disassembly of this instruction. i will happily do the same for v4.0 if i can put my hands on the test.exe of v4.0...

**Comment by aquynh** [comment]
this bug was fixed in the "next" branch. you should use that instead of "master", as i am going to merge that to "master" soon, after some bugfixes.

**Comment by orenmn** [comment]
great! 
thanks, and sorry for the report

**Comment by koemeet** [comment]
@aquynh Was the fix for this merged in master or do we need to use the `next` branch 😄 ?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
