### ISSUE TITLE
How do I install Core Engine on Windows?

### ISSUE THREAD

**Issue by AzadefiaS** [capstone-engine/capstone#616]
They write everywhere it need to be installed to use the Bindings (i need the java bindings) 
but nowhere how to install it. After download i just got a File with no Informations what to do with it.
Im new with this, can someone help please?

**Comment by aquynh** [comment]
can you try to put capstone.dll in the same directory with capstone.jar, and see if it works?

**Comment by AzadefiaS** [comment]
I am unsing Eclipse. After trying that, and build path, i get a red exclamation mark and nothing works anymore.

**Comment by aquynh** [comment]
this question is not specific to Capstone. it should be "how to use Eclipse with a binding with DLL". hopefully somebody will chime in to help you.

**Comment by AzadefiaS** [comment]
I didnt know that "using the binding" is similar with "install engine engore" ...like i said im new with that

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
