### ISSUE TITLE
The __getattr__ function of CsInsn returns None instead of raising an AttributeError exception when an attribute does not exist

### ISSUE THREAD

**Issue by SeanHeelan** [capstone-engine/capstone#634]
This behaviour can lead to some fairly confusing issues if one mistypes an attribute name or mistakes an attribute for a function. Unless there's a really good reason, it would seem better to conform to normal behaviour and raise an exception in these cases.

**Comment by aquynh** [comment]
What exact exception do you recommend?

**Comment by SeanHeelan** [comment]
Something like the above? Is there some place for Python binding unittests btw? If so, let me know and I'll add the one I created locally.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
