### ISSUE TITLE
Comparing capstone x86 output to another disassembler

### ISSUE THREAD

**Issue by Zoxc** [capstone-engine/capstone#635]
I wrote a partial x86 disassembler and I compared the output of it with the output of capstone.
I used revision https://github.com/aquynh/capstone/commit/f3b886315bd53b37d0008ff83248659eefb54ae5 to do this.

[Comparison output](https://github.com/aquynh/capstone/files/221401/capstone.txt) (`c` is capstone and `m` is my library)

One thing of stylistic note is that I leave out pointer sizes for `nop` while capstone does not (which seems slightly inconsistent with it being missing from `lea`).

```
on 0f1f06
  c: nop dword ptr [rsi]
  m: nop [rsi]
```

**Comment by radare** [comment]
This is what r2 does by enabling an option. Also, the second output is incomplete because doesnt specifies the size of the access operation. 

I dont get whats the purpose of this issue. Is this  a question? A feature request? A proposal? Btw udis was already showing the output like u do.

**Comment by Zoxc** [comment]
@radare With the exception of the `nop` instructions, it is a list of instructions capstone doesn't properly disassemble.

**Comment by radare** [comment]
Thanks for clarification!

**Comment by aquynh** [comment]
this is very cool, thanks!

few things:

- is this against "master" or "next" branch?
- would you mind sending a PR to include your scripts in Capstone, so we can repeat this test in the future?

**Comment by Zoxc** [comment]
It was against the `next` branch.

I won't make a PR to capstone, but I will put the test in a repository so you can repeat it.

**Comment by aquynh** [comment]
please do confirm that all of the output of "your disassembler" is correct. i took a quick look, and many of them are actually incorrect, for example:

```
on f022561d
  c: invalid
  m: lock and dl, byte ptr [rsi + 0x1d]
```

Capstone is correct here.

**Comment by Zoxc** [comment]
I misread the manual regarding the lock prefix so I fixed that. I also removed the `nop` and `xchg` differences which weren't meaningful.

[Here is the updated comparison output](https://github.com/aquynh/capstone/files/223931/capstone.txt)

**Comment by aquynh** [comment]
thanks for the update.

Capstone interprets 87c0 as "xchg eax, eax", and i think that is correct.

**Comment by 10110111** [comment]
FWIW, both ndisasm and objdump say (up to `BYTE PTR` presence):

    F0 22 56 1D   lock and dl,[rsi+0x1d]

Only capstone refuses to disassemble this instruction.

**Comment by aquynh** [comment]
Because they are all wrong.

**Comment by Zoxc** [comment]
I've added this test to Travis, https://travis-ci.org/AveryOS/avery/jobs/125456610

**Comment by aquynh** [comment]
this is very nice, thank you @Zoxc.

will address these issues asap.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
