### ISSUE TITLE
VRCPSS has empty list of groups

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#639]
`VRCPSS` is an AVX instruction, but Capstone reports it with empty list of groups. Example code:

```
C5 C2 53 1C 24 vrcpss xmm3,xmm7, [esp]
```

**Comment by aquynh** [comment]
would you mind sending a PR to fix this issue?

it is simple enough: you just need to put the AVX group into the structure of this instruction at https://github.com/aquynh/capstone/blob/next/arch/X86/X86MappingInsn.inc.

thanks.

**Comment by 10110111** [comment]
I'll try to do this, but I see three entries corresponding to this instruction there: `X86_VRCPSS{m,m_Int,r}`. What do these suffixes mean?

**Comment by 10110111** [comment]
Also, what to do with instructions which, depending on encoding, are from AVX or AVX512, like e.g. `VSQRTSS` with VEX vs EVEX encoding? Does Capstone differentiate between them?

**Comment by aquynh** [comment]
"r" means "register", and "m" means memory. this indicates the operand types of the instruction.

can you give some examples on these encodings? (with hexcode as input)

thanks.

**Comment by 10110111** [comment]
> "r" means "register", and "m" means memory.
But what does `m_Int` mean? Could you give an example of instruction code with such an operand?

> can you give some examples on these encodings?

Example of VEX-encoded `vsqrtss`:

    C5 EA 51 CB   vsqrtss xmm1,xmm2,xmm3

And EVEX-encoded (fails to be disassembled by Capstone currently):

    62 F1 6E 09 51 CB   vsqrtss xmm1{k1},xmm2,xmm3

**Comment by 10110111** [comment]
Actually I've now noticed that the EVEX-encoded versions are already reported with AVX-512 group. It's only the VEX-encoded versions which have no group listed.

My question about `m_Int` still remains though. What does this suffix mean? Does it have anything to do with Intel syntax?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
