### ISSUE TITLE
No way of knowing where opcode ends

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#640]
Currently the interface for x86 opcode is `uint8_t opcode[4]`, where `00` might mean that the byte is unused. But there are legal opcodes which do include trailing zero byte, e.g. `sldt`: `0F 00 /0`. So when such instruction is encountered, it'll be hard to understand whether opcode is `0F` or `00` unless we implement a mini-disassembler on top of Capstone.

Similarly, we can't easily know whether a ModRM byte is present and zero or it's absent, unless we parse the instruction ourselves.

Similarly for SIB: we must parse ModRM to understand whether SIB is present. But decoding instructions is the task for a disassembler.

**Comment by 10110111** [comment]
BTW, the interface for `opcode` currently is even insufficient to contain some opcodes, e.g.

    00100071   62 F1 74 8D 59 BC 24 40 12 00 00   vmulps xmm7 {k5} {z}, xmm1, xmmword ptr [esp + 0x1240]

This instruction has opcode `62 F1 74 8D 59`. Capstone correctly puts `BC` into ModRM, but is unable to give the whole opcode (its last byte doesn't fit).

**Comment by aquynh** [comment]
the Intel manual says one instruction has only up to 4 bytes of opcode, and we are following that.
what you are saying (5 bytes) is something else.

**Comment by 10110111** [comment]
Well, basically it's due to the scheme Capstone is following, where EVEX and VEX prefixes are included in opcode. If you follow Intel manual, then prefix is not part of opcode.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
