### ISSUE TITLE
Some cases of AVX instructions fail to be disassembled

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#644]
This instruction fails to be disassembled by Capstone:

```
62 F1 74 9D 59 FC   vmulps zmm7{k5}{z},zmm1,zmm4,{rn-sae}
```

But, interestingly, if I change rounding mode, it does get disassembled, although the mode is wrong (here I present the correct disassembly by objdump):

```
62 F1 74 FD 59 FC   vmulps zmm7{k5}{z},zmm1,zmm4,{rz-sae}
```

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
