### ISSUE TITLE
Extra space after register name when no opmask is specified but EVEX is used

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#645]
See the extra space after `zmm7` in the following code:

```
62 F1 74 48 58 FC   vaddps zmm7 , zmm1, zmm4
```

Looks like it's supposed to be the space before something like `{k1}`, but nothing similar had to be added, while the space still hasn't been stripped.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
