### ISSUE TITLE
Missing RFLAGS for X86 architecture

### ISSUE THREAD

**Issue by lucasg** [capstone-engine/capstone#646]
While enumerating the various naming conventions for general purpose registers (e.g. `X86_REG_AX`, `X86_REG_EAX`, `X86_REG_RAX`) there is only one flags register publicly defined : `X86_REG_EFLAGS`.

Moreover, it's defined as a 32-bit long register on `CS_MODE_32` and 64-bit long on `CS_MODE_64`, while the convention (well the Windbg convention anyway) always define `EFLAGS` as a 32-bit long register, whatever the running arch.

Wouldn't be better to define `X86_REG_FLAGS`, `X86_REG_EFLAGS` and `X86_REG_RFLAGS` that same way general purpose register are defined ?

Cheers,

**Comment by aquynh** [comment]
currently we treat X86_REG_EFLAGS as 64bit for 64bit mode, 32bit for 32bit mode, and 16bit for 16bit mode, depending on `mode` you use for `cs_open()`.

perhaps we can have alias `X86_REG_FLAGS = X86_REG_FLAGS`, `X86_REG_FLAGS = X86_REG_FLAGS` to make it more clear?

**Comment by lucasg** [comment]
That would be a solution, yes. However if in the future you want to expose register size as an API (like `cs_reg_name`) you might as well document special case such as FLAGS register.

**Comment by aquynh** [comment]
perhaps it is better to just have separate enum for FLAGS, EFLAGS & RFLAGS registers

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
