### ISSUE TITLE
Only VEX prefix present in opcode bytes, but not actual opcode

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#647]
The following instruction, disassembled in 64 bit mode, is reported as having opcode `C4 63 FD 00`, while the actual opcode is `69`, which is for some reason omitted:

```
C4 63 FD 69 0C 10 75   vfmaddpd ymm9, ymm0, ymm7, ymmword ptr [rax + rdx]
```

**Comment by 10110111** [comment]
The same happens for an instruction with two-byte VEX prefix:

    C5 C2 53 1C 24   vrcpss xmm3, xmm7, dword ptr [esp]

Opcode is reported as `C5 C2 00 00`, while actual opcode begins with `53`, which isn't included.

**Comment by 10110111** [comment]
Hmm, in fact I'm yet to find any VEX-encoded instruction where this doesn't happen. It appears to happen with _all_ VEX-encoded instructions.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
