### ISSUE TITLE
Legacy SIMD prefixes F2 and F3 are not listed in the list of prefixes

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#651]
See a bunch of SSE instructions:

```
F3: 0F 53. 6C 24, 08   rcpss xmm5, [esp+8]
F2: 0F 5A. DE          cvtsd2ss xmm3, xmm6
F3: 0F 5A. DE          cvtss2sd xmm3, xmm6
F3: 0F 51. CC          sqrtss xmm1, xmm4
```

`F2` and `F3` prefixes are not reported in the list of prefixes. This doesn't happen with `66` though, e.g.

```
66: 0F 10. 05, 000011F3   movupd xmm0, [rip+0x11f3]
```

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
