### ISSUE TITLE
endianness ignored in sparc

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#652]

**Comment by jpenalbae** [comment]
Never heard about sparc being bi-endian. Anyway looking at the documentation I found that it is, but only for load/store operations, so I guess its safe for capstone to keep ignoring endianness.

![bi-endian](https://cloud.githubusercontent.com/assets/8380459/14826561/b2a5fb98-0bde-11e6-8b40-8c9963504593.png)

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
