### ISSUE TITLE
A question: on ARM mem.disp field reused for alignment

### ISSUE THREAD

**Issue by mkravchik** [capstone-engine/capstone#670]
Hi,

I just discovered that in capstone.arm.ArmOpMem the disp field is sometimes used for immediate offset and sometimes for alignment. For example:
Used as alignment:
vst1.64 {d12, d13, d14, d15}, [r4:0x80]
    Number of operands: 5
        operands[0].type: REG = d12
        operands[1].type: REG = d13
        operands[2].type: REG = d14
        operands[3].type: REG = d15
        operands[4].type: MEM
            operands[4].mem.base: REG = r4
            operands[4].mem.disp: 0x80  
Used as offset:
ldr r1, [pc, #0x100]
    Number of operands: 2
        operands[0].type: REG = r1
        operands[1].type: MEM
            operands[1].mem.base: REG = pc
            operands[1].mem.disp: 0x100  
Is this the expected behaviour? Is there any way to know what disp means besides learning it hard way for each instruction?
In my code I was assuming that the meaning of disp is the same regardless of the instruction and was adding it to the base. Looks I was wrong.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
