### ISSUE TITLE
Extend detailed api to hook between IR and TR

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#672]
The idea of this issue is to discuss the possibility to extend capstone's API to be able to inject a hook in the middle of the disassembler loop in order to be able to manipulate the IR to change the text representation in the disassembly

This is useful when you want to create a higher level disassembler and it is required to change a specific expression by another one ([ebp+4]  -> arg_4) without having to mess with the string parsing.

Also, this internal API requires some more information than the one we already have in the detailed struct because it requires to change the "AST" form of the instruction and it must be able to set specific strings instead of just register names and numbers.

**Comment by aquynh** [comment]
Can you propose the API here?

**Comment by radare** [comment]
no, because it requires previous discussion and changes on the internal representation so it will probably need several iterations of brainstorming

**Comment by stevemk14ebr** [comment]
This sounds like something that should be implemented by the project using capstone and not capstone itself. It's capstones job to give you correct disassembly, if you want to rename certain opcodes to pseudonames i think thats outside of its responsibilities. Imho.

**Comment by ibabushkin** [comment]
If I understood the proposal correctly, what is actually suggested is a way to hook the disassembling API. In which case I'd suggest adding a modified function that allows for hooking alongside the already existing ones, to remain compatible with existing code and bindings. However, internal representation needs more discussion. What capabilities are needed exactly @radare?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
