### ISSUE TITLE
pushal/popal mnemonics are inconsistent with all other instructions and not understood by most assemblers

### ISSUE THREAD

**Issue by 10110111** [capstone-engine/capstone#674]
Such mnemonics as `pushal` and `popal` are not supported by any Intel-syntax assembler I tried: nasm, yasm, fasm, gas (I'd also bet that masm, tasm and wasm don't support them too). Only gas in AT&T mode understands it (and doesn't understand `pushad`/`popad`).
Also, this is inconsistent with all the other instructions working with dwords: be it `popfd`, `pshufd` or anything like that.

This is a request to use `pushad` and `popad` mnemonics when in Intel syntax mode.

(Ideally, the `enum x86_insn` identifiers should also be changed for consistency, but this breaks API, so I'm not sure whether capstone would be willing to do this).

**Comment by aquynh** [comment]
yes, we can fix this in the "next" branch. would you mind sending a PR for this?

**Comment by aquynh** [comment]
perhaps the best solution is just creating some new alias instructions, for example `X86_INS_PUSHAD = X86_INS_PUSHAL`, then we dont break anything. is that OK for you?

**Comment by 10110111** [comment]
That's OK. Will do both in a PR.

**Comment by 10110111** [comment]
For some strange reason, even these commands don't fix the disassembly:
````
cd capstone-source
grep pushal -lr . | while read file; do sed 's@pushal@pushad@g' -i $file; done
grep popal -lr . | while read file; do sed 's@popal@popad@g' -i $file; done
````
What could this mean? Does this indicate some problem in non-string-based instruction description?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
