### ISSUE TITLE
Carry is not taken into account in ARM instructions

### ISSUE THREAD

**Issue by vnd** [capstone-engine/capstone#689]
Some ARM instructions depend on a carry bit which is not part of instruction itself, for example here's an excerpt from a TEQ instruction algorithm (ARMv7):
(shifted, carry) = Shift_C(R[m], shift_t, shift_n, **APSR.C**);

However capstone seems to always assume that carry is zero, for example:
0xe31a080f is decoded as "teq sl, #0x2f0000"

It's probably better to return two decoding variants, with carry bit assumed to be 0 and 1.

**Comment by mossberg** [comment]
+1

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
