### ISSUE TITLE
LSR is decoded as MOV in ARMv7

### ISSUE THREAD

**Issue by vnd** [capstone-engine/capstone#690]
0xe1a01230 ("lsr r1, r0, r2") is decoded as MOV instruction with three register operands, without any shift_\* properties set.

Although in general reduction of shift instructions into MOV with appropriate shift fields set does make sense, in this particular case it seems to be a bug since apparently the only way to know shift type is using the instruction mnemonic.

**Comment by aquynh** [comment]
Can you send PRs for these issues?

**Comment by vnd** [comment]
Not in the nearest month or two unfortunately. I'll put in my "backlog" and try to get back to it in the future though..

**Comment by ibabushkin** [comment]
If help is needed quickly, I can look into it. A minimal example would be great in such a case :).

**Comment by vnd** [comment]
It's not an urgent issue for me. Not sure what do you mean by minimal example though: incorrectly decoded instruction is given (0xe1a01230), do you mean some decoding code example?

**Comment by ibabushkin** [comment]
I was referring to a general description of the issue, but if it's just this single instruction that's causing issues, I can look into it already.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
