### ISSUE TITLE
x86 ud2b

### ISSUE THREAD

**Issue by mrexodia** [capstone-engine/capstone#691]
The instruction `0F B9` is disassembled as `ud2b` but this should be `ud1` https://sourceware.org/ml/binutils/2010-08/msg00081.html https://www.onlinedisassembler.com/odaweb/

**Comment by mrexodia** [comment]
Another instruction (undocumented) is `0F FF` which is `ud0`. https://groups.google.com/forum/#!topic/alt.os.development/_rS4L0fnqGE

**Comment by 10110111** [comment]
See also [this Linux patch](https://patchwork.kernel.org/patch/9631663/), namely this part:
```
+/*
+ * Since some emulators terminate on UD2, we cannot use it for WARN.
+ * Since various instruction decoders disagree on the length of UD1,
+ * we cannot use it either. So use UD0 for WARN.
+ *
+ * (binutils knows about "ud1" but {en,de}codes it as 2 bytes, whereas
+ *  our kernel decoder thinks it takes a ModRM byte, which seems consistent
+ *  with various things like the Intel SDM instruction encoding rules)
+ */
+
+#define ASM_UD0		".byte 0x0f, 0xff"
+#define ASM_UD1		".byte 0x0f, 0xb9" /* + ModRM */
+#define ASM_UD2		".byte 0x0f, 0x0b"
```
The point about ModRM is supported by my experimental check on Core i7-4765T: e.g. putting `0f b9` at the end of a code page leads to `SIGSEGV` with `SEGV_MAPERR` with error address equal to the first byte after the page. Moving the instruction one byte back and putting a ModRM byte of e.g. `c0` or `00` results in the expected `SIGILL`. But putting the third (ModRM) byte of `41` results in `SIGSEGV:SEGV_MAPERR` again — until you move the instruction one more byte back to allow for `disp8`, after which it'll result in the expected `SIGILL` again.

**Comment by aquynh** [comment]
i just pushed a commit to add UD0 instruction.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
