### ISSUE TITLE
movss dword ptr [rax + 0x10], xmm0 has no memory write operands

### ISSUE THREAD

**Issue by jrmuizel** [capstone-engine/capstone#693]
The following program reproduces the problem

from capstone import *
from capstone.x86 import *

md = Cs(CS_ARCH_X86, CS_MODE_64)
md.detail = True
CODE = (bytes([0xf3, 0x0f,0x11,0x40,0x10]))
i = list(md.disasm(CODE, 0x1000))[0]
print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
assert i.operands[0].type == X86_OP_MEM
assert i.operands[0].access & CS_AC_WRITE

**Comment by aquynh** [comment]
fixed in the "next" branch with this commit https://github.com/aquynh/capstone/commit/c1a16fa0bfa7d09773629914de9a8a298c3aee5e, thanks.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
