### ISSUE TITLE
Unable to disassemble 80 00 00  and 82 10 00

### ISSUE THREAD

**Issue by sparktrend** [capstone-engine/capstone#706]
from capstone import *

```
md = Cs(CS_ARCH_X86, UC_MODE_32)
asm = md.disasm(str('\x82\x00\x00'), 0)
for a in asm:
    print '%s %s' % (a.mnemonic, a.op_str)
```

Two add instructions 82 00 00 and 82 10 00 are not disassembled in capstone. The above should print out results. I tried with Xed, which works (see below).

$ xed -d **820000**
820000
ICLASS: ADD   CATEGORY: BINARY   EXTENSION: BASE  IFORM: ADD_MEMb_IMMb_82r0   ISA_SET: I86
SHORT: **add byte ptr [eax], 0x0**
$ xed -d **821000**
821000
ICLASS: ADC   CATEGORY: BINARY   EXTENSION: BASE  IFORM: ADC_MEMb_IMMb_82r2   ISA_SET: I86
SHORT: **adc byte ptr [eax], 0x0**

Any thoughts?

**Comment by sparktrend** [comment]
xor operation 82 30 00 also doesn't work.

$ xed -d **823000**
823000
ICLASS: XOR   CATEGORY: LOGICAL   EXTENSION: BASE  IFORM: XOR_MEMb_IMMb_82r6   ISA_SET: I86
SHORT: **xor byte ptr [eax], 0x0**

**Comment by sparktrend** [comment]
I'm using capstone 3.0.5.

**Comment by aquynh** [comment]
you can switch to use the "next" branch, which can handle these code.

**Comment by sparktrend** [comment]
Any estimate on next branch (4.0) release?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
