### ISSUE TITLE
Condition code missing from x86

### ISSUE THREAD

**Issue by jnippula** [capstone-engine/capstone#707]
There is condition code info (arm_cc) in ARM arch, but it is missing from x86 arch.

**Comment by aquynh** [comment]
Please always provide the input (hexcode) for further discussion.

**Comment by jnippula** [comment]
Example: Condition code for 'je' instraction:
400306:       74 05                   je     40030d <_init+0x15>

Could have information X86_CC_EQ defined in table:
typedef enum x86_cc {
    X86_CC_INVALID = 0,
    X86_CC_EQ,            // Equal                      Equal
    ...

**Comment by aquynh** [comment]
this is interesting, but i am not sure if this is something that other people (besides you) want and need for X86.

lets see what people think about this idea.

**Comment by jnippula** [comment]
Ok. I don't want to fork my own branch from capstone due to maintenance
work, but I have a workaround for my own code always.

**Comment by ismaell** [comment]
It's a desirable feature, it would allow for simpler analysis of control flow, in fact IMO it should be generic, so that you can just check the instruction group and condition code and take a decision.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
