### ISSUE TITLE
Implicit Memory R/W

### ISSUE THREAD

**Issue by fvrmatteo** [capstone-engine/capstone#709]
Instructions like PUSH or POP write/read from the stack (which is a memory location). Capstone is not reporting the accessed memory location in these cases, I think it would be useful to add them to the "detail" structure, just like already done with "regs_write" and "regs_read". Arrays called "mem_read" and "mem_write" would be useful.

If it's something others need I can try to work on it or help someone implementing it.

**Comment by aquynh** [comment]
why we need array, when only a variable is enough?

**Comment by fvrmatteo** [comment]
Yeah :D if we are 100% there are no esoteric instructions implicitly modifying more than one memory location. Anyway I think this is necessary to make Capstone really complete, also it should't be difficult at all, I implemented a wrapper for the 'detail->x86' structure to add the memory location.

**Comment by fvrmatteo** [comment]
OK, I completely forgot about instructions like: PUSHAD or POPAD. These instructions are actually writing and reading many memory locations. So an array is needed if we want to track implicit memory locations accesses.

**Comment by KevinPoole** [comment]
> Yeah :D if we are 100% there are no esoteric instructions implicitly modifying more than one memory location. Anyway I think this is necessary to make Capstone really complete, also it should't be difficult at all, I implemented a wrapper for the 'detail->x86' structure to add the memory location.

Is the wrapper that you wrote available somewhere for reference? This is a feature that I would like to see as well (Implicit Memory R/W) as I am trying to use capstone to add a taint tracking feature to an AFL-unicorn emulation environment - without the implicit memory R/W I will need to manually determine all of the places that this happens, and manage these accesses separately.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
