### ISSUE TITLE
scale is set incorrectly for strh (ARMv7)

### ISSUE THREAD

**Issue by vnd** [capstone-engine/capstone#710]
0x118c30b6 (strhne r3, [ip, r6]) has scale set to -1 for its second operand:

```
$ ./decode 0x118c30b6
118c30b6
0x0:    strhne r3, [ip, r6]!
subtracted for op 0: 0
subtracted for op 1: 1
base  for op 1: 78
index for op 1: 72
scale for op 1: -1
disp  for op 1: 0
        This instruction belongs to groups: 147 
```

Output produced by: https://gist.github.com/vnd/9b1b358c83959b229d6c8a66cfb7709d

What is also very strange, exclamation mark in op_str (meaning pre-indexed form) is also set incorrectly. However it happens only when using capstone directly, when decoding through Rust wrapper it magically disappears.

subtracted is also apparently set incorrectly, but there's already a issue #695 for that.

**Comment by vnd** [comment]
scale/subtracted is fixed in the next branch, should I close or wait until it's merged into master?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
