### ISSUE TITLE
no intel itanium support

### ISSUE THREAD

**Issue by crowell** [capstone-engine/capstone#714]
there was a period of time where llvm supported ia64, getting this in capstone would be great!

**Comment by aquynh** [comment]
i think we can count the number of people who are going to need this?

**Comment by aquynh** [comment]
You can look at simpler architecture such as m68k & ethereum, to see how to
add a new one.

It depends on how complicated the instruction encoding is.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
