### ISSUE TITLE
Add ability to disable negative numbers in mnemonics

### ISSUE THREAD

**Issue by j123123** [capstone-engine/capstone#716]
when using rasm2 with capstone, I get this

```
$ rasm2 -a x86 -s att -b 64 -d '48 c7 c0 ff ff ff 8f'
movq $-0x70000001, %rax
$ rasm2 -a x86 -s att -b 64 -d '48 c7 c0 ff ff ff ff'
movq $-1, %rax
```

but what if I want to get unsigned value, without this negation stuff? Like when I using udis:

```
$ rasm2 -a x86.udis -s att -b 64 -d '48 c7 c0 ff ff ff 8f'
mov $0xffffffff8fffffff, %rax
$ rasm2 -a x86.udis -s att -b 64 -d '48 c7 c0 ff ff ff ff'
mov $0xffffffffffffffff, %rax
```

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
