### ISSUE TITLE
Registers read/written empty

### ISSUE THREAD

**Issue by newgre** [capstone-engine/capstone#732]
Hey,

when disassembling either of CMC, CLC, STC, CLD the resulting set of read or written registers is empty, even though it should contain EFLAGS, or better yet, CF and DF, resp.

**Comment by aquynh** [comment]
pull req to fix this is welcome.

you just need to add the missing info to https://github.com/aquynh/capstone/blob/next/arch/X86/X86MappingInsnOp.inc & https://github.com/aquynh/capstone/blob/next/arch/X86/X86MappingInsnOp_reduce.inc. format of these files are simple & self-contained.

**Comment by newgre** [comment]
Why not fix the .td files and contribute upstream? It doesn't seem to make much sense to fix the generated files here.

**Comment by aquynh** [comment]
because upstream does not have these info.

**Comment by newgre** [comment]
Yes, that's what I'm saying. Why fix a generated file locally if you can contribute that fix upstream and simply regenerate the files?

A similar error occurs for XADD: it doesn't list FLAGS register as being written to.

**Comment by aquynh** [comment]
you can see that Capstone has some info that LLVM does not have, like those bits of EFLAGS. example:

```
{       /* X86_AAS, X86_INS_AAS: aas */
        X86_EFLAGS_UNDEFINED_OF | X86_EFLAGS_UNDEFINED_SF | X86_EFLAGS_UNDEFINED_ZF | X86_EFLAGS_MODIFY_AF | X86_EFLAGS_UNDEFINED_PF | X86_EFLAGS_MODIFY_CF,
        { 0 }
},
```

i dont think LLVM would accept these changes, as their focus is different.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
