### ISSUE TITLE
ARM LDR incorrect writeback

### ISSUE THREAD

**Issue by offlinemark** [capstone-engine/capstone#740]
Hi, I believe the `writeback` flag is being set incorrectly here for post indexed LDR instructions.

```
>>> from capstone import *
>>> from capstone.arm import *
>>> c = Cs(CS_ARCH_ARM, CS_MODE_ARM)
>>> c.detail = True
>>> c.disasm('\x02\x10\x9d\xe6', 0x1000)
<generator object disasm at 0x7f741dfb9730>
>>> ldr = next(c.disasm('\x02\x10\x9d\xe6', 0x1000))
>>> print ldr.mnemonic, ldr.op_str
ldr r1, [sp], r2
>>> print ldr.writeback
False
```

![image](https://cloud.githubusercontent.com/assets/2467355/17230031/4269a994-54e8-11e6-8e2c-cf79e6a62a2f.png)

**Comment by aquynh** [comment]
fixed now in the "next" branch with commit https://github.com/aquynh/capstone/commit/483e101ff70ba1e6a6bf7df535747567ed6c5f5e. please confirm, thanks.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
