### ISSUE TITLE
ARM LSR incorrect insn_name()

### ISSUE THREAD

**Issue by offlinemark** [capstone-engine/capstone#743]
Hi, it looks like `insn_name()` returns 'mov' instead of 'lsr' for `lsr r0, r0, r2`.

```
>>> from capstone import *
>>> from capstone.arm import *
>>> c = Cs(CS_ARCH_ARM, CS_MODE_ARM)
>>> lsr = c.disasm('\x30\x02\xa0\xe1', 0x1000)
>>> lsr = next(lsr)
>>> lsr.insn_name()
u'mov'
```

**Comment by aquynh** [comment]
can you try this with the "next" branch?

**Comment by vnd** [comment]
Seems to be the same as #690

**Comment by aquynh** [comment]
this issue does not exist in the "next" branch.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
