### ISSUE TITLE
ARM64 NEGS instruction insn_name() error

### ISSUE THREAD

**Issue by redd0glee** [capstone-engine/capstone#752]
Hi, It seems that  insn_name() of 'NEGS' instruction is wrong

Capstone version: 3.0.4
Python 3.5.1

 File "~~~/virtualenv/lib/python3.5/site-packages/capstone/**init**.py", line 580, in insn_name
    return _cs.cs_insn_name(self._cs.csh, self.id).decode('ascii')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by aquynh** [comment]
How to reproduce this? Please provide the input (in hexcode format) for
this issue.

**Comment by redd0glee** [comment]
>>> [print("%s %s" %(i.**mnemonic** , i.op_str)) for i in cs.disasm(b'\xea\x03\x1c\xeb',0)]
negs x10, x28
[None]

>>> [print("%s %s" %(i.**insn_name()** , i.op_str)) for i in cs.disasm(b'\xea\x03\x1c\xeb',0)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "~~~/virtualenv/lib/python3.5/site-packages/capstone/__init__.py", line 580, in insn_name
    return _cs.cs_insn_name(self._cs.csh, self.id).decode('ascii')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by aquynh** [comment]
i tried, but did not find any problem. can you post the full code?

if you dont know how to format the code properly, you can paste it to https://gist.github.com/, and post the link here.

**Comment by redd0glee** [comment]
https://gist.github.com/redd0glee/643f1dc4cc0ab1f2c26e32bf94041c98

**Comment by aquynh** [comment]
Are you using master, or next branch?

**Comment by redd0glee** [comment]
I installed capstone using pip

**Comment by aquynh** [comment]
fixed in the "next" branch, please confirm.

**Comment by aquynh** [comment]
when you get the code from "next", be sure to reinstall the core & bindings, like this:

```
$ ./make.sh
$ sudo ./make.sh install
$ cd bindings/python
$ sudo make install
```

**Comment by redd0glee** [comment]
It works

**Comment by kfirstri** [comment]
Any plan to release this fix? it's been more than 2 years.. Alpha release will be cool as well

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
