### ISSUE TITLE
ARM RRX shift operand value should be 1

### ISSUE THREAD

**Issue by offlinemark** [capstone-engine/capstone#758]
Hi, when I disassemble an ARM instruction that uses an rrx shifted operand, the `value` attribute of the `shift` is 0. I'd like to propose that this should be 1 instead to more closely match the semantics described in the manual.

```
>>> from capstone import *
>>> from capstone.arm import *
>>> c = Cs(CS_ARCH_ARM, CS_MODE_ARM)
>>> c.detail = 1
>>> d = c.disasm('\x61\x30\x82\xe0', 0x1000)
>>> d = d.next()
>>> d.mnemonic, d.op_str
(u'add', u'r3, r2, r1, rrx')
>>> d.operands[2].shift.type == ARM_SFT_RRX
True
>>> d.operands[2].shift.value
0L
>>>
```

The ARMv7-A manual A8-292 asserts in this pseudocode that the shift amount of an RRX shift must be 1, so I think it makes sense for the `value` attribute to be set to 1 also.

![image](https://cloud.githubusercontent.com/assets/2467355/18096613/d0e1689a-6ea8-11e6-9b27-61ffc24e6580.png)

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
