### ISSUE TITLE
arm64 Decode [0x8b 0x51 0x82 0x12] error?

### ISSUE THREAD

**Issue by hulovebin** [capstone-engine/capstone#782]
---

Platform: ARM-64
Code: 0x8b 0x51 0x82 0x12 0x15 0xfb 0xa8 0x52
Disasm:

//**********************
//Is there a bug???
0x4584: movn    w11, #0x128c
        op_count: 2
                operands[0].type: REG = w11
                operands[1].type: IMM = 0x128c

//--------------------------------------
ida ：
8b 51 82 12    mov    w11, #0xffffed73

//in DecodeMoveImmInstruction ...case AArch64_MOVNWi:
if (!shift)
{
    imm = ~imm;
}

**Comment by aquynh** [comment]
is this on "master" or "next" branch?

**Comment by hulovebin** [comment]
"master" and "next" branch

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
