### ISSUE TITLE
AArch64: type of direct branch operands is treated as immediate

### ISSUE THREAD

**Issue by uraj** [capstone-engine/capstone#795]
I encountered this when using the python binding of 3.0.4. It seems that the label of a direct branch in AArch64 is of type CS_OP_IMM. Doesn't CS_OP_MEM make more sense? Since the operand is actually the memory address of the next instruction to be executed. In the current implementation, op_str of a branch instruction would be something like "#0xabcdef", which is not really correct (the '#' shouldn't be there). The issue also applies to instructions like adrp.

The hexcode of the instruction is [0x61, 0x2a, 0x0, 0x94] for this case

**Comment by aquynh** [comment]
Could you provide the input hexcode of this case?

**Comment by uraj** [comment]
The hexcode is ['0x61', '0x2a', '0x0', '0x94']

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
