### ISSUE TITLE
Warning while compiling with -pedantic

### ISSUE THREAD

**Issue by hziSot** [capstone-engine/capstone#802]
/usr/include/capstone/capstone.h:97:23: warning: enumerator value for 'CS_MODE_BIG_ENDIAN' is not an integer constant expression [-Wpedantic]
  CS_MODE_BIG_ENDIAN = 1 << 31, // big-endian mode
There was the bug in gcc 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71803
which was closed as RESOLVED INVALID since:
"1 << 31 is not a constant integral expression in C99/C90/C11 since you are overflowing the 1 to the sign bit."

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
