### ISSUE TITLE
[PowerPC] Decoding of SC instruction ignores restrictions on LEV field

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#808]
The `LEV` field (bits 20-26) of an `SC` instruction must be either 0 or 1. All other values are reserved. Here's an example that should be invalid:

Bytes: `47 17 63 86`
Capstone Output: `sc 0x1c`

This issue appears for both Capstone 3.0.4 and the next branch.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
