### ISSUE TITLE
capstone & captsone-windows are broken on windows7

### ISSUE THREAD

**Issue by brupelo** [capstone-engine/capstone#811]
I've just tried both choices, either `pip install capstone`  and `pip install capstone-windows`, both of them will give me this:

    >>> import capstone
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "d:\virtual_envs\py351\lib\site-packages\capstone\__init__.py", line 230, in <module>
        raise ImportError("ERROR: fail to load the dynamic library.")
    ImportError: ERROR: fail to load the dynamic library.

What's the matter here? 

Specs:
 - `Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32`
 - `Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32`

**Comment by aquynh** [comment]
`pip install capstone` does not work for Windows, so you need `pip install capstone-windows`.

regarding this issue, perhaps you are missing the runtime library for MSVC (MSVCRT) that capstone.dll depends on.

**Comment by brupelo** [comment]
Ok, I'll stick to capstone-windows, in any case, the error persists.

I got installed on my laptop msvc2008, 2010, 2013 and 2015, so the MSVC runtime library missing is unlikely?

Take a look to what [dependency walker tells about it](http://screencast.com/t/koOjTXRwIe), does that give you any clue to narrow down the issue?

**Comment by lucasg** [comment]
@brupelo : are you using a 32-bit Windows ? That would explain the system32 dll (kernel32, etc.) listed as x86 in depend.exe and the fact that could not be able to load the x64 capstone dll.

Otherwise you're just using the 32-bit version of depend.exe which is kinda bugged on x64 platforms.

**Comment by brupelo** [comment]
@lucasg No, I'm using 64-bit windows7 ultimate. Also I've tried installing capstone-windows on `Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32` .

Btw, you're right, the dependency walker i'm using is x86... let me find whether there is any 64-bit alternative to check what's going on with that dll, thanks to point out this fact :)

**Comment by brupelo** [comment]
@lucasg @aquynh Alright, I've tried dependency walker x64 and here's the [results](http://screencast.com/t/Vhhm8Htlz). So, any other suggestion to know what's going on here? As i've mentioned at the beginning of the thread I'm installing capstone on a virtualenv, which is installing capstone in this path `D:\virtual_envs\py351\Lib\site-packages\virtual_envs\py351\Lib\site-packages\capstone` , it seems to me that path is kinda of strange...

**Comment by brupelo** [comment]
@lucasg @aquynh FYI, installing capstone-windows using `easy_install` didn't spawn the previous mentioned error. So, my conclusion is, the `pip installation` is just buggy.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
