### ISSUE TITLE
ARM: thumb2 invalid disassembling

### ISSUE THREAD

**Issue by wodz** [capstone-engine/capstone#828]
Code compiled for cortex-m0 has this instructions which capstone 3.0.4 doesn't know. Binutils objdump returns correct disasm.

f3ef 8210       mrs     r2, PRIMASK
f382 8810       msr     PRIMASK, r2

**Comment by wodz** [comment]
Ok, after some googling around adding CS_MODE_MCLASS solves this BUT http://www.capstone-engine.org/lang_python.html doesn't mention this flag at all.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
