### ISSUE TITLE
ARM: Incorrect register access information for STMDB

### ISSUE THREAD

**Issue by Dil4rd** [capstone-engine/capstone#829]
For some reason stored registers are marked as `CS_AC_READ | CS_AC_WRITE`, but should be just `CS_AC_READ`.

# Example

Arch = `CS_ARCH_ARM`, mode = `CS_MODE_LITTLE_ENDIAN`
```
0x0:    00 D8 2D E9 push    {fp, ip, lr, pc}
    implicit_regs_read = [u'sp']
    implicit_regs_write = [u'sp']
    regs_read = [u'sp', u'fp', u'ip', u'lr', u'pc']
    regs_write = [u'sp', u'fp', u'ip', u'lr', u'pc']
    op_count: 4
        operands[0].type: REG = fp
        operands[0].type: REG_ACCESS = 3
        operands[1].type: REG = ip
        operands[1].type: REG_ACCESS = 3
        operands[2].type: REG = lr
        operands[2].type: REG_ACCESS = 3
        operands[3].type: REG = pc
        operands[3].type: REG_ACCESS = 3
```
## Expected
Read: `sp`, `fp`, `ip`, `lr`, `pc`

Written: `sp`

## Actual
Read: `sp`, `fp`, `ip`, `lr`, `pc`

Written: `sp`, `fp`, `ip`, `lr`, `pc`

**Comment by Dil4rd** [comment]
Dirty trick to fix

# In file arch/ARM/ARMInstPrinter.c
It looks like that the bug reason is that  `MI->ac_idx` is never used before `printRegisterList` function call.  So `MI->ac_idx` isn't incremented anywhere and `printRegisterList` function uses access pattern for operand 0.

So inside function `printRegisterList` we can add `1` to `MI->ac_idx` as shown below and it will works just fine.

```cpp
static void printRegisterList(MCInst *MI, unsigned OpNum, SStream *O)
{
// ... init vars and print "{"
#ifndef CAPSTONE_DIET
        if (MI->csh->detail) {
                // add 1 to current value of MI->ac_idx
                access = get_op_access(MI->csh, MCInst_getOpcode(MI), MI->ac_idx + 1);
        }
#endif
// ... other code
```
 But, incrementing `MI->ac_idx` in `ARM_printInst` before `printRegisterList` call and maybe then inc it inside `printRegisterList` function looks like a better way to fix this bug.

# In file arch/ARM/ARMMappingInsnOp.inc
Add second item with value `CS_AC_READ` to those `ARM_*STM*` opcodes, which have it set to zero.
## Before
```cpp
// ...
{   /* ARM_FSTMXDB_UPD, ARM_INS_FSTMDBX: fstmdbx${p}    $rn!, $regs */
    { CS_AC_READ | CS_AC_WRITE, 0 }
},
{   /* ARM_FSTMXIA, ARM_INS_FSTMIAX: fstmiax${p}    $rn, $regs */
    { CS_AC_READ, 0 }
},
{   /* ARM_FSTMXIA_UPD, ARM_INS_FSTMIAX: fstmiax${p}    $rn!, $regs */
    { CS_AC_READ | CS_AC_WRITE, 0 }
},
// ...
```
## After
```cpp
// ...
{       /* ARM_FSTMXDB_UPD, ARM_INS_FTMDBX: fstmdbx${p} $rn!, $regs */
        { CS_AC_READ | CS_AC_WRITE, CS_AC_READ, 0 }
},
{       /* ARM_FSTMXIA, ARM_INS_FSTMIAX: fstmiax${p}    $rn, $regs */
        { CS_AC_READ, CS_AC_READ, 0 }
},
{       /* ARM_FSTMXIA_UPD, ARM_INS_FSTMIAX: fstmiax${p}        $rn!, $regs */
        { CS_AC_READ | CS_AC_WRITE, CS_AC_READ, 0 }
},
// ...
```

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)

**Comment by Invincibl-e** [comment]
> Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue. thx :)

Is the current version ready to give up without consideration of maintenance, arm64 below the cmp instruction also has similar problems, 5.0 when to release?

**Comment by kabeor** [comment]
@Invincibl-e We have found a way to auto sync instructions with newest LLVM version and working on merging it into capstone 5. It's just going to take a while. Then Next branch will become master branch.
