### ISSUE TITLE
[PowerPC] Branch Conditional Ignores Reserved BO Value

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#831]
The value `00101` is a reserved value for the BO field of branch instructions.

Input Bytes: `40 b6 5a 45`
Capstone Output: `bnel cr5, 0x5a44`

Although this output may correspond to similar behavior to the identified instruction, when assembled, this instruction is different.

Using gas, I assembled the Capstone output and found that the BO field was changed to a non-reserved BO value, `40 96 5a 45`

This behavior is confirmed on the next branch.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
