### ISSUE TITLE
Implement Pointer Authentication instructions for ARM64

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#840]
https://www.qualcomm.com/news/onq/2017/01/10/qualcomm-releases-whitepaper-detailing-pointer-authentication-armv83

**Comment by aquynh** [comment]
this is in TODO list

**Comment by XVilka** [comment]
2 years anniversary soon. Any celebration is planned for this one?

**Comment by aquynh** [comment]
Yes of course.

**Comment by gkpln3** [comment]
Any updates?

**Comment by trufae** [comment]
just use cs5. its implemented there, but after 5 years no release has happened yet in here. it's the default version used in r2 for a while, but you may probably have a look at vector35 disassembler which are way better maintained and i completely lost my hope in having a tag for everyone to package the release which literaly takes 2 seconds to do

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
