### ISSUE TITLE
[PPC] Invalid TBR number for MFTB instruction.

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#853]
The instruction `mftb 26, 327` from bytes `7f 47 52 e6` has an invalid second operand. Using gas to compile the instruction results in the error "Invalid tbr number". The second operand can only be 268 or 268.

**Comment by aquynh** [comment]
binutils also decodes "7f 47 52 e6" as "mftb 26, 327". 
is there any disassembler that decodes it as "mftb 26, 268"?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
