### ISSUE TITLE
[PPC] Branch to LR has extra operand

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#855]
(EDIT): The branch instruction has an exta operand, according to gas. The 0x8 doesn't correspond to any operand documented in the manuals, as far as I can tell.

Bytes: `4c 00 10 20`
Capstone Output: `bdnzflr lt, 0x8`
Accepted Output: `bdnzflr lt`

**Comment by aquynh** [comment]
we have this output now (code in the "next" branch)

```
$ cstool -d ppc64be 4c001020 
 0  4c 00 10 20  bclr	0, cr0lt, 2
	ID: 36 (bclr)
	op_count: 3
		operands[0].type: IMM = 0x0
		operands[1].type: REG = cr0lt
		operands[2].type: IMM = 0x2
```

any comments?

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
