### ISSUE TITLE
[MIPS] Report from r2r

### ISSUE THREAD

**Issue by Maijin** [capstone-engine/capstone#857]
Greetings,

Here is the report from r2r on the current opcodes that we found that seems to be missing/incorrect/invalid on capstone. This can be wrong but if you could take a look and tell us that would be great:

| Hex      | Current           | Expected           |
|----------|-------------------|--------------------|
| 00000050 | beqzl zero, 8     | beql zero, zero, 8 |
| 00000055 | bnezl t0, 8       | bnel t0, zero, 8   |
| 000000d8 | ldc2 0, (zero)    | bbit032 zero, 0, 8 |
| 000000c8 | lwc2 0, (zero)    | bbit0 zero, 0, 8   |
| 000000f8 | sdc2 0, (zero)    | bbit132 zero, 0, 8 |
| 000000e8 | swc2 0, (zero)    | bbit1 zero, 0, 8   |
| 000000dc | ld zero, 0(zero)  | ldc3 0, (zero)     |
| 000000fc | sd zero, (zero)   | sdc3 0, (zero)     |
| 00000042 | c0 0x0            | invalid            |
| 00000047 | c1 0x1000000      | bz.b w0, 8         |
| 0000004a | c2 0x0            | invalid            |
| 0000004b | paddsh f0, f0, f0 | invalid            |

**Comment by Maijin** [comment]
@radare

**Comment by noobdoesre** [comment]
Maybe dublicate case (MIPS64 Big Endian), but still looks odd to me:

| Hex        | Current           | Expected  |
| ------------- |:-------------:| -----:|
| df820120      | ld $v0, ($gp) | ld $v0, 0x120($gp) |

**Comment by radare** [comment]
@aquynh

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
