### ISSUE TITLE
fail to load the dynamic library when sudo pip install capstone on macOS 10.12 

### ISSUE THREAD

**Issue by liuxuan30** [capstone-engine/capstone#858]
so everything works fine while installing via `sudo pip install capstone` on macOS 10.12,
however when trying to import, it reports error:
```
>>> from capstone import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```
I searched some similar issues, but none work for me. The version is 3.0.4, my python is 2.7

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
