### ISSUE TITLE
brew install capstone will lead to  No module named capstone on macOS 10.12

### ISSUE THREAD

**Issue by liuxuan30** [capstone-engine/capstone#859]
So I had another post #858 which uses pip to install.
Now I change to brew install capstone, which is also 3.0.4. Then no matter whether I use `export DYLD_LIBRARY_PATH=/opt/local/lib/:$DYLD_LIBRARY_PATH` or not, when trying to import, it shows:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named capstone
```
Looks like on macOS 10.12, there is something changed? Both pip and brew install have different import issues.

**Comment by liuxuan30** [comment]
interestingly, if I use brew and pip both install capstone, although it seems duplicate, however it actually works...

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
