### ISSUE TITLE
ARM64 immediate storage bugs (likely others)

### ISSUE THREAD

**Issue by saurik** [capstone-engine/capstone#860]
The ARM64 backend is truncating immediate values returned through the detail parameter due to a combination of a ["fix warnings reported by MSVC" patch](https://github.com/aquynh/capstone/commit/07c92ec20a031d88d4dd9d241aa4705679f43fee) that started casting a number of values to int which was *followed* by a [semantics fix for ARM64 immediates](https://github.com/aquynh/capstone/commit/56128da51596899cd033c286f9ac6e42cca814dd) which made the imm parameter int64_t instead of int. I tried just removing all the casts with a search/replace of "imm = (int)" to "imm = " (which is *probably* the correct behavior, under an assumption that all of those casts were a "poor man's /wd flag", and so now that the field is wider, as many casts as possible should just be removed, in the hope they aren't semantic), and it sort of looked like it worked... but given that I ran into this issue after only a few hours of playing with this library, I can't vouch for anything working, really. (Oh: an example instruction is 0xe9f301b2, which is "orr x9, xzr, #0xaaaaaaaaaaaaaaaa".)

**Comment by aquynh** [comment]
Please provide the input & expected output.

Is this on master branch? Can you try with the "next" branch?

**Comment by aquynh** [comment]
what is your expected output for 0xe9f301b2?

**Comment by saurik** [comment]
This is on the "master" branch. I provided the expected output: 0xaaaaaaaaaaaaaaaa. The actual output is truncated to a 32-bit number, 0xaaaaaaaa. This is due to the code I linked to, which type casts values to (int) before storing them: immediate values on arm64 are 64-bit (which, as I also already described, was something the capstone code learned after sprinkling these casts all over the place). It is my impression that the "next" branch has a different API than the "master" branch: given that I've provided examples of exact instructions and even explained what the problem is in the code, could you maybe just use a test case you have to verify the bug and get it fixed? ;P

**Comment by saurik** [comment]
OK, I just checked the code of the "next" branch, and I see that there was a single fix put in for this issue, but given how many casts to (int) there are there is almost no way this is a sufficient way to fix the problem. It will likely be "sufficient" for the one case I ran into a few days ago, given that this is the same instruction I was having an issue with, but the core problem is trying to use type casts to deal with warnings, particularly if you aren't 100% sure what the size of the underlying type is (as in this case it changed a month later): all of the int casts should be pulled and if MSVC is still giving warnings (which is now unlikely) the underlying problem should be addressed without adding more casts.

https://github.com/aquynh/capstone/commit/9271db7c7f6005920853a2fd009c978f6348684f

**Comment by aquynh** [comment]
i pushed a fix for this issue to the new "test" branch. can you try & confirm this is fixed?
("test" is forked from "master")

**Comment by aquynh** [comment]
Let me know, so i can merge "test" branch to master and next branches.

**Comment by aquynh** [comment]
i merged the "test" branch to "master" now.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
