### ISSUE TITLE
PyPi package for v4.0-alpha4

### ISSUE THREAD

**Issue by zachriggle** [capstone-engine/capstone#866]
Is there any chance we could get a `pip` version of the v4 alpha release?

It'd make distributing packages much easier than relying on Capstone as a Git submodule, and building from source manually.

**Comment by aquynh** [comment]
how about doing that with pip, like this:

    sudo pip install "https://github.com/aquynh/capstone/archive/next.zip#egg=capstone&subdirectory=bindings/python"

**Comment by zachriggle** [comment]
That could work. Can you put that in the reader for that branch?

**Comment by aquynh** [comment]
"in the reader"? do you mean README? feel free to pull req

**Comment by zachriggle** [comment]
Sorry, yes, on mobile. Can do. Assign this to me?

**Comment by aquynh** [comment]
sure. i did it.

**Comment by disconnect3d** [comment]
Bump, maybe even alpha5 ;P

**Comment by zachriggle** [comment]
@mossberg I agree wholeheartedly (I opened this bug), but you actually can get it in your `setup.py`, at least via `requirements.txt` (and maybe directly).

See here: https://github.com/pwndbg/pwndbg/blob/dev/requirements.txt#L12

**Comment by mossberg** [comment]
@zachriggle thanks!

> but you actually can get it in your setup.py, at least via requirements.txt (and maybe 

Not sure I totally understand the "via requirements.txt" part; our project actually does not use a requirements.txt file as our installation model doesn't involve users downloading our source tree (directly).

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
