### ISSUE TITLE
Got an Error when compiling in MS VS2015

### ISSUE THREAD

**Issue by noword** [capstone-engine/capstone#868]
> 1>..\..\arch\ARM\ARMInstPrinter.c(1162): error C4146: unary minus operator applied to unsigned type, result still unsigned

ARMInstPrinter.c line 1662:
`int v = (Imm & 256) ? ((Imm & 0xff) << 2) : -((Imm & 0xff) << 2);`

should be:
`int v = (Imm & 256) ? ((Imm & 0xff) << 2) : -((((int)Imm) & 0xff) << 2);`

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
