### ISSUE TITLE
Displacement size not available on x86_64

### ISSUE THREAD

**Issue by dwks** [capstone-engine/capstone#873]
Hi, I'm trying to parse x86_64 instructions with capstone, modify them, and output adjusted instructions. To do this I need to know the size of displacements in the instruction (to determine how many bytes to modify). However, capstone always rounds the sizes of all operands to the maximum size amongst all registers. For example, see this output:

```
66 83 c0 01             0x1000:  addw  $1, %ax
    arg[0]: (imm 0x1) size 2    # would like this to say 1
    arg[1]: (reg ax) size 2
83 c0 01                0x1004:  addl  $1, %eax
    arg[0]: (imm 0x1) size 4    # would like this to say 1
    arg[1]: (reg eax) size 4
48 83 c0 01             0x1007:  addq  $1, %rax
    arg[0]: (imm 0x1) size 8    # would like this to say 1
    arg[1]: (reg rax) size 8
```

Is there any way of obtaining the size in bytes of the displacement aside from manually parsing the opcode myself?

On a related note, when the argument sizes match, capstone curiously thinks there are actually three arguments! I assume this is a bug.

```
04 01                   0x100b:  addb  $1, %al
    arg[0]: (reg al) size 1
    arg[1]: (imm 0x1) size 1
    arg[2]: (reg al) size 1
66 05 ef be             0x100d:  addw  $0xbeef, %ax
    arg[0]: (reg ax) size 2
    arg[1]: (imm 0xbeef) size 2
    arg[2]: (reg ax) size 2
48 05 ef be ad 1e       0x1011:  addq  $0x1eadbeef, %rax
    arg[0]: (reg rax) size 8
    arg[1]: (imm 0x1eadbeef) size 8
    arg[2]: (reg rax) size 8
```

Any suggestions for my problem, or comments on this apparent bug? By the way, the above output is fully reproducible by running the following test case: https://github.com/dwks/capstone-dispsize

**Comment by aquynh** [comment]
Have you tried with the "next" branch yet?

**Comment by dwks** [comment]
I tried the "master" and "next" branches. They both fix the repeated-register bug, but leave the displacement sizes the same (using the maximum size amongst each operand). So unfortunately it doesn't help in my case.

**Comment by dwks** [comment]
Looks like the current behaviour is intentional (arch/X86/X86ATTInstPrinter.c):
```
 905     if (MI->has_imm) {
 906         // if op_count > 1, then this operand's size is taken from the destination op
 907         if (MI->flat_insn->detail->x86.op_count > 1) {
 908             if (MI->flat_insn->id != X86_INS_LCALL && MI->flat_insn->id != X86_INS_LJMP) {
 909                 for (i = 0; i < MI->flat_insn->detail->x86.op_count; i++) {
 910                     if (MI->flat_insn->detail->x86.operands[i].type == X86_OP_IMM)
 911                         MI->flat_insn->detail->x86.operands[i].size =
 912                             MI->flat_insn->detail->x86.operands[MI->flat_insn->detail->x86.op_count - 1].size;
 913                 }
 914             }
 915         } else
 916             MI->flat_insn->detail->x86.operands[0].size = MI->imm_size;
 917     }
```
I tried disabling that commented if, but then the reported operand sizes are strange. It varies between 4 and 8 bytes.
```
66 83 c0 01             0x1000:  addw  $1, %ax
    arg[0]: (imm 0x1) size 4
    arg[1]: (reg ax) size 2
83 c0 01                0x1004:  addl  $1, %eax
    arg[0]: (imm 0x1) size 8
    arg[1]: (reg eax) size 4
48 83 c0 01             0x1007:  addq  $1, %rax
    arg[0]: (imm 0x1) size 4
    arg[1]: (reg rax) size 8
04 01                   0x100b:  addb  $1, %al
    arg[0]: (imm 0x1) size 8
    arg[1]: (reg al) size 1
```
Capstone seems to use three representations of sizes: imm_size, op1_size, and opsize (as returned by X86_immediate_size() based on arch/X86/X86ImmSize.inc). imm_size doesn't work, op1_size is 0, and in the last case the data itself seems inaccurate. For instance, this first instruction
```
66 83 c0 01             0x1000:  addw  $1, %ax
```
is a X86_ADD16ri8 (79) and has imm size 2 in arch/X86/X86ImmSize.inc, whereas I would expect an imm size of 1. I'm not sure how this is decoding successfully; I suppose it's the masking of values that makes it work. Am I missing something here?

**Comment by dwks** [comment]
(didn't mean to close)

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
