### ISSUE TITLE
Sparc OOB read

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#876]
The line 1205 doesnt checks for boundaries and crashes

<img width="654" alt="screen shot 2017-03-22 at 03 12 17" src="https://cloud.githubusercontent.com/assets/917142/24179161/b937d486-0ead-11e7-9d4a-b273250c5349.png">

Reproducer https://github.com/radare/radare2/issues/7068

**Comment by aquynh** [comment]
What is input & expected output?

**Comment by radare** [comment]
I can find out this after the other crash is fixed. It appears to show up after the first crash with a different memory layout and valgrind

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
