### ISSUE TITLE
Access to regs_read and regs_write

### ISSUE THREAD

**Issue by frapik99** [capstone-engine/capstone#878]
Hi,
I have an instruction that if printed using ```op_str``` I have the following result:

```
In [20]: i.op_str
Out[20]: u'qword ptr [rip + 0x204eda]'
```

but if i have the following weird case:

```
In [21]: i.regs_read
Out[21]: []

In [22]: i.regs_write
Out[22]: []

In [23]: i.regs_access

```

How is it possible?

Also, how the method ```op_str``` is able to obtain ```rip``` if ```regs_access``` is empty?

Thanks a lot

**Comment by aquynh** [comment]
the documentation mentions all this: what you are seeing is just list of **implicit** registers being accessed: https://github.com/aquynh/capstone/blob/master/include/capstone.h#L600-L613

instead, you need this API **cs_regs_access**, available in the next branch: http://www.capstone-engine.org/op_access.html

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
