### ISSUE TITLE
How to retrieve destination of Immediate operands (x86)

### ISSUE THREAD

**Issue by stevemk14ebr** [capstone-engine/capstone#882]
x86_OP_IMM types such as :
`0x75 0xE4 jne  0x1800182B0               when @0x1800182CA (base + 0xE4(neg) + 0x2)`
and
`0xE8 0xCB 0x57 0x01 0x00 call 0x18002DA9C when @0x1800182CC (base + 0x157CB + 0x5)`

I need to find where the final address of a jmp/call/conditional jmp points to. I can current read out the displacement just find using the encoding branch of capstone with this:

```
ExtractDisplacement(Instruction &Inst, const cs_insn *CapInst)
{
    cs_x86 *x86 = &(CapInst->detail->x86);
    for (uint_fast32_t j = 0; j < x86->op_count; j++) {
        cs_x86_op *op = &(x86->operands[j]);
        if (op->type == X86_OP_MEM)
        {
           //other stuff
        }else if(op->type == X86_OP_IMM){
            //IMM types are like call 0xdeadbeef
            if (x86->op_count > 1) //exclude types like sub rsp,0x20
                continue;


            int64_t Base = 0;
            if(HasGroup(CapInst,x86_insn_group::X86_GRP_JUMP) ||
               HasGroup(CapInst,x86_insn_group::X86_GRP_CALL))
            {
                Base = Inst.GetAddress();
            } else
                continue;

            const uint8_t Offset = x86->encoding.imm_offset;
            const uint8_t Size = x86->encoding.imm_size;

            int64_t displacement;
            memset(&displacement,0x00,sizeof(typeof(displacement)));
            memcpy(&displacement,&Inst.GetBytes()[Offset], Size);

            **uint64_t Destination = Base + displacement + Inst.Size();**
```
That last line doesn't work however for this JMP as i need to negate the displacement (i think?). How can this be done better, surely capstone can tell me where an instruction points to since it must print that info for a string view??

I want it to be as simple as CapInst->GetDestinationAddress()

The closest thing i could find was: https://github.com/aquynh/capstone/blob/master/arch/X86/X86Disassembler.c#L140
But this is not exposed in the public API

Also can the encoding branch PLEASE be merged into next (and encoding be supported in general). So many people have asked for encoding to be exposed, it's a huge pain to have to parse instructions like this manually when capstone has all the necessary info bundled in internal structures.

**Comment by dwks** [comment]
On x86, you should be able to compute the target of a RIP-relative JMP by adding the displacement to the instruction address. The only wrinkle is that the CPU evaluates RIP after the instruction fetch stage so it will have already advanced to the next instruction; hence you need the address of the instruction plus its size:
```
auto dest = ins->detail->x86.disp + ins->address + ins->size;
```
Now, I hadn't noticed before but there is actually a macro for this in x86.h:
```
// Calculate relative address for X86-64, given cs_insn structure
#define X86_REL_ADDR(insn) (insn.address + insn.size + insn.detail->x86.disp)
```
So I'd just use that.

**Comment by stevemk14ebr** [comment]
Thanks, i figured it out. I was storing the displacement in an int64_t so i had to sign extend the smaller displacements when they were negative.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
