### ISSUE TITLE
Can't import capstone on Windows, getting "ImportError("ERROR: fail to load the dynamic library.")"

### ISSUE THREAD

**Issue by mkravchik** [capstone-engine/capstone#885]
Hi,

I've got capstone by "pip install capstone". running on Windows 10, Python 2.7
I can't import it, 
`>>> import capstone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\capstone\__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
`
The capstone.dll resides in C:\Python27\Lib\site-packages\capstone

**Comment by mkravchik** [comment]
Using the installer from releases works though

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
