### ISSUE TITLE
Do not spit tabs

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#892]
Tabs are non-constant size characters, which can be problematic for integrating in other tools or printing data into the terminal, because that should be used by the app, no the lib. The capstone codebase contains 162 places where this is done on x86, sysz, mips, arm and arm64. 

```
$ git grep '\\t' *| grep SStream_concat|wc -l
     162
```

Replacing this all the tabs for a single space should be enough to solve this issue. i'll do a PR later today.

```
- SStream_concat0(O, "\t");
+ SStream_concat0(O, " ");
```

**Comment by aquynh** [comment]
This may break some apps relying on tabs after mnemonic, so sorry no i dont
want this.

**Comment by aquynh** [comment]
Ah no this is internal code, not exposed to the API. How do you benefit
from this change?

**Comment by radare** [comment]
if you want so, why not be consistent at least?

**Comment by radare** [comment]
if this tab is suposed to be after the instruction, it should be only in 1 place, not in 162

**Comment by aquynh** [comment]
i dont see any benefits from this change, while it can break something,
that you cannot detect without enough tests.

**Comment by radare** [comment]
I dont see any benefit in having tabs in random places only for some architectures, this is not consistent. I propose to remove them all because the developer who uses capstone can perfectly grab the instruction and the arguments separately and construct the string in the way he wants.

This shouldn't break anything in r2land. And if the purpose of having a tab is to separate instruction and arguments, this should be in only 1 place. If this change breaks any app is because the app did wrong assumptions.

**Comment by aquynh** [comment]
I think you misunderstood this issue here: the tabs you see never show up
at the final output of cs_disasm() anywhere. if you see anything like that,
let me know.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
