### ISSUE TITLE
TMS320 c64x : issues found by clang-analyzer

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#894]
* [ ] http://cloud.radare.org/beta/20170418/report-1bc98e.html#EndPath
* [ ] http://cloud.radare.org/beta/20170418/report-c45ce9.html#EndPath

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
