### ISSUE TITLE
ARM : issue found by clang-analyzer

### ISSUE THREAD

**Issue by radare** [capstone-engine/capstone#895]
* http://cloud.radare.org/beta/20170418/report-605904.html#EndPath

<img width="497" alt="screen shot 2017-04-18 at 02 46 19" src="https://cloud.githubusercontent.com/assets/917142/25110208/6200ace8-23e2-11e7-985b-3e3b92b89e7e.png">
<img width="679" alt="screen shot 2017-04-18 at 02 46 32" src="https://cloud.githubusercontent.com/assets/917142/25110209/62019b6c-23e2-11e7-9e67-687bf06feee6.png">

**Comment by aquynh** [comment]
what is wrong here?

**Comment by radare** [comment]
The problem is that using 0 as a terminator identifier conflicts with ARM_BL.

**Comment by aquynh** [comment]
this is false positive.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
