### ISSUE TITLE
Why some instructions belong to no group

### ISSUE THREAD

**Issue by roj4s** [capstone-engine/capstone#900]
Below code when executed outputs instructions that are included in no group by capstone's instruction grouping model. I get instructions like: add, test, mov, sub and nop. Why are these instructions in no group? Thanks in advance.

for i in md.disasm(code, int(ins_addr, 16)):
   if len(i.groups) == 0:
    print("\tThis instruction belongs to no group")
    print("0x%x:\t%s\t%s" % (i.address, i.mnemonic, i.op_str))

**Comment by aquynh** [comment]
On Apr 22, 2017 5:49 AM, "Luis Miguel Rojas Aguilera" <
notifications@github.com> wrote:

Below code when executed outputs instructions that are included in no group
by capstone's instruction grouping model. I get instructions like: add,
test, mov, sub and nop. Why are these instructions in no group?

Then which groups do you think they belong to?

**Comment by roj4s** [comment]
Don't know, I was hoping you could tell me lol ... What's the criteria used for grouping?

**Comment by aquynh** [comment]
We classify instruction group according to how LLVM does. It is possible to add new groups for those you mentioned.

**Comment by roj4s** [comment]
Where can I find a description on this classification model used by LLVM ??

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
