### ISSUE TITLE
[x86] Instruction with incorrect VEX.W value decoded as valid

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#902]
This instruction is invalid because the third byte must have a leading zero (for the W bit of the vex prefix).

Bytes: 8f 8 f0 86 25 24 bf 73 eb ba
Capstone Output: vpmacsswd %xmm11, -344735964(%rip), %xmm1, %xmm12
Expected: decoder should return error

**Comment by aquynh** [comment]
this is invalid code for the "next" branch

**Comment by nathanhjay** [comment]
Using 64-bit, it appears to be valid.

`./cstool x64att "8f 08 f0 86 25 24 bf 73 eb ba"`
`0  8f08f0862524bf73ebba              vpmacsswd  %xmm11, -0x148c40dc(%rip), %xmm1, %xmm12`

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
