### ISSUE TITLE
[x86] EVEX write mask uses {%k0}{z} when just {z} is expected

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#903]
I think the %k0 mask register is either 1. being printed when implicitly used, or 2. should not be used here. I tried assembling capstone output using gas and got an error about the write mask.

Bytes: 62 81 14 c8 5f d5 
Capstone Output: vmaxps %zmm29, %zmm13, %zmm18 {%k0}{z}
Error from gas: `%k0}{z}' can't be used for write mask
Expected: vmaxps %zmm29, %zmm13, %zmm18{z}

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
