### ISSUE TITLE
[x86] Using CS_MODE_64 still decodes 32-bit mode only instructions as valid.

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#904]
Even when configured with CS_MODE_64, Capstone decodes instructions that should only be available in 32-bit mode as valid.

Bytes:          4b c4 1d d5 b9 aa 3a 
Output:         lesl 0x3aaab9d5(%rip), %rbx
Error from gas: `les' is not supported in 64-bit mode
Expected:       decoder to return error

**Comment by aquynh** [comment]
fixed now, please confirm

**Comment by nathanhjay** [comment]
The issue is fixed for LES, but it appears to happen for LDS as well. Example (from "next"):

`$ ./cstool x64att "41 c5 16 60"`
`0  41c516                            ldsl       (%r14), %edx`

I don't see any other opcodes with this particular issue.

**Comment by aquynh** [comment]
fixed now, thanks.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
