### ISSUE TITLE
[x86] XCHG instruction with data16 prefix decoded with two different sized operands

### ISSUE THREAD

**Issue by nathanhjay** [capstone-engine/capstone#906]
The XCHG instruction should have the same size operands, even in the presence of a data16 prefix as below.

Bytes:          66 3e 97 
Output:         xchgl %di, %eax
Error from gas: register type mismatch for `xchg'
Expected:       xchg %ax,%di

**Comment by aquynh** [comment]
Are these reports all on master branch? If so, can you confirm the results
on the "next" branch?

**Comment by nathanhjay** [comment]
These issues are on master. I'll work on confirming them on "next". I can go through my open x86 issues and work on that.

**Comment by aquynh** [comment]
We have a tool named cstool, you can use that to test your input.

**Comment by aquynh** [comment]
which Capstone version are you using? on "master", i have different result from what you report.

```
$ cstool x32att "66 3e 97"
0  663e97                            xchgw	%di, %ax
```

**Comment by nathanhjay** [comment]
My capstone version is listed as 3.0.4. What's the best way for me to get cstool? Is it just a matter of pulling the lastest fixed and building?

**Comment by aquynh** [comment]
you just pull from Git, and follow the docs to compile.

on Linux, or Mac, or any Nix machines, just do:

```
$ ./make.sh
$ sudo ./make.sh install
```

**Comment by nathanhjay** [comment]
Issue exists for 64-bit mode on "next":

`$ ./cstool x64att "66 3e 97"
0  663e97                            xchgl      %di, %eax`

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
