### ISSUE TITLE
last coverity bug report

### ISSUE THREAD

**Issue by trufae** [capstone-engine/capstone#911]
https://gist.github.com/trufae/5ad6e5473eeba2b6954e3c89a0b87ccb

**Comment by aquynh** [comment]
this is for the "next" branch, right?

except an issue on Arm about dead code, the rest are false positive.

the real problems are with the new architecture TMS320C64x

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
