### ISSUE TITLE
pip install capstone uses wrong path for DSO

### ISSUE THREAD

**Issue by zachriggle** [capstone-engine/capstone#916]
On a virgin Ubuntu docker image, after `pip install capstone`, Capstone does not actually function properly.

```
$ docker pull ubuntu:xenial
$ docker run -it ubuntu:xenial
```

```
root@fae1494afd2b:/# apt-get -qq update
root@fae1494afd2b:/# apt-get -qq -y install python-pip
root@fae1494afd2b:/# pip install -U capstone
Collecting capstone
  Downloading capstone-3.0.4.tar.gz (3.2MB)
    100% |################################| 3.2MB 444kB/s
Building wheels for collected packages: capstone
  Running setup.py bdist_wheel for capstone ... done
  Stored in directory: /root/.cache/pip/wheels/7c/d1/d0/db6e2c5ef1063aabb9de2dd8b92b4c27ee6f9fd213240099b8
Successfully built capstone
Installing collected packages: capstone
Successfully installed capstone-3.0.4
```

Looks like everything worked!

```
root@fae1494afd2b:/# python -c 'import capstone'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

It looks like there's an issue with the path used by Capstone.  If we try to find the library, we come across:

```
root@fae1494afd2b:/# find /usr -iname 'libcapstone*'
/usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/capstone/libcapstone.so
```

Which is clearly wrong.  I assume it's attempting to use the path:

```
/usr/lib/python2.7/dist-packages/capstone/libcapstone.so
```

If we symlink the two, everything works:

```
root@fae1494afd2b:/# mkdir -p /usr/lib/python2.7/dist-packages/capstone/
root@fae1494afd2b:/# ln -s /usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/capstone/libcapstone.so /usr/lib/python2.7/dist-packages/capstone/
root@fae1494afd2b:/# python -c 'import capstone'
root@fae1494afd2b:/#
```

**Comment by aquynh** [comment]
yes version 3.0.4 has some issues. why dont you pip from Github instead?

**Comment by zachriggle** [comment]
Because the released versions should work 😜 -- that's why they exist!

**Comment by disconnect3d** [comment]
It's two months already. Hope this will be fixed in 3.0.5.
Any ETA? :)

**Comment by aquynh** [comment]
Yes, this month July.

**Comment by aquynh** [comment]
to be sure we have no major issues for v3.0.5, i have tagged v3.0.5-rc3, the final RC version. 
v3.0.5 will follow soon

**Comment by zachriggle** [comment]
Did this get fixed?

**Comment by zachriggle** [comment]
Hey, @aquynh -- Any timeline for a 3.0.5 release?  PyPi still only has 3.0.4 (and doesn't even have 3.0.5-rc3, just rc2).

https://pypi.python.org/pypi/capstone

**Comment by bannsec** [comment]
Random comment here, but when i have run into this issue, rc2 from pip fixed it.

**Comment by zachriggle** [comment]
Ping?

**Comment by E3V3A** [comment]
Pong!? :100:

**Comment by E3V3A** [comment]
This issue may have been resolved by following this [updated installation procedure](https://github.com/aquynh/capstone/issues/1273),
when using **`Cygwin`** and **`Python3`**. 
A new [Wiki page](https://github.com/aquynh/capstone/wiki/Installing-on-Cygwin-&-Python3) has been added, describing the procedure.

**Comment by kabeor** [comment]
Close this issue for now because of legacy, we are preparing to release Capstone 5.0, plz feel free to open a new issue if that still has this issue.
thx :)
