### ISSUE TITLE
is support NASM( or masm/intel / att)  syntax ? 

### ISSUE THREAD

**Issue by stonedreamforest** [capstone-engine/capstone#997]
such API like this：

- nasm:

cs_disasm(handle, CODE, sizeof(CODE)-1, 0x1000, 0, &insn,"**nasm**");

- masm:

cs_disasm(handle, CODE, sizeof(CODE)-1, 0x1000, 0, &insn,"**masm**");

- intel:

cs_disasm(handle, CODE, sizeof(CODE)-1, 0x1000, 0, &insn,"**intel**");

- att:

cs_disasm(handle, CODE, sizeof(CODE)-1, 0x1000, 0, &insn,"**att**");

**Comment by aquynh** [comment]
see section 5 in this tutorial for how to set the asm syntax: http://www.capstone-engine.org/lang_c.html

for now, we dont support nasm & masm syntax.

**Comment by stonedreamforest** [comment]
thanks

**Comment by aquynh** [comment]
actually we do support Masm syntax, with option CS_OPT_SYNTAX_MASM.

**Comment by stonedreamforest** [comment]
I think it's more necessary to support NASM，Because it's cross platform

**Comment by aquynh** [comment]
yes that should not be too hard. you are welcome to send pull req for NASM syntax support.

**Comment by stonedreamforest** [comment]
I have a lot of ideas, And I want to be involved in a lot of projects, too.
But my code style and English are not very good
So, on some things
for example
Variables names, functions names, and so forth...
The will  use is not correct
And that's why I want to be involved, but I can't take part.

**Comment by aquynh** [comment]
I can read your code, which is in English, and i can help to cleanup)fix,
so no worry.

**Comment by stonedreamforest** [comment]
ok，I'll read the captone source code .And then try to write, but it might take some time because I don't have much free time
